### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-3 @ encode_decode.py

### ISSUE THREAD

**Issue by andresriancho** [andresriancho/w3af#10267]
```pytb
New URL found by web_spider plugin: "..."
encoding error : input conversion failed due to input error, bytes 0x98 0xD0 0xA0 0xD0
encoding error : input conversion failed due to input error, bytes 0x98 0xD0 0xA0 0xD0
Exception in thread PoolResultHandler:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/skoval/w3af/w3af/core/controllers/threads/pool276.py", line 453, in _handle_results
    cache[job]._set(i, obj)
  File "/home/skoval/w3af/w3af/core/controllers/threads/pool276.py", line 624, in _set
    self._callback(self._value)
  File "/home/skoval/w3af/w3af/core/controllers/core_helpers/consumers/base_consumer.py", line 55, in _wrapper
    result = method(self, function_id, *args, **kwds)
  File "/home/skoval/w3af/w3af/core/controllers/core_helpers/consumers/crawl_infrastructure.py", line 174, in _plugin_finished_cb
    self._route_plugin_results(plugin)
  File "/home/skoval/w3af/w3af/core/controllers/core_helpers/consumers/base_consumer.py", line 55, in _wrapper
    result = method(self, function_id, *args, **kwds)
  File "/home/skoval/w3af/w3af/core/controllers/core_helpers/consumers/crawl_infrastructure.py", line 215, in _route_plugin_results
    elif self._is_new_fuzzable_request(plugin, fuzzable_request):
  File "/home/skoval/w3af/w3af/core/controllers/core_helpers/consumers/crawl_infrastructure.py", line 389, in _is_new_fuzzable_request
    if not self._variant_db.append(fuzzable_request):
  File "/home/skoval/w3af/w3af/core/data/db/variant_db.py", line 101, in append
    request_hash = fuzzable_request.get_request_hash(self.HASH_IGNORE_HEADERS)
  File "/home/skoval/w3af/w3af/core/data/request/request_mixin.py", line 54, in get_request_hash
    return hashlib.md5(self.dump(ignore_headers=ignore_headers)).hexdigest()
  File "/home/skoval/w3af/w3af/core/data/request/request_mixin.py", line 45, in dump
    request_head = self.dump_request_head(ignore_headers=ignore_headers)
  File "/home/skoval/w3af/w3af/core/data/request/request_mixin.py", line 68, in dump_request_head
    return u"%s%s" % (self.get_request_line(),
  File "/home/skoval/w3af/w3af/core/data/request/request_mixin.py", line 61, in get_request_line
    self.get_uri().url_encode(),
  File "/home/skoval/w3af/w3af/core/data/parsers/doc/url.py", line 725, in url_encode
    qs = '?' + str(self.querystring)
  File "/home/skoval/w3af/w3af/core/data/dc/urlencoded_form.py", line 98, in __str__
    return urlencode(d, encoding=self.encoding, safe='')
  File "/home/skoval/w3af/w3af/core/data/parsers/utils/encode_decode.py", line 146, in urlencode
    ele = ele.encode(encoding)
  File "/home/skoval/.virtualenvs/w3af/lib/python2.7/encodings/cp1251.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-3: character maps to <undefined>
```

## Original bug reporter
@skoval00 

## Related with
https://github.com/andresriancho/w3af/pull/7988

**Comment by skoval00** [comment]
Exception dissapeared, only this warnings are left
encoding error : input conversion failed due to input error, bytes 0x98 0x2E 0x20 0xD0
But I suppose this is some problem with the website's content.
