### ISSUE TITLE
netlib - AttributeError: 'module' object has no attribute '_lib'

### ISSUE THREAD

**Issue by 1d3df9903ad** [andresriancho/w3af#10716]
## Version Information
```
  Python version: 2.7.9 (default, Apr  2 2015, 15:33:21) [GCC 4.9.2]
  GTK version: 2.24.27
  PyGTK version: 2.24.0
  w3af version:
    w3af - Web Application Attack and Audit Framework
    Version: 1.6.55
    Revision: 7916db7c4e - 23 Jun 2015 23:33
    Branch: master
    Local changes: No
    Author: Andres Riancho and the w3af team.
```
## Traceback
```pytb
Traceback (most recent call last):
  File "/home/user/Secure/Sources/git/w3af/w3af/core/ui/gui/main.py", line 917, in _proxy_tool
    ProxiedRequests(self.w3af)
  File "/home/user/Secure/Sources/git/w3af/w3af/core/ui/gui/tools/proxywin.py", line 158, in __init__
    self.reload_options()
  File "/home/user/Secure/Sources/git/w3af/w3af/core/ui/gui/tools/proxywin.py", line 254, in reload_options
    self._start_proxy()
  File "/home/user/Secure/Sources/git/w3af/w3af/core/ui/gui/tools/proxywin.py", line 308, in _start_proxy
    self.proxy = InterceptProxy(ip, int(port), self.w3af.uri_opener)
  File "/home/user/Secure/Sources/git/w3af/w3af/core/controllers/daemons/proxy/intercept_proxy.py", line 48, in __init__
    name='LocalProxyThread')
  File "/home/user/Secure/Sources/git/w3af/w3af/core/controllers/daemons/proxy/proxy.py", line 110, in __init__
    port=port)
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/proxy/config.py", line 86, in __init__
    CONF_BASENAME)
  File "/usr/local/lib/python2.7/dist-packages/netlib/certutils.py", line 207, in from_store
    dh = cls.load_dhparam(dh_path)
  File "/usr/local/lib/python2.7/dist-packages/netlib/certutils.py", line 181, in load_dhparam
    bio = OpenSSL.SSL._lib.BIO_new_file(path, b"r")
AttributeError: 'module' object has no attribute '_lib'

```

**Comment by andresriancho** [comment]
Reported upstream https://github.com/mitmproxy/netlib/issues/78

**Comment by andresriancho** [comment]
Note that a new mitmproxy was released which might fix this. Need to related all this with #10821
