### ISSUE TITLE
GUI - BaseFrameworkException: The HTTP request is invalid

### ISSUE THREAD

**Issue by 1d3df9903ad** [andresriancho/w3af#11071]
## Version Information
```
  Python version: 2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]
  GTK version: 2.24.23
  PyGTK version: 2.24.0
  w3af version:
    w3af - Web Application Attack and Audit Framework
    Version: 1.7.2
    Revision: f91a13ca69 - 24 Jun 2015 20:09
    Branch: master
    Local changes: No
    Author: Andres Riancho and the w3af team.
```
## Traceback
```pytb
Traceback (most recent call last):
  File "/home/user/Documents/fuzzer/w3af/w3af/core/ui/gui/tools/fuzzy_requests.py", line 407, in _real_send
    fixContentLength)
  File "/home/user/Documents/fuzzer/w3af/w3af/core/data/url/extended_urllib.py", line 514, in send_raw_request
    fuzz_req = http_request_parser(head, postdata)
  File "/home/user/Documents/fuzzer/w3af/w3af/core/data/parsers/doc/http_request_parser.py", line 110, in http_request_parser
    raise BaseFrameworkException(msg)
BaseFrameworkException: The HTTP request is invalid.

```

**Comment by andresriancho** [comment]
This is a very, very, very rare race condition.
