### ISSUE TITLE
ValueError: u'fingerprint_WAF' is not in list @ use_profile

### ISSUE THREAD

**Issue by 1d3df9903ad** [andresriancho/w3af#11216]
## Version Information
```
  Python version: 2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]
  GTK version: 2.24.10
  PyGTK version: 2.24.0
  w3af version:
    w3af - Web Application Attack and Audit Framework
    Version: 1.6.54
    Distribution: Kali Linux
    Author: Andres Riancho and the w3af team.
```
## Traceback
```pytb
Traceback (most recent call last):
  File "/usr/share/w3af/w3af/core/ui/gui/profiles.py", line 387, in _use_profile
    self.w3af.profiles.use_profile(profile_obj.get_profile_file())
  File "/usr/share/w3af/w3af/core/controllers/core_helpers/profiles.py", line 186, in use_profile
    raise_on_error=False)
  File "/usr/share/w3af/w3af/core/controllers/core_helpers/plugins.py", line 182, in set_plugins
    set_dict[plugin_type](plugin_names)
  File "/usr/share/w3af/w3af/core/controllers/core_helpers/plugins.py", line 375, in _set_evasion_plugins
    self.plugin_factory()
  File "/usr/share/w3af/w3af/core/controllers/core_helpers/plugins.py", line 358, in plugin_factory
    self.order_plugins()
  File "/usr/share/w3af/w3af/core/controllers/core_helpers/plugins.py", line 325, in order_plugins
    plugin_type].index(plugin_name)
ValueError: u'fingerprint_WAF' is not in list

```

**Comment by andresriancho** [comment]
Dup ValueError: 'detect_reverse_proxy' is not in list #11062
