### ISSUE TITLE
NameError: global name 'webkit' is not defined

### ISSUE THREAD

**Issue by 1d3df9903ad** [andresriancho/w3af#11719]
## Version Information
```
  Python version: 2.7.10 (default, Jul 13 2015, 12:05:58) [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
  GTK version: 2.24.28
  PyGTK version: 2.24.0
  w3af version:
    w3af - Web Application Attack and Audit Framework
    Version: 1.7.4
    Revision: 894247654f - 29 Jul 2015 11:57
    Branch: master
    Local changes: Yes
    Author: Andres Riancho and the w3af team.
```
## Traceback
```pytb
Traceback (most recent call last):
  File "/Users/daniel.gray/tools/w3af/w3af/core/ui/gui/main.py", line 546, in _scan_director
    func()
  File "/Users/daniel.gray/tools/w3af/w3af/core/ui/gui/main.py", line 645, in _scan_start
    self.set_tabs(True)
  File "/Users/daniel.gray/tools/w3af/w3af/core/ui/gui/main.py", line 792, in set_tabs
    self._set_tab(sensit, _("Results"), scanrun.ScanRunBody)
  File "/Users/daniel.gray/tools/w3af/w3af/core/ui/gui/main.py", line 798, in _set_tab
    newone = realWidget(self.w3af)
  File "/Users/daniel.gray/tools/w3af/w3af/core/ui/gui/scanrun.py", line 675, in __init__
    kbbrowser = KBBrowser(w3af)
  File "/Users/daniel.gray/tools/w3af/w3af/core/ui/gui/scanrun.py", line 247, in __init__
    description = self.get_notebook_description()
  File "/Users/daniel.gray/tools/w3af/w3af/core/ui/gui/scanrun.py", line 262, in get_notebook_description
    self.description = webkit.WebView()
NameError: global name 'webkit' is not defined

```

**Comment by andresriancho** [comment]
`Local changes: Yes`
