### ISSUE TITLE
UnicodeDecodeError with unicode values in QS

### ISSUE THREAD

**Issue by kyprizel** [andresriancho/w3af#11997]
```
Exception in thread CrawlInfraController:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/user/w3af/w3af/core/controllers/core_helpers/consumers/crawl_infrastructure.py", line 90, in run
    self._route_all_plugin_results()
  File "/home/user/w3af/w3af/core/controllers/core_helpers/consumers/base_consumer.py", line 55, in _wrapper
    result = method(self, function_id, *args, **kwds)
  File "/home/user/w3af/w3af/core/controllers/core_helpers/consumers/crawl_infrastructure.py", line 202, in _route_all_plugin_results
    self._route_plugin_results(plugin)
  File "/home/user/w3af/w3af/core/controllers/core_helpers/consumers/base_consumer.py", line 55, in _wrapper
    result = method(self, function_id, *args, **kwds)
  File "/home/user/w3af/w3af/core/controllers/core_helpers/consumers/crawl_infrastructure.py", line 229, in _route_plugin_results
    elif self._is_new_fuzzable_request(plugin, fuzzable_request):
  File "/home/user/w3af/w3af/core/controllers/core_helpers/consumers/crawl_infrastructure.py", line 405, in _is_new_fuzzable_request
    if not self._variant_db.append(fuzzable_request):
  File "/home/user/w3af/w3af/core/data/db/variant_db.py", line 101, in append
    request_hash = fuzzable_request.get_request_hash(self.HASH_IGNORE_HEADERS)
  File "/home/user/w3af/w3af/core/data/request/request_mixin.py", line 56, in get_request_hash
    return hashlib.md5(self.dump(ignore_headers=ignore_headers)).hexdigest()
  File "/home/user/w3af/w3af/core/data/request/request_mixin.py", line 47, in dump
    request_head = self.dump_request_head(ignore_headers=ignore_headers)
  File "/home/user/w3af/w3af/core/data/request/request_mixin.py", line 70, in dump_request_head
    return u"%s%s" % (self.get_request_line(),
  File "/home/user/w3af/w3af/core/data/request/request_mixin.py", line 64, in get_request_line
    CRLF)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 133: ordinal not in range(128)
```
here is example where you can reproduce the problem:
http://dvwa.people.yandex.net/mgform.php

**Comment by andresriancho** [comment]
* Which w3af version are you using?
 * Could you give me a w3af script to reproduce this issue?

**Comment by kyprizel** [comment]
Here is example profile:
```
[misc-settings]
fuzz_url_filenames = False
fuzz_url_parts = False
fuzz_cookies = False
max_discovery_time = 120
form_fuzzing_mode = t

[crawl.web_spider]
only_forward = False
follow_regex = .*

[profile]
description = Default profile
name = test

[target]
target = http://dvwa.people.yandex.net/mgform.php

[output.text_file]
output_file = log.txt
http_output_file = http-log.txt
verbose = True

[output.xml_file]
output_file = log.xml
```
I tried both devel and 
```
Version: 1.7.4
Revision: 894247654f - 29 Jul 2015 11:57
```

**Comment by andresriancho** [comment]
I was able to reproduce with the profile yo sent, going to fix now

**Comment by andresriancho** [comment]
That tricky form is making w3af send multipart encoded stuff in the query string:

```
http://dvwa.people.yandex.net/mgform.php?--b08c02-53d780-e2bc43-1d5278-a3c0d9-a5c0d9\r\nContent-Disposition: form-data; name="test"\r\n\r\n\xd1\x82\xd0\xb5\xd1\x81\xd1\x82\r\n--b08c02-53d780-e2bc43-1d5278-a3c0d9-a5c0d9\r\nContent-Disposition: form-data; name="submit"\r\n\r\n\r\n--b08c02-53d780-e2bc43-1d5278-a3c0d9-a5c0d9--\r\n\r\n
```

**Comment by andresriancho** [comment]
Related with Handling of Multipart forms with GET method #11998

**Comment by andresriancho** [comment]
Original HTML:
```html
<html>
<head>
<meta charset="UTF-8">
</head>
<body>
<form action="" method="get" enctype="multipart/form-data" target="_self" id="tricky_form">
<input type="text" name="test" value="тест">
<input type="submit" name="submit" onclick="document.forms[0].method='POST'; return true;">
</form>
</body>
</html>
```

Form as seen by w3af:
```
<form action="" method="get" enctype="multipart/form-data" target=">
<input type="text" name="test" value="тест">
<input type="submit" name="submit">
</form>
```

This is confusing w3af, it seems to think that it should put the data in the query string but encode it as multipart instead of url-encode (which triggers the bug)

**Comment by andresriancho** [comment]
Tests are running in separate branch, when done they will be merged into develop
