### ISSUE TITLE
TypeError: must be string, not int

### ISSUE THREAD

**Issue by 1d3df9903ad** [andresriancho/w3af#12889]
## Version Information
```
  Python version: 2.7.9 (default, Mar  1 2015, 18:22:53) [GCC 4.9.2]
  GTK version: 2.24.25
  PyGTK version: 2.24.0
  w3af version:
    w3af - Web Application Attack and Audit Framework
    Version: 1.6.54
    Distribution: Kali Linux
    Author: Andres Riancho and the w3af team.
```
## Traceback
```pytb
Traceback (most recent call last):
  File "/usr/share/w3af/w3af/core/ui/gui/tabs/log/graph.py", line 92, in draw_handler
    reset = self._redraw_gen.next()
  File "/usr/share/w3af/w3af/core/ui/gui/tabs/log/graph.py", line 230, in _redraw_all
    mesind, None, None):
  File "/usr/share/w3af/w3af/core/data/db/disk_list.py", line 186, in __iter__
    obj = cPickle.loads(r[0])
TypeError: must be string, not int

```

**Comment by andresriancho** [comment]
Can't repro
