### ISSUE TITLE
GUI - invalid literal for int - dotcode

### ISSUE THREAD

**Issue by karstdiver** [andresriancho/w3af#12906]
My w3af seems to crash by it stopping to listen to GUI inputs after a scan completes.  I need to kill -9 all the w3af processes to get it to die.

Here is the shell transcript:

```console
kali@kali-HP:~$ sudo /usr/bin/w3af 
Starting w3af, running on:
  Python version: 2.7.9 (default, Mar  1 2015, 18:22:53) [GCC 4.9.2]
  GTK version: 2.24.25
  PyGTK version: 2.24.0
  w3af version:
    w3af - Web Application Attack and Audit Framework
    Version: 1.6.54
    Distribution: Kali Linux
    Author: Andres Riancho and the w3af team.
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.6) (7u79-2.5.6-1~deb8u1)
OpenJDK Client VM (build 24.79-b02, mixed mode)
Exception in thread GTKDraw:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/share/w3af/w3af/core/ui/gui/scanrun.py", line 419, in _draw_real
    raise ValueError(msg % args)
ValueError: A ValueError exception with message "invalid literal for int() with base 10: '86.3'" was found while trying to render a new dotcode. Please create a new bug report at https://github.com/andresriancho/w3af/issues/new including the following info:

['"<GtkTreeIter at 0xc673690>" [shape=box]',
 '"<GtkTreeIter at 0xc673690>" [label="http://localhost"]',
 '"<GtkTreeIter at 0xc85bda0>" [label="mutillidae"]',
 '"<GtkTreeIter at 0xc673690>" -- "<GtkTreeIter at 0xc85bda0>"']

Begin emission:
Finished to send 1 packets.
....................................................................................................................................
Received 132 packets, got 0 answers, remaining 1 packets
```

**Comment by andresriancho** [comment]
@karstdiver thanks for the bug report!

**Comment by andresriancho** [comment]
This is the graph generated from the user bug report:

```xdot
graph G {
    "<GtkTreeIter at 0xc673690>" [shape=box]
    "<GtkTreeIter at 0xc673690>" [label="http://localhost"]
    "<GtkTreeIter at 0xc85bda0>" [label="mutillidae"]
    "<GtkTreeIter at 0xc673690>" -- "<GtkTreeIter at 0xc85bda0>"
}
```

And I'm able to render it with `xdot -f dot xdot.dot` , which is the same (or almost the same...) as `_draw_real`

**Comment by andresriancho** [comment]
Will wait until I get new bug reports with the dotcode. Closing.
