### ISSUE TITLE
Too many target URLs

### ISSUE THREAD

**Issue by 1d3df9903ad** [andresriancho/w3af#13143]
## Version Information
```
  Python version: 2.7.10 (default, Sep  7 2015, 13:51:49) [GCC 5.2.0]
  GTK version: 2.24.28
  PyGTK version: 2.24.0
  w3af version:
    w3af - Web Application Attack and Audit Framework
    Version: 1.7.6
    Revision: d7cb405316 - 09 Oct 2015 21:26
    Branch: master
    Local changes: No
    Author: Andres Riancho and the w3af team.
```
## Traceback
```pytb
Traceback (most recent call last):
  File "/home/user/w3af/w3af/core/ui/gui/pluginconfig.py", line 698, in _advanced_target
    {"target": url})
  File "/home/user/w3af/w3af/core/ui/gui/confpanel.py", line 369, in __init__
    ConfigDialog.__init__(self, title, w3af, plugin, overwriter)
  File "/home/user/w3af/w3af/core/ui/gui/confpanel.py", line 306, in __init__
    rvrt_btn, overwriter)
  File "/home/user/w3af/w3af/core/ui/gui/confpanel.py", line 69, in __init__
    opt.set_value(overwriter[opt.get_name()])
  File "/home/user/w3af/w3af/core/data/options/url_list_option.py", line 33, in set_value
    return super(URLListOption, self).set_value(value)
  File "/home/user/w3af/w3af/core/data/options/list_option.py", line 52, in set_value
    self._value = self.validate(value)
  File "/home/user/w3af/w3af/core/data/options/url_list_option.py", line 36, in validate
    parsed_list = super(URLListOption, self).validate(value)
  File "/home/user/w3af/w3af/core/data/options/list_option.py", line 62, in validate
    raise BaseFrameworkException(msg)
BaseFrameworkException: Invalid list format in user configuration: "https://path/foo/accounts/forgotpassword/,https://path/foo/path/foo/,https://path/foo/accounts/add_edit_user/rchmt_user/,https://path/foo/accounts/add_edit_user/,https://path/foo/accounts/users/,https://path/foo/accounts/notifications/edit/,https://path/foo/accounts/notifications/delete/,https://path/foo/accounts/edit_settings/,https://path/foo/accounts/edit_notification_settings/,https://path/foo/accounts/add_tag/,https://path/foo/accounts/set_notification/MP,https://path/foo/accounts/set_notification/DM,https://path/foo/accounts/set_notification/SM,https://path/foo/accounts/set_notification/PS,https://path/foo/accounts/set_notification/AS,https://path/foo/accounts/set_notification/DP,https://path/foo/accounts/set_notification/notices,https://path/foo/accounts/set_notification/case,https://path/foo/accounts/notifications/,https://path/foo/accounts/polling_notifications/,https://path/foo/trademark_library/,https://path/foo/trademark_library/api/v1/product-list.json,https://path/foo/trademark_library/add_trademark,https://path/foo/trademark_library/delete_trademark,https://path/foo/image_library/,https://path/foo/image_library/api/v1/product-list.json,https://path/foo/image_library/upload,https://path/foo/image_library/get_product_list,https://path/foo/image_library/get_collection_list,https://path/foo/path/foo/api/v1/,https://path/foo/path/foo/api/v1/keywords/,https://path/foo/path/foo/api/v1/keywords/0db8f86f-e21c-41cc-a74a-922c58bccac7/,https://path/foo/path/foo/api/v1/whitelists/company/,https://path/foo/path/foo/api/v1/whitelists/path/foo/,https://path/foo/path/foo/api/v1/whitelists/site/,https://path/foo/path/foo/api/v1/whitelists/url/,https://path/foo//,https://path/foo/lock,https://path/foo/dashboard,https://path/foo/whois-search/api/query,https://path/foo/whois-search,https://path/foo/whois-search/filter,https://path/foo/export_modal/,https://path/foo/export_modal/MP,https://path/foo/export_modal/DM,https://path/foo/api/export,https://path/foo/reporting/,https://path/foo/reporting/api/query/,https://path/foo/ajax/notify/notifications.html,https://path/foo/password_change/,https://path/foo/password_change/done/,https://path/foo/path/foo/,https://path/foo/path/foo/whitelists/,https://path/foo/path/foo/whitelists/path/foo/import/,https://path/foo/path/foo/whitelists/path/foo/,https://path/foo/path/foo/keywords/,https://path/foo/path/foo/keywords/import/,https://path/foo/path/foo/templates/,https://path/foo/path/foo/templates/add/,https://path/foo/path/foo/templates/richemont-domain-test/,https://path/foo/path/foo/login/,https://path/foo/path/foo/logout/,https://path/foo/path/foo/password_change/,https://path/foo/path/foo/password_change/done/,https://path/foo/path/foo/jsi18n/,https://path/foo/path/foo/sites/site/,https://path/foo/path/foo/sites/site/add/,https://path/foo/path/foo/sites/site/1/history/,https://path/foo/path/foo/sites/site/1/,https://path/foo/path/foo/legacy/sitesinformation/,https://path/foo/path/foo/legacy/sitesinformation/add/,https://path/foo/path/foo/legacy/sitesinformation/1/history/,https://path/foo/path/foo/legacy/sitesinformation/1/,https://path/foo/path/foo/auth/group/,https://path/foo/path/foo/auth/group/add/,https://path/foo/path/foo/auth/group/1/history/,https://path/foo/path/foo/auth/group/1/,https://path/foo/path/foo/accounts/hubuser/,https://path/foo/path/foo/accounts/hubuser/add/,https://path/foo/path/foo/accounts/hubuser/1/history/,https://path/foo/path/foo/accounts/hubuser/1/,https://path/foo/path/foo/accounts/hubuser/1/password/,https://path/foo/path/foo/accounts/hubuser/,https://path/foo/path/foo/sites/,https://path/foo/path/foo/legacy/,https://path/foo/path/foo/auth/,https://path/foo/path/foo/accounts/,https://path/foo/path/foo/,https://path/foo/path/foo/api/v1/product-list.json,https://path/foo/path/foo/filter,https://path/foo/path/foo/overview,https://path/foo/path/foo/,https://path/foo/path/foo/api/v1/validate-items/,https://path/foo/path/foo/api/v1/flag-irrelevant/,https://path/foo/path/foo/api/v1/flag-enforced/,https://path/foo/path/foo/api/v1/unenforceable/,https://path/foo/path/foo/api/v1/flag-vip/,https://path/foo/path/foo/api/v1/flag-udrp/,https://path/foo/path/foo/api/v1/save-tags/,https://path/foo/marketplace/,https://path/foo/marketplace/api/v1/product-list.json,https://path/foo/marketplace/add_item,https://path/foo/marketplace/filter,https://path/foo/marketplace/overview,https://path/foo/marketplace/api/v1/validate-items/,https://path/foo/marketplace/api/v1/flag-irrelevant/,https://path/foo/marketplace/api/v1/flag-enforced/,https://path/foo/marketplace/api/v1/flag-vip/,https://path/foo/marketplace/api/v1/unenforceable/,https://path/foo/marketplace/api/v1/save-tags/,https://path/foo/mobile-apps/,https://path/foo/mobile-apps/api/v1/product-list.json,https://path/foo/mobile-apps/filter,https://path/foo/mobile-apps/overview,https://path/foo/mobile-apps/api/v1/validate-items/,https://path/foo/mobile-apps/api/v1/flag-irrelevant/,https://path/foo/mobile-apps/api/v1/flag-enforced/,https://path/foo/mobile-apps/api/v1/flag-vip/,https://path/foo/mobile-apps/api/v1/unenforceable/,https://path/foo/mobile-apps/add_item,https://path/foo/mobile-apps/api/v1/save-tags/,https://path/foo/paid-search/,https://path/foo/paid-search/api/v1/product-list.json,https://path/foo/paid-search/add_item,https://path/foo/paid-search/filter,https://path/foo/paid-search/overview,https://path/foo/paid-search/api/v1/validate-items/,https://path/foo/paid-search/api/v1/flag-irrelevant/,https://path/foo/paid-search/api/v1/flag-enforced/,https://path/foo/paid-search/api/v1/flag-vip/,https://path/foo/paid-search/api/v1/unenforceable/,https://path/foo/paid-search/api/v1/save-tags/,https://path/foo/social-media/,https://path/foo/social-media/api/v1/product-list.json,https://path/foo/social-media/add_item,https://path/foo/social-media/filter,https://path/foo/social-media/overview,https://path/foo/social-media/api/v1/validate-items/,https://path/foo/social-media/api/v1/flag-irrelevant/,https://path/foo/social-media/api/v1/flag-enforced/,https://path/foo/social-media/api/v1/flag-vip/,https://path/foo/social-media/api/v1/unenforceable/,https://path/foo/social-media/api/v1/save-tags/,https://path/foo/3d-printing/,https://path/foo/3d-printing/api/v1/product-list.json,https://path/foo/3d-printing/filter,https://path/foo/3d-printing/overview,https://path/foo/path/foo/,https://path/foo/3d-printing/api/v1/validate-items/,https://path/foo/3d-printing/api/v1/flag-irrelevant/,https://path/foo/3d-printing/api/v1/flag-enforced/,https://path/foo/3d-printing/api/v1/flag-vip/,https://path/foo/3d-printing/api/v1/unenforceable/,https://path/foo/3d-printing/api/v1/save-tags/,https://path/foo/smartwatch/,https://path/foo/smartwatch/add_item,https://path/foo/smartwatch/overview,https://path/foo/smartwatch/api/v1/flag-irrelevant/,https://path/foo/smartwatch/api/v1/flag-enforced/,https://path/foo/smartwatch/api/v1/unenforceable/,https://path/foo/clustering/,https://path/foo/clustering/api/v1/product-list.json/all/,https://path/foo/clustering/api/v1/product-list.json/DM/,https://path/foo/clustering/api/v1/product-list.json/MP/,https://path/foo/clustering/overview/filter,https://path/foo/clustering/overview,https://path/foo/clustering/overview/all/,https://path/foo/clustering/overview/DM/,https://path/foo/clustering/overview/MP/,https://path/foo/clustering/heatmap/email/price/all/,https://path/foo/clustering/heatmap/email/price/MP/,https://path/foo/clustering/revisualize/email/num_issues/all/,https://path/foo/clustering/revisualize/email/num_issues/DM/,https://path/foo/clustering/revisualize/email/num_issues/MP/,https://path/foo/notices/,https://path/foo/notices/add_to_basket/DM,https://path/foo/notices/add_to_basket/MP,https://path/foo/notices/add_to_basket/,https://path/foo/notices/notice_from_basket/,https://path/foo/notices/quick_notice/DM,https://path/foo/notices/quick_notice/MP,https://path/foo/notices/quick_notice/,https://path/foo/notices/notice_basket/,https://path/foo/notices/polling_preview/,https://path/foo/notices/send_notice_reply/262/,https://path/foo/notices/send_notice_reply/1/,https://path/foo/notices/send_notice_reply/junk/,https://path/foo/notices/resend_notice/262/,https://path/foo/notices/resend_notice/1/,https://path/foo/notices/resend_notice/junk/,https://path/foo/notices/items/262,https://path/foo/notices/items/1,https://path/foo/notices/api/v1/get-items-info/,https://path/foo/notices/notice_history/,https://path/foo/notices/get_notices_flow/262/,https://path/foo/notices/filter,https://path/foo/notices/overview,https://path/foo/notices/notice_basket/edit/897/,https://path/foo/notices/notice_basket/preview/897/,https://path/foo/notices/notice_basket/delete/,https://path/foo/notices/notice_basket/api/v1/product-list.json,https://path/foo/cases/,https://path/foo/cases/api/v1/product-list.json,https://path/foo/cases/999/comments,https://path/foo/cases/999/history,https://path/foo/cases/999/update,https://path/foo/cases/999/notices,https://path/foo/cases/999/upload,https://path/foo/cases/999/files,https://path/foo/cases/298/comments,https://path/foo/cases/298/history,https://path/foo/cases/298/update,https://path/foo/cases/298/notices,https://path/foo/cases/298/upload,https://path/foo/cases/298/files,https://path/foo/cases/overview,https://path/foo/cases/filter,https://path/foo/cases/manual_case_creation
".

```

**Comment by andresriancho** [comment]
Failed to reproduce
