### ISSUE TITLE
New Bug

### ISSUE THREAD

**Issue by Flora7** [andresriancho/w3af#13600]
I experienced a problem when run w3af_gui. The application shows 'w3af is not responding' after I start a scan. I checked information in terminal and it asks me to report a new bug. Information as follows:
 
root@kali:/usr/share/w3af# ./w3af_gui 
Starting w3af, running on:
  Python version: 2.7.11+ (default, Feb 22 2016, 16:38:42) [GCC 5.3.1 20160220]
  GTK version: 2.24.29
  PyGTK version: 2.24.0
  w3af version:
    w3af - Web Application Attack and Audit Framework
    Version: 1.6.54
    Distribution: Kali Linux
    Author: Andres Riancho and the w3af team.
/usr/share/w3af/w3af/core/ui/gui/reqResViewer.py:182: GtkWarning: gtk_box_pack: assertion 'child->parent == NULL' failed
  self.pack_start(hbox, False, False, padding=5)
Exception in thread GTKDraw:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/share/w3af/w3af/core/ui/gui/scanrun.py", line 419, in _draw_real
    raise ValueError(msg % args)
ValueError: A ValueError exception with message "invalid literal for int() with base 10: '87.5'" was found while trying to render a new dotcode. Please create a new bug report at https://github.com/andresriancho/w3af/issues/new including the following info:

['"<GtkTreeIter at 0x3595140>" [shape=box]',
 '"<GtkTreeIter at 0x3595140>" [label="http://www.webscantest.com"]',
 '"<GtkTreeIter at 0x35a4000>" [label="datastore"]',
 '"<GtkTreeIter at 0x3595140>" -- "<GtkTreeIter at 0x35a4000>"']

*** finished (Connection refused) ***

encoding error : input conversion failed due to input error, bytes 0xE5 0x82 0x99 0xE4
encoding error : input conversion failed due to input error, bytes 0xE5 0x82 0x99 0xE4
encoding error : input conversion failed due to input error, bytes 0xEB 0x93 0xB1 0xEB
encoding error : input conversion failed due to input error, bytes 0xEB 0x93 0xB1 0xEB
I/O error : encoder error
internal buffer error : No error message provided
encoding error : input conversion failed due to input error, bytes 0xB8 0x22 0x20 0x77
encoding error : input conversion failed due to input error, bytes 0xB8 0x22 0x20 0x77

Hope fix soon!

**Comment by Flora7** [comment]
Oops, missing some segments..

['"<GtkTreeIter at 0x3595140>" [shape=box]',
 '"<GtkTreeIter at 0x3595140>" [label="http://www.webscantest.com"]',
 '"<GtkTreeIter at 0x35a4000>" [label="datastore"]',
 '"<GtkTreeIter at 0x3595140>" -- "<GtkTreeIter at 0x35a4000>"']
