### ISSUE TITLE
w3af hangs after getting exception

### ISSUE THREAD

**Issue by knikulov** [andresriancho/w3af#13905]
I've found that w3af hangs after getting exception with message

```
Exception in thread PoolWorkerHandler:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/share/secmon/wvs/w3af/w3af/core/controllers/threads/pool276.py", line 383, in _handle_workers
    pool._maintain_pool()
  File "/usr/local/share/secmon/wvs/w3af/w3af/core/controllers/threads/pool276.py", line 287, in _maintain_pool
    self._repopulate_pool()
  File "/usr/local/share/secmon/wvs/w3af/w3af/core/controllers/threads/pool276.py", line 280, in _repopulate_pool
    w.start()
  File "/usr/lib/python2.7/multiprocessing/dummy/__init__.py", line 73, in start
    self._parent._children[self] = None
AttributeError: 'Thread' object has no attribute '_children'
```
```
$ ps ax | grep w3af
 9845 ?        S      0:00 sh -c /usr/local/share/secmon/wvs/w3af/w3af_console -s /usr/local/share/secmon/wvs/scan_1299.w3af > /dev/null
 9846 ?        Rl   751:38 python /usr/local/share/secmon/wvs/w3af/w3af_console -s /usr/local/share/secmon/wvs/scan_1299.w3af
 9864 ?        Sl     0:00 python /usr/local/share/secmon/wvs/w3af/w3af_console -s /usr/local/share/secmon/wvs/scan_1299.w3af
10078 ?        S      0:00 python /usr/local/share/secmon/wvs/w3af/w3af_console -s /usr/local/share/secmon/wvs/scan_1299.w3af
21620 pts/4    S+     0:00 grep --color=auto w3af
```

Is there a way to fix it?

**Comment by andresriancho** [comment]
No fix that I remember, but `AttributeError: 'Thread' object has no attribute '_children'` sounds like something I've fixed before. Are you sure you're using the latest w3af?

**Comment by andresriancho** [comment]
Also, try searching for that error in this repo to get more info

**Comment by knikulov** [comment]
Yes, I do use the latest w3af version. Ok, I'll try.
