### ISSUE TITLE
gobject crash

### ISSUE THREAD

**Issue by Silur** [andresriancho/w3af#14262]
When I'm starting the `w3af-gui` I get the following error (this is my full output)
```
Traceback (most recent call last):
  File "/usr/share/w3af/w3af_gui", line 110, in <module>
    _main()
  File "/usr/share/w3af/w3af_gui", line 106, in _main
    sys.exit(main())
  File "/usr/share/w3af/w3af_gui", line 100, in main
    from w3af.core.ui.gui.main import main as gui_main
  File "/usr/share/w3af/w3af/core/ui/gui/main.py", line 54, in <module>
    from w3af.core.ui.gui import scanrun, helpers, profiles, compare
  File "/usr/share/w3af/w3af/core/ui/gui/scanrun.py", line 36, in <module>
    from w3af.core.ui.gui.tools.fuzzy_requests import FuzzyRequests
  File "/usr/share/w3af/w3af/core/ui/gui/tools/fuzzy_requests.py", line 30, in <module>
    from w3af.core.ui.gui.clusterGraph import distance_function_selector
  File "/usr/share/w3af/w3af/core/ui/gui/clusterGraph.py", line 25, in <module>
    import xdot
  File "/usr/lib/python2.7/site-packages/xdot.py", line 33, in <module>
    from gi.repository import GLib
  File "/usr/lib/python2.7/site-packages/gi/__init__.py", line 39, in <module>
    raise ImportError(_static_binding_error)
ImportError: When using gi.repository you must not import static modules like "gobject". Please change all occurrences of "import gobject" to "from gi.repository import GObject". See: https://bugzilla.gnome.org/show_bug.cgi?id=709183
```
while w3af CLI works great. I'm on `Linux  4.7.2-1-ARCH  x86_64 `

**Comment by chadaw** [comment]
me too  i have Linux ARCH x86_64
[chabacha@chabacha w3af]$ python2.7 w3af_gui
Traceback (most recent call last):
  File "w3af_gui", line 110, in <module>
    _main()
  File "w3af_gui", line 106, in _main
    sys.exit(main())
  File "w3af_gui", line 100, in main
    from w3af.core.ui.gui.main import main as gui_main
  File "/home/chabacha/w3af/w3af/core/ui/gui/main.py", line 54, in <module>
    from w3af.core.ui.gui import scanrun, helpers, profiles, compare
  File "/home/chabacha/w3af/w3af/core/ui/gui/scanrun.py", line 27, in <module>
    import webkit
ImportError: No module named webkit

**Comment by perigee98** [comment]
similar on ubuntu 17.1, CLI works fine but gui crashes with
./w3af_gui
Gtk-Message: Failed to load module "overlay-scrollbar"
Traceback (most recent call last):
  File "./w3af_gui", line 110, in <module>
    _main()
  File "./w3af_gui", line 106, in _main
    sys.exit(main())
  File "./w3af_gui", line 100, in main
    from w3af.core.ui.gui.main import main as gui_main
  File "/home/jlj/w3af/w3af/core/ui/gui/main.py", line 54, in <module>
    from w3af.core.ui.gui import scanrun, helpers, profiles, compare
  File "/home/jlj/w3af/w3af/core/ui/gui/scanrun.py", line 27, in <module>
    import webkit
ImportError: No module named webkit
