### ISSUE TITLE
error when runing

### ISSUE THREAD

**Issue by amirreza225** [andresriancho/w3af#14353]
amirrezaalibeygi@local ~ $ cd w3af
amirrezaalibeygi@local ~/w3af $ ./w3af_gui
Your python installation needs the following modules to run w3af:
    pybloomfilter esmre phply nltk chardet tblib pdfminer concurrent.futures OpenSSL ndg pyasn1 lxml scapy.config guess_language cluster msgpack ntlm Halberd darts.lib.utils jinja2 vulndb markdown psutil termcolor mitmproxy ruamel.ordereddict Flask yaml tldextract xdot

After installing any missing operating system packages, use pip to install the remaining modules:
    sudo pip install pybloomfiltermmap==0.3.14 esmre==0.3.1 phply==0.9.1 nltk==3.0.1 chardet==2.1.1 tblib==0.2.0 pdfminer==20140328 futures==2.1.5 pyOpenSSL==0.15.1 ndg-httpsclient==0.3.3 pyasn1==0.1.8 lxml==3.4.4 scapy-real==2.2.0-dev guess-language==0.2 cluster==1.1.1b3 msgpack-python==0.4.4 python-ntlm==1.0.1 halberd==0.2.4 darts.util.lru==0.5 Jinja2==2.7.3 vulndb==0.0.19 markdown==2.6.1 psutil==2.2.1 termcolor==1.1.0 mitmproxy==0.13 ruamel.ordereddict==0.4.8 Flask==0.10.1 PyYAML==3.11 tldextract==1.7.2 xdot==0.6

A script with these commands has been created for you at /tmp/w3af_dependency_install.sh
The GTK package requirements are not met, please make sure your system meets these requirements:
    - PyGTK >= 2.12
    - GTK >= 2.12

The required "dot" binary is missing, please install the "graphviz" package in your operating system.
amirrezaalibeygi@local ~/w3af $ ^C
amirrezaalibeygi@local ~/w3af $ /tmp/w3af_dependency_install.sh
Password: 
Collecting pybloomfiltermmap==0.3.14
  Using cached pybloomfiltermmap-0.3.14.tar.gz
Collecting esmre==0.3.1
  Using cached esmre-0.3.1.tar.gz
Collecting phply==0.9.1
Collecting nltk==3.0.1
Collecting chardet==2.1.1
Collecting tblib==0.2.0
  Using cached tblib-0.2.0-py2-none-any.whl
Collecting pdfminer==20140328
Collecting futures==2.1.5
  Using cached futures-2.1.5-py2.py3-none-any.whl
Collecting pyOpenSSL==0.15.1
  Using cached pyOpenSSL-0.15.1-py2.py3-none-any.whl
Collecting ndg-httpsclient==0.3.3
Collecting pyasn1==0.1.8
Collecting lxml==3.4.4
  Using cached lxml-3.4.4.tar.gz
Collecting scapy-real==2.2.0-dev
Collecting guess-language==0.2
Collecting cluster==1.1.1b3
Collecting msgpack-python==0.4.4
Collecting python-ntlm==1.0.1
Collecting halberd==0.2.4
Collecting darts.util.lru==0.5
Collecting Jinja2==2.7.3
Collecting vulndb==0.0.19
Collecting markdown==2.6.1
Collecting psutil==2.2.1
  Using cached psutil-2.2.1.tar.gz
Collecting termcolor==1.1.0
Collecting mitmproxy==0.13
Collecting ruamel.ordereddict==0.4.8
  Using cached ruamel.ordereddict-0.4.8.tar.gz
Collecting Flask==0.10.1
Collecting PyYAML==3.11
Collecting tldextract==1.7.2
Collecting xdot==0.6
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib64/python2.7/site-packages (from esmre==0.3.1)
Collecting ply (from phply==0.9.1)
Collecting six (from tblib==0.2.0)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting cryptography>=0.7 (from pyOpenSSL==0.15.1)
  Using cached cryptography-1.5.tar.gz
Collecting markupsafe (from Jinja2==2.7.3)
Collecting urwid>=1.3 (from mitmproxy==0.13)
Collecting blinker>=1.3 (from mitmproxy==0.13)
Collecting Pillow>=2.3.0 (from mitmproxy==0.13)
  Using cached Pillow-3.3.1-cp27-cp27m-manylinux1_x86_64.whl
Collecting configargparse>=0.9.3 (from mitmproxy==0.13)
Collecting netlib<0.14,>=0.13 (from mitmproxy==0.13)
Collecting html2text>=2015.4.14 (from mitmproxy==0.13)
Collecting tornado>=4.0.2 (from mitmproxy==0.13)
Collecting pyparsing>=1.5.2 (from mitmproxy==0.13)
  Using cached pyparsing-2.1.9-py2.py3-none-any.whl
Collecting pyperclip>=1.5.8 (from mitmproxy==0.13)
Collecting itsdangerous>=0.21 (from Flask==0.10.1)
Collecting Werkzeug>=0.7 (from Flask==0.10.1)
  Using cached Werkzeug-0.11.11-py2.py3-none-any.whl
Collecting idna>=2.0 (from cryptography>=0.7->pyOpenSSL==0.15.1)
  Using cached idna-2.1-py2.py3-none-any.whl
Collecting enum34 (from cryptography>=0.7->pyOpenSSL==0.15.1)
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting ipaddress (from cryptography>=0.7->pyOpenSSL==0.15.1)
  Using cached ipaddress-1.0.17-py2-none-any.whl
Collecting cffi>=1.4.1 (from cryptography>=0.7->pyOpenSSL==0.15.1)
  Using cached cffi-1.8.3-cp27-cp27m-manylinux1_x86_64.whl
Collecting passlib>=1.6.2 (from netlib<0.14,>=0.13->mitmproxy==0.13)
  Using cached passlib-1.6.5-py2.py3-none-any.whl
Collecting certifi (from netlib<0.14,>=0.13->mitmproxy==0.13)
  Using cached certifi-2016.8.31-py2.py3-none-any.whl
Collecting hpack>=1.0.1 (from netlib<0.14,>=0.13->mitmproxy==0.13)
  Using cached hpack-2.3.0-py2.py3-none-any.whl
Collecting singledispatch (from tornado>=4.0.2->mitmproxy==0.13)
  Using cached singledispatch-3.4.0.3-py2.py3-none-any.whl
Collecting backports-abc>=0.4 (from tornado>=4.0.2->mitmproxy==0.13)
  Using cached backports_abc-0.4-py2.py3-none-any.whl
Collecting pycparser (from cffi>=1.4.1->cryptography>=0.7->pyOpenSSL==0.15.1)
Building wheels for collected packages: pybloomfiltermmap, esmre, lxml, psutil, ruamel.ordereddict, cryptography
  Running setup.py bdist_wheel for pybloomfiltermmap ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4eGeTU/pybloomfiltermmap/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpxCV6bvpip-wheel- --python-tag cp27:
  info: Building from C
  running bdist_wheel
  running build
  running build_ext
  building 'pybloomfilter' extension
  creating build
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/src
  x86_64-solus-linux-gcc -pthread -fno-strict-aliasing -mtune=generic -march=x86-64 -g2 -O2 -pipe -fPIC -Wformat -Wformat-security -fomit-frame-pointer -fstack-protector-strong --param ssp-buffer-size=4 -fexceptions -D_FORTIFY_SOURCE=2 -feliminate-unused-debug-types -Wno-error -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c src/mmapbitarray.c -o build/temp.linux-x86_64-2.7/src/mmapbitarray.o
  x86_64-solus-linux-gcc: error trying to exec 'as': execvp: No such file or directory
  src/mmapbitarray.c:1:20: fatal error: stdlib.h: No such file or directory
  compilation terminated.
  error: command 'x86_64-solus-linux-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pybloomfiltermmap
  Running setup.py clean for pybloomfiltermmap
  Running setup.py bdist_wheel for esmre ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4eGeTU/esmre/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpJ4xxQkpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  copying src/esmre.py -> build/lib.linux-x86_64-2.7
  running build_ext
  building 'esm' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/src
  x86_64-solus-linux-gcc -pthread -fno-strict-aliasing -mtune=generic -march=x86-64 -g2 -O2 -pipe -fPIC -Wformat -Wformat-security -fomit-frame-pointer -fstack-protector-strong --param ssp-buffer-size=4 -fexceptions -D_FORTIFY_SOURCE=2 -feliminate-unused-debug-types -Wno-error -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c src/esm.c -o build/temp.linux-x86_64-2.7/src/esm.o
  x86_64-solus-linux-gcc: error trying to exec 'as': execvp: No such file or directory
  In file included from /usr/lib64/gcc/x86_64-solus-linux/5.2.0/include-fixed/syslimits.h:7:0,
                   from /usr/lib64/gcc/x86_64-solus-linux/5.2.0/include-fixed/limits.h:34,
                   from /usr/include/python2.7/Python.h:19,
                   from src/esm.c:19:
  /usr/lib64/gcc/x86_64-solus-linux/5.2.0/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory
  compilation terminated.
  error: command 'x86_64-solus-linux-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for esmre
  Running setup.py clean for esmre
  Running setup.py bdist_wheel for lxml ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4eGeTU/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpiptlUnpip-wheel- --python-tag cp27:
  Building lxml version 3.4.4.
  Building without Cython.
  Using build configuration of libxslt 1.1.28
  Building against libxml2/libxslt in the following directory: /usr/lib
  /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/doctestcompare.py -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/__init__.py -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/_elementpath.py -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/sax.py -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/ElementInclude.py -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/usedoctest.py -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/pyclasslookup.py -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/cssselect.py -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/builder.py -> build/lib.linux-x86_64-2.7/lxml
  creating build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/__init__.py -> build/lib.linux-x86_64-2.7/lxml/includes
  creating build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/diff.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/defs.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/__init__.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/ElementSoup.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/soupparser.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/_setmixin.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/usedoctest.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/formfill.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/clean.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/_diffcommand.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/html5parser.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/builder.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/_html5builder.py -> build/lib.linux-x86_64-2.7/lxml/html
  creating build/lib.linux-x86_64-2.7/lxml/isoschematron
  copying src/lxml/isoschematron/__init__.py -> build/lib.linux-x86_64-2.7/lxml/isoschematron
  copying src/lxml/lxml.etree.h -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/lxml.etree_api.h -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/includes/xinclude.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/uri.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/xmlschema.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/htmlparser.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/xslt.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/tree.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/xmlparser.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/xpath.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/schematron.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/config.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/dtdvalid.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/c14n.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/etreepublic.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/xmlerror.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/relaxng.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/etree_defs.h -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/lxml-version.h -> build/lib.linux-x86_64-2.7/lxml/includes
  creating build/lib.linux-x86_64-2.7/lxml/isoschematron/resources
  creating build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/rng
  copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/rng
  creating build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl
  copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl
  copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl
  creating build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  running build_ext
  building 'lxml.etree' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/src
  creating build/temp.linux-x86_64-2.7/src/lxml
  x86_64-solus-linux-gcc -pthread -fno-strict-aliasing -mtune=generic -march=x86-64 -g2 -O2 -pipe -fPIC -Wformat -Wformat-security -fomit-frame-pointer -fstack-protector-strong --param ssp-buffer-size=4 -fexceptions -D_FORTIFY_SOURCE=2 -feliminate-unused-debug-types -Wno-error -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/include/libxml2 -I/tmp/pip-build-4eGeTU/lxml/src/lxml/includes -I/usr/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -w
  x86_64-solus-linux-gcc: error trying to exec 'as': execvp: No such file or directory
  In file included from /usr/lib64/gcc/x86_64-solus-linux/5.2.0/include-fixed/syslimits.h:7:0,
                   from /usr/lib64/gcc/x86_64-solus-linux/5.2.0/include-fixed/limits.h:34,
                   from /usr/include/python2.7/Python.h:19,
                   from src/lxml/lxml.etree.c:16:
  /usr/lib64/gcc/x86_64-solus-linux/5.2.0/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory
  compilation terminated.
  error: command 'x86_64-solus-linux-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for lxml
  Running setup.py clean for lxml
  Running setup.py bdist_wheel for psutil ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4eGeTU/psutil/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpEd9GABpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/psutil
  copying psutil/_pswindows.py -> build/lib.linux-x86_64-2.7/psutil
  copying psutil/_pslinux.py -> build/lib.linux-x86_64-2.7/psutil
  copying psutil/_psposix.py -> build/lib.linux-x86_64-2.7/psutil
  copying psutil/_psbsd.py -> build/lib.linux-x86_64-2.7/psutil
  copying psutil/_pssunos.py -> build/lib.linux-x86_64-2.7/psutil
  copying psutil/_psosx.py -> build/lib.linux-x86_64-2.7/psutil
  copying psutil/_common.py -> build/lib.linux-x86_64-2.7/psutil
  copying psutil/_compat.py -> build/lib.linux-x86_64-2.7/psutil
  copying psutil/__init__.py -> build/lib.linux-x86_64-2.7/psutil
  running build_ext
  building '_psutil_linux' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/psutil
  x86_64-solus-linux-gcc -pthread -fno-strict-aliasing -mtune=generic -march=x86-64 -g2 -O2 -pipe -fPIC -Wformat -Wformat-security -fomit-frame-pointer -fstack-protector-strong --param ssp-buffer-size=4 -fexceptions -D_FORTIFY_SOURCE=2 -feliminate-unused-debug-types -Wno-error -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DPSUTIL_VERSION=221 -I/usr/include/python2.7 -c psutil/_psutil_linux.c -o build/temp.linux-x86_64-2.7/psutil/_psutil_linux.o
  x86_64-solus-linux-gcc: error trying to exec 'as': execvp: No such file or directory
  In file included from /usr/lib64/gcc/x86_64-solus-linux/5.2.0/include-fixed/syslimits.h:7:0,
                   from /usr/lib64/gcc/x86_64-solus-linux/5.2.0/include-fixed/limits.h:34,
                   from /usr/include/python2.7/Python.h:19,
                   from psutil/_psutil_linux.c:12:
  /usr/lib64/gcc/x86_64-solus-linux/5.2.0/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory
  compilation terminated.
  error: command 'x86_64-solus-linux-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for psutil
  Running setup.py clean for psutil
  Running setup.py bdist_wheel for ruamel.ordereddict ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4eGeTU/ruamel.ordereddict/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpcgudv3pip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/ruamel
  creating build/lib.linux-x86_64-2.7/ruamel/ordereddict
  copying ./__init__.py -> build/lib.linux-x86_64-2.7/ruamel/ordereddict
  copying ./setup.py -> build/lib.linux-x86_64-2.7/ruamel/ordereddict
  running build_ext
  building '_ordereddict' extension
  creating build/temp.linux-x86_64-2.7
  x86_64-solus-linux-gcc -pthread -fno-strict-aliasing -mtune=generic -march=x86-64 -g2 -O2 -pipe -fPIC -Wformat -Wformat-security -fomit-frame-pointer -fstack-protector-strong --param ssp-buffer-size=4 -fexceptions -D_FORTIFY_SOURCE=2 -feliminate-unused-debug-types -Wno-error -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c ordereddict.c -o build/temp.linux-x86_64-2.7/ordereddict.o
  x86_64-solus-linux-gcc: error trying to exec 'as': execvp: No such file or directory
  In file included from /usr/lib64/gcc/x86_64-solus-linux/5.2.0/include-fixed/syslimits.h:7:0,
                   from /usr/lib64/gcc/x86_64-solus-linux/5.2.0/include-fixed/limits.h:34,
                   from /usr/include/python2.7/Python.h:19,
                   from ordereddict.c:22:
  /usr/lib64/gcc/x86_64-solus-linux/5.2.0/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory
  compilation terminated.
  error: command 'x86_64-solus-linux-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for ruamel.ordereddict
  Running setup.py clean for ruamel.ordereddict
  Running setup.py bdist_wheel for cryptography ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4eGeTU/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpkgDCcdpip-wheel- --python-tag cp27:
  x86_64-solus-linux-gcc: error trying to exec 'as': execvp: No such file or directory
  _configtest.c:1:1: fatal error: error closing -: Broken pipe
   __thread int some_threadlocal_variable_42;
   ^
  compilation terminated.
  x86_64-solus-linux-gcc: error trying to exec 'as': execvp: No such file or directory
  _configtest.c:1:1: fatal error: error closing -: Broken pipe
   int some_regular_variable_42;
   ^
  compilation terminated.
  
      No working compiler found, or bogus compiler options
      passed to the compiler from Python's distutils module.
      See the error messages above.
      (If they are about -mno-fused-madd and you are on OS/X 10.8,
      see http://stackoverflow.com/questions/22313407/ .)
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-4eGeTU/cryptography/setup.py", line 334, in <module>
      **keywords_with_side_effects(sys.argv)
    File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
      _setup_distribution = dist = klass(attrs)
    File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 315, in __init__
      self.fetch_build_eggs(attrs['setup_requires'])
    File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 361, in fetch_build_eggs
      replace_conflicting=True,
    File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 851, in resolve
      dist = best[req.key] = env.best_match(req, ws, installer)
    File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1123, in best_match
      return self.obtain(req, installer)
    File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1135, in obtain
      return installer(requirement)
    File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 429, in fetch_build_egg
      return cmd.easy_install(req)
    File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 665, in easy_install
      return self.install_item(spec, dist.location, tmpdir, deps)
    File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 695, in install_item
      dists = self.install_eggs(spec, download, tmpdir)
    File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 876, in install_eggs
      return self.build_and_install(setup_script, setup_base)
    File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1115, in build_and_install
      self.run_setup(setup_script, setup_base, args)
    File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1103, in run_setup
      raise DistutilsError("Setup script exited with %s" % (v.args[0],))
  distutils.errors.DistutilsError: Setup script exited with 1
  
  ----------------------------------------
  Failed building wheel for cryptography
  Running setup.py clean for cryptography
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4eGeTU/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" clean --all:
  x86_64-solus-linux-gcc: error trying to exec 'as': execvp: No such file or directory
  _configtest.c:1:1: fatal error: error closing -: Broken pipe
   __thread int some_threadlocal_variable_42;
   ^
  compilation terminated.
  x86_64-solus-linux-gcc: error trying to exec 'as': execvp: No such file or directory
  _configtest.c:1:1: fatal error: error closing -: Broken pipe
   int some_regular_variable_42;
   ^
  compilation terminated.
  
      No working compiler found, or bogus compiler options
      passed to the compiler from Python's distutils module.
      See the error messages above.
      (If they are about -mno-fused-madd and you are on OS/X 10.8,
      see http://stackoverflow.com/questions/22313407/ .)
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-4eGeTU/cryptography/setup.py", line 334, in <module>
      **keywords_with_side_effects(sys.argv)
    File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
      _setup_distribution = dist = klass(attrs)
    File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 315, in __init__
      self.fetch_build_eggs(attrs['setup_requires'])
    File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 361, in fetch_build_eggs
      replace_conflicting=True,
    File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 851, in resolve
      dist = best[req.key] = env.best_match(req, ws, installer)
    File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1123, in best_match
      return self.obtain(req, installer)
    File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1135, in obtain
      return installer(requirement)
    File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 429, in fetch_build_egg
      return cmd.easy_install(req)
    File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 665, in easy_install
      return self.install_item(spec, dist.location, tmpdir, deps)
    File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 695, in install_item
      dists = self.install_eggs(spec, download, tmpdir)
    File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 876, in install_eggs
      return self.build_and_install(setup_script, setup_base)
    File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1115, in build_and_install
      self.run_setup(setup_script, setup_base, args)
    File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1103, in run_setup
      raise DistutilsError("Setup script exited with %s" % (v.args[0],))
  distutils.errors.DistutilsError: Setup script exited with 1
  
  ----------------------------------------
  Failed cleaning build dir for cryptography
Failed to build pybloomfiltermmap esmre lxml psutil ruamel.ordereddict cryptography
Installing collected packages: pybloomfiltermmap, esmre, ply, phply, nltk, chardet, six, tblib, pdfminer, futures, idna, pyasn1, enum34, ipaddress, pycparser, cffi, cryptography, pyOpenSSL, ndg-httpsclient, lxml, scapy-real, guess-language, cluster, msgpack-python, python-ntlm, halberd, darts.util.lru, markupsafe, Jinja2, vulndb, markdown, psutil, termcolor, urwid, blinker, Pillow, configargparse, passlib, certifi, hpack, netlib, html2text, singledispatch, backports-abc, tornado, pyparsing, pyperclip, mitmproxy, ruamel.ordereddict, itsdangerous, Werkzeug, Flask, PyYAML, tldextract, xdot
  Running setup.py install for pybloomfiltermmap ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4eGeTU/pybloomfiltermmap/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-hTHbIp-record/install-record.txt --single-version-externally-managed --compile:
    info: Building from C
    running install
    running build
    running build_ext
    building 'pybloomfilter' extension
    creating build
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/src
    x86_64-solus-linux-gcc -pthread -fno-strict-aliasing -mtune=generic -march=x86-64 -g2 -O2 -pipe -fPIC -Wformat -Wformat-security -fomit-frame-pointer -fstack-protector-strong --param ssp-buffer-size=4 -fexceptions -D_FORTIFY_SOURCE=2 -feliminate-unused-debug-types -Wno-error -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c src/mmapbitarray.c -o build/temp.linux-x86_64-2.7/src/mmapbitarray.o
    x86_64-solus-linux-gcc: error trying to exec 'as': execvp: No such file or directory
    src/mmapbitarray.c:1:20: fatal error: stdlib.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-solus-linux-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4eGeTU/pybloomfiltermmap/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-hTHbIp-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-4eGeTU/pybloomfiltermmap/

**Comment by amirreza225** [comment]
I'm installing this software on solus OS
