### ISSUE TITLE
ASCII codec error

### ISSUE THREAD

**Issue by digitalhuman** [andresriancho/w3af#14936]
I keep getting these errors. After 5 times this error occurs w3af exits and doesn't write output. I saw in 1.62 this issue was also rased but as far as i can tell it's still not fixed completely.

'ascii' codec can't encode character u'\u2026' in position 767: ordinal not in range(128)

Cheers,

Victor

**Comment by digitalhuman** [comment]
I was trying to figure that out as well. It happens when;

-archive_dot_org
-bing_spider
-dot_listing
-find_backdoors
-ghdb
-phpinfo
-pykto
-user_dir
-web_spider

are turned on. It's easy to fix though but you have to set your Linux environment to en_US-UTF8 though. I can imagine some people don't want to change that because of other stuff that is running. Especially when non US peepz. ;)

**Comment by andresriancho** [comment]
Do you have a target site where I can reproduce this issue?

**Comment by hmaki** [comment]
I encoutered this problem too.

```
An exception was raised while trying to write to the output file "output.txt", 
error: "'ascii' codec can't encode character u'\xc4' in position 17610: ordinal 
not in range(128)". Disabling output to this file.
```

I added a simple print (msg) line into text_file in beginning of the exception handler in _write_to_file function, and the next run gave this Python traceback.

```
Exception in thread ConsoleScanThread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/heikki/w3af/w3af/core/ui/console/rootMenu.py", line 143, in _real_start
    self._w3af.start()
  File "/home/heikki/w3af/w3af/core/controllers/w3afCore.py", line 199, in start
    self.plugins.get_all_plugin_options())
  File "/home/heikki/w3af/w3af/core/controllers/output_manager/manager.py", line 53, in od_wrapper
    return func(*args, **kwds)
  File "/home/heikki/w3af/w3af/core/controllers/output_manager/manager.py", line 244, in log_enabled_plugins
    o_plugin.log_enabled_plugins(enabled_plugins, plugins_options)
  File "/home/heikki/w3af/w3af/plugins/output/text_file.py", line 234, in log_enabled_plugins
    self._write_to_file(timestamp + to_print)
  File "/home/heikki/w3af/w3af/plugins/output/text_file.py", line 112, in _write_to_file
    print (msg)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xc4' in position 17610: ordinal not in range(128)
```

**Comment by hmaki** [comment]
Not sure if this is the right fix, but it worked for me. I changed the line

```
try:
            self._file.write(self._clean_string(msg))
```
in w3af/plugins/output/text_file.py into

```
try:
            self._file.write(self._clean_string(msg).encode('utf-8'))
```
