### ISSUE TITLE
w3af openssl bug?

### ISSUE THREAD

**Issue by hclzmao** [andresriancho/w3af#15220]
kali 2
w3af need  openssl==0.15.1

`emaining modules:
    sudo pip install pyOpenSSL==0.15.1`

when I do it  then

` ./w3af_console 

Traceback (most recent call last):
  File "./w3af_console", line 15, in <module>
    from w3af.core.ui.console.console_ui import ConsoleUI
  File "/root/w3af/w3af/core/ui/console/console_ui.py", line 35, in <module>
    from w3af.core.ui.console.rootMenu import rootMenu
  File "/root/w3af/w3af/core/ui/console/rootMenu.py", line 32, in <module>
    from w3af.core.ui.console.plugins import pluginsMenu
  File "/root/w3af/w3af/core/ui/console/plugins.py", line 29, in <module>
    from w3af.core.ui.console.config import ConfigMenu
  File "/root/w3af/w3af/core/ui/console/config.py", line 27, in <module>
    from w3af.core.controllers.plugins.plugin import Plugin
  File "/root/w3af/w3af/core/controllers/plugins/plugin.py", line 37, in <module>
    from w3af.core.data.url.helpers import new_no_content_resp
  File "/root/w3af/w3af/core/data/url/helpers.py", line 28, in <module>
    import OpenSSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
`

**Comment by andresriancho** [comment]
Solved with the latest merge from develop to master I made today. In order to fix this issue you need to go to your w3af directory and run `git pull`, then try to run the `w3af_console` again.
