### ISSUE TITLE
ImportError: No module named webkit

### ISSUE THREAD

**Issue by lacroutelacroute** [andresriancho/w3af#15293]
after new install from scratch on my kali laptop
I encounter an error when launching the GUI

/opt/w3afmaster/w3af$ sudo ./w3af_gui 
[sudo] Mot de passe de fakessh : 
Traceback (most recent call last):
  File "./w3af_gui", line 110, in <module>
    _main()
  File "./w3af_gui", line 106, in _main
    sys.exit(main())
  File "./w3af_gui", line 100, in main
    from w3af.core.ui.gui.main import main as gui_main
  File "/opt/w3afmaster/w3af/w3af/core/ui/gui/main.py", line 54, in <module>
    from w3af.core.ui.gui import scanrun, helpers, profiles, compare
  File "/opt/w3afmaster/w3af/w3af/core/ui/gui/scanrun.py", line 27, in <module>
    import webkit
ImportError: No module named webkit

w3af is missing to kali depot
w3af_console work

**Comment by lacroutelacroute** [comment]
i have two version installed on my box
master and develop 
the result is the same error

**Comment by xperblueray** [comment]
Also run into the same problem : No module named webkit ,when I install the w3af_gui

**Comment by lacroutelacroute** [comment]
From what I know python-webkit is no longer maintained
for use w3af_gui
Use an outdated deb distribution

**Comment by xperblueray** [comment]
@lacroutelacroute Thx a lot,I've resolved the problem last

**Comment by crystalstorm** [comment]
for those of you having the same problem but on OSX, I fixed it with macports:
`sudo port install py27-webkitgtk`

**Comment by n1rv4n4** [comment]
`sudo apt install python-webkit`

Solves the problem.

**Comment by juliustravy** [comment]
> From what I know python-webkit is no longer maintained for use w3af_gui Use an outdated deb distribution Le Mon, 05 Jun 2017 05:22:34 -0700, xperblueray <notifications@github.com> a écrit :
> […](#)
> Also run into the same problem : No module named webkit ,when I install the w3af_gui

Could you please substantiate on this... How do I Use an outdated deb and where can I get one please? Thanks.

**Comment by jackbritchford** [comment]
Hi, no longer maintained on kali-rolling. Can't install it using a Debian dpkg because all of the dependencies are also no longer maintained on kali-rolling.

Any advice?
