### ISSUE TITLE
new install problem

### ISSUE THREAD

**Issue by lacroutelacroute** [andresriancho/w3af#15298]
after reinstall my core python package and my kali desktop
w3af is removed to depot

i encouter fatal ssl error
fakessh@fakessh:/opt/w3afdev/w3af$ sudo ./w3af_gui 
Something went wrong, w3af failed to start the output manager.
Exception: "There was an error while importing w3af.plugins.output.console: "'module' object has no attribute 'SSL_ST_INIT'"."
fakessh@fakessh:/opt/w3afdev/w3af$ sudo ./w3af_console 
Traceback (most recent call last):
  File "./w3af_console", line 15, in <module>
    from w3af.core.ui.console.console_ui import ConsoleUI
  File "/opt/w3afdev/w3af/w3af/core/ui/console/console_ui.py", line 35, in <module>
    from w3af.core.ui.console.rootMenu import rootMenu
  File "/opt/w3afdev/w3af/w3af/core/ui/console/rootMenu.py", line 32, in <module>
    from w3af.core.ui.console.plugins import pluginsMenu
  File "/opt/w3afdev/w3af/w3af/core/ui/console/plugins.py", line 29, in <module>
    from w3af.core.ui.console.config import ConfigMenu
  File "/opt/w3afdev/w3af/w3af/core/ui/console/config.py", line 27, in <module>
    from w3af.core.controllers.plugins.plugin import Plugin
  File "/opt/w3afdev/w3af/w3af/core/controllers/plugins/plugin.py", line 37, in <module>
    from w3af.core.data.url.helpers import new_no_content_resp
  File "/opt/w3afdev/w3af/w3af/core/data/url/helpers.py", line 28, in <module>
    import OpenSSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
fakessh@fakessh:/opt/w3afdev/w3af$ 

git master and develop propose same error
with different pip package

**Comment by alldayi420** [comment]
any luck?

**Comment by andresriancho** [comment]
Solved with the latest merge from develop to master I made today. In order to fix this issue you need to go to your w3af directory and run `git pull`, then try to run the `w3af_console` again.
