### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by lingyu12138** [andresriancho/w3af#15593]
root@kali:/opt/w3af# ./w3af_gui 
Traceback (most recent call last):
  File "./w3af_gui", line 12, in <module>
    from w3af.core.ui.gui.dependency_check.dependency_check import dependency_check
  File "/opt/w3af/w3af/core/ui/gui/dependency_check/dependency_check.py", line 25, in <module>
    from w3af.core.controllers.dependency_check.dependency_check import dependency_check as mdep_check
  File "/opt/w3af/w3af/core/controllers/dependency_check/dependency_check.py", line 31, in <module>
    import pip
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 21, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
  File "/usr/lib/python2.7/dist-packages/pip/_vendor/__init__.py", line 64, in <module>
    vendored("cachecontrol")
  File "/usr/lib/python2.7/dist-packages/pip/_vendor/__init__.py", line 36, in vendored
    __import__(modulename, globals(), locals(), level=0)
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/__init__.py", line 9, in <module>
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/wrapper.py", line 1, in <module>
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 4, in <module>
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/__init__.py", line 52, in <module>
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/packages/__init__.py", line 59, in <module>
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/packages/__init__.py", line 32, in vendored
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/contrib/pyopenssl.py", line 47, in <module>
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

**Comment by derboblan** [comment]
like #15465, #15523, #15527, #15633 and #15636: try #14966 and maybe comment `PIPDependency('pyasn1', 'pyasn1', '0.1.9'),` in `w3af/core/controllers/dependency_check/requirements.py`

**Comment by GhostSpotter** [comment]
Hi
sorry for my bad English..i am from Germany...i found a Solution to install w3af under Kali Rolling 2017.
u have to do this steps..i use the new Kali Version...

install w3af in kali linux (rolling) 2017
Kali Linux has been installed some packages for fill the requirements of w3af.

openssl ==> 16.2.0
lxml ==> 3.7.1

Preparing install:
sudo apt install -y python-pybloomfiltermmap

pybloomfiltermmap ==> 0.3.15

update the version in requiremenets.py
vim ~/w3af/w3af/core/controllers/dependency_check/requirements.py

PIPDependency('pybloomfilter', 'pybloomfiltermmap', '0.3.15'),
PIPDependency('OpenSSL', 'pyOpenSSL', '16.2.0'),
PIPDependency('lxml', 'lxml', '3.7.1'),

update mac version dependency_check
vim ~/w3af/w3af/core/controllers/dependency_check/platforms/mac.py

MAC_CORE_PIP_PACKAGES.remove(PIPDependency('pybloomfilter', 'pybloomfiltermmap', '0.3.15')

Execute command for generating installation scripts
And the script will be generated to /tmp/w3af_dependency_install.sh

./w3af_console -- work

**Comment by andresriancho** [comment]
Solved with the latest merge from develop to master I made today. In order to fix this issue you need to go to your w3af directory and run `git pull`, then try to run the `w3af_console` again.
