### ISSUE TITLE
Problem!! , ImportError: No module named webkit

### ISSUE THREAD

**Issue by ProDevCC** [andresriancho/w3af#15690]
root@MinePM:~/w3af# ./w3af_gui
Traceback (most recent call last):
  File "./w3af_gui", line 110, in <module>
    _main()
  File "./w3af_gui", line 106, in _main
    sys.exit(main())
  File "./w3af_gui", line 100, in main
    from w3af.core.ui.gui.main import main as gui_main
  File "/root/w3af/w3af/core/ui/gui/main.py", line 54, in <module>
    from w3af.core.ui.gui import scanrun, helpers, profiles, compare
  File "/root/w3af/w3af/core/ui/gui/scanrun.py", line 27, in <module>
    import webkit
ImportError: No module named webkit

**Comment by ProDevCC** [comment]
How do I solve the problem?
Thanks ..

**Comment by n1rv4n4** [comment]
`sudo apt install python-webkit`

Solves the problem.

**Comment by yuleitest** [comment]
root@kali:~/w3af# ./w3af_gui 
Traceback (most recent call last):
  File "./w3af_gui", line 110, in <module>
    _main()
  File "./w3af_gui", line 106, in _main
    sys.exit(main())
  File "./w3af_gui", line 100, in main
    from w3af.core.ui.gui.main import main as gui_main
  File "/root/w3af/w3af/core/ui/gui/main.py", line 54, in <module>
    from w3af.core.ui.gui import scanrun, helpers, profiles, compare
  File "/root/w3af/w3af/core/ui/gui/scanrun.py", line 27, in <module>
    import webkit
ImportError: No module named webkit
root@kali:~/w3af# apt install python-webkit
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python-webkit
root@kali:~/w3af#

**Comment by imidoriya** [comment]
Not able to get webkit on macOS either..
