### ISSUE TITLE
REST API service did not return JSON

### ISSUE THREAD

**Issue by jangelesg** [andresriancho/w3af#15889]
REST API service did not return JSON, if this issue persists please create an issue in the w3af framework repository at https://github.com/andresriancho/w3af/issues/new. The response body starts with: "<!DOCTYPE HTML PUBLI

**Comment by andresriancho** [comment]
Thanks for the bug report!

How may I reproduce this bug?

**Comment by jangelesg** [comment]
I'm using your API in order to scan but when i try to scan serveral times one by one 

the API Service triggered this traceback

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/Documents/WebSECt00ls/w3af/w3af/core/ui/api/utils/auth.py", line 51, in decorated
    return f(*args, **kwargs)
  File "/home/user/Documents/WebSECt00ls/w3af/w3af/core/ui/api/resources/scans.py", line 88, in start_scan
    if not len(target_urls):
TypeError: object of type 'NoneType' has no len()

**Comment by andresriancho** [comment]
It seems that in some HTTP requests to the REST API you're not specifying a target URL
