### ISSUE TITLE
W3af is not getting install 

### ISSUE THREAD

**Issue by iitmcollegeprash** [andresriancho/w3af#15897]
HI Team 

I am using Kali and tried to install W3af with recommended method but it is not getting install . i have done all the things presents on Google .

Whenever i run -
**root@kali:~/w3af# ./w3af_console** 
Below is output 
Your python installation needs the following modules to run w3af:
    pybloomfilter OpenSSL lxml scapy.config guess_language cluster msgpack ntlm Halberd darts.lib.utils jinja2 vulndb markdown psutil mitmproxy ruamel.ordereddict Flask tldextract

After installing any missing operating system packages, use pip to install the remaining modules:
    sudo pip install pybloomfiltermmap==0.3.15 pyOpenSSL==16.2.0 lxml==3.7.1 scapy-real==2.2.0-dev guess-language==0.2 cluster==1.1.1b3 msgpack-python==0.4.4 python-ntlm==1.0.1 halberd==0.2.4 darts.util.lru==0.5 Jinja2==2.7.3 vulndb==0.0.19 markdown==2.6.1 psutil==2.2.1 mitmproxy==0.13 ruamel.ordereddict==0.4.8 Flask==0.10.1 tldextract==1.7.2

A script with these commands has been created for you at /tmp/w3af_dependency_install.sh

Now when i run /w3af_dependency_install.sh got below error -

**root@kali:/tmp# ./w3af_dependency_install.sh** 
Collecting pybloomfiltermmap==0.3.15
  Downloading pybloomfiltermmap-0.3.15.tar.gz (448kB)
    100% |████████████████████████████████| 450kB 22kB/s 
Collecting pyOpenSSL==16.2.0
  Downloading pyOpenSSL-16.2.0-py2.py3-none-any.whl (43kB)
    100% |████████████████████████████████| 51kB 13kB/s 
Collecting lxml==3.7.1
  Downloading lxml-3.7.1-cp27-cp27mu-manylinux1_x86_64.whl (6.7MB)
    69% |██████████████████████▍         | 4.7MB 15kB/s eta 0:02:10Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 882, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 603, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/usr/lib/python2.7/dist-packages/pip/utils/hashes.py", line 46, in check_against_chunks
    for chunk in chunks:
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 571, in written_chunks
    for chunk in chunks:
  File "/usr/lib/python2.7/dist-packages/pip/utils/ui.py", line 139, in iter
    for x in it:
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 560, in resp_read
    decode_content=False):
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/response.py", line 432, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/response.py", line 397, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/response.py", line 303, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
ReadTimeoutError: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out.

Also i did this 
I edited the file in ~/w3af/w3af/core/controllers/dependency_check/requirements.py and changed
PIPDependency('OpenSSL', 'pyOpenSSL', '0.15.1'), to
PIPDependency('OpenSSL', 'pyOpenSSL', '16.2.0')

But issue remain same .
Output of require command is below - 

**root@kali:~/Desktop# /etc/lsb-release**
DISSTRIB_ID=Kali
DISTRIB_RELEASE=kali-rolling
DISTRIB_CODENAME=kali-rolling
DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"

**root@kali:~/Desktop# python --version**
Python 2.7.13

**root@kali:/tmp# ls**
pip-PZY0nE-unpack
ssh-wPL5KEnii6G6
systemd-private-be32d310d51846bcb8765bf838d10771-colord.service-OIfGfh
systemd-private-be32d310d51846bcb8765bf838d10771-rtkit-daemon.service-itnnBh
tracker-extract-files.0
w3af_dependency_install.sh

**root@kali:/tmp# pip freeze**
Warning: cannot find svn location for chirp===daily-20170124
adns-python==1.2.1
AdvancedHTTPServer==2.0.10
alembic==0.8.8.dev0
anyjson==0.3.3
argcomplete==1.8.1
argh==0.26.2
attrs==17.2.0
backports-abc==0.5
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.5.0.1
basemap==1.0.7
BBQSQL==1.0
BeautifulSoup==3.2.1
beautifulsoup4==4.6.0
BlindElephant==1.0
blinker==1.3
boltons==16.4.1
brotlipy==0.6.0
capstone==3.0.4
certifi==2016.2.28
chardet==2.1.1
Cheetah==2.4.4
## FIXME: could not find svn URL in dependency_links for this package:
chirp===daily-20170124
chrome-gnome-shell==0.0.0
click==6.6
colorama==0.3.7
ConfigArgParse==0.11.0
configobj==5.0.6
configparser==3.3.0.post2
constantly==15.1.0
construct==2.5.2
couchdbkit==0.6.5
cryptography==1.7.1
cssutils==1.0
cycler==0.10.0
dap==2.2.6.7
decorator==4.0.11
dicttoxml==1.7.4
dissy==9
distorm3==3.3.4
dnspython==1.15.0
docutils==0.13.1
easygui==0.96
Elixir==0.7.1
enum34==1.1.6
esmre==0.3.1
feedparser==5.1.3
Flask==0.12.2
FormEncode==1.3.0
functools32==3.2.3.post2
fuse-python==0.2.1
future==0.15.2
futures==2.1.5
GDAL==2.1.2
GeoIP==1.3.2
geoip2==2.5.0
geojson==1.3.4
gevent==1.1.2
gitdb2==2.0.2
GitPython==2.1.3
greenlet==0.4.11
h2==2.5.2
hpack==2.3.0
html2text==2016.9.19
html5lib==0.999999999
http-parser==0.8.3
httplib2==0.9.2
httpretty==0.8.14
hyperframe==4.0.1
icalendar==3.8
idna==2.2
impacket==0.9.15
incremental==16.10.1
ipaddress==1.0.17
IPy==0.83
ipython==5.1.0
ipython-genutils==0.1.0
itsdangerous==0.24
jdcal==1.0
Jinja2==2.9.6
jsbeautifier==1.6.4
jsonpickle==0.9.3
jsonrpclib==0.1.3
keepnote==0.7.8
keyring==10.4.0
keyrings.alt==2.2
killerbee==1.0
lxml==3.8.0
M2Crypto==0.24.0
Mako==1.0.6
MarkupSafe==1.0
matplotlib==2.0.0
maxminddb==1.2.3
mechanize==0.2.5
mercurial==4.0
metaconfig==0.1.4a1
mitmproxy==0.18.2
mockito==0.5.2
msgpack-python==0.4.8
mysqlclient==1.3.7
nassl==0.12
ndg-httpsclient==0.3.3
netaddr==0.7.18
NfSpy==1.0
nltk==3.0.1
numpy==1.12.1
olefile==0.44
openpyxl==2.3.0
PAM==0.4.2
paramiko==2.0.0
passlib==1.7.1
Paste==2.0.3
PasteDeploy==1.5.2
PasteScript==1.7.5
pathlib2==2.1.0
pathtools==0.1.2
pcapy==0.10.8
pdfminer==20140328
pefile==2017.5.26
pexpect==4.2.1
phply==0.9.1
pickleshare==0.7.4
Pillow==4.1.1
pluginbase==0.4
ply==3.10
prettytable==0.7.2
prompt-toolkit==1.0.14
psycopg2==2.7.1
ptyprocess==0.5.1
py==1.4.34
pyasn1==0.1.9
pyasn1-modules==0.0.7
pybloomfiltermmap==0.3.14
pyClamd==0.3.15
pycrypto==2.6.1
pycurl==7.43.0
pydns==2.3.6
pyenchant==1.6.7
PyGithub==1.21.0
Pygments==2.2.0
pygobject==3.22.0
pygtkspellcheck==4.0.5
pyinotify==0.9.6
pylibemu==0.3.3
pymongo==3.4.0
pymssql==2.1.3
pyOpenSSL==0.15.1
pyotp==2.2.1
pyparsing==2.1.10
PyPDF2==1.26.0
pyperclip==1.5.27
pyrit==0.5.1
pyscard==1.9.5
pyserial==3.3
pysnmp==4.3.2
pysnmp-apps==0.3.2
pysnmp-mibs==0.1.3
PySocks==1.6.5
pyspatialite==3.0.1
pysqlite==2.7.0
pytest==3.0.6
python-dateutil==2.5.3
python-editor==0.4
python-Levenshtein==0.12.0
python-openid==2.2.5
python-pam==1.8.2
pytz==2017.2
pyusb==1.0.0b2
PyX==0.12.1
pyxdg==0.25
PyYAML==3.12
qrcode==5.3
requests==2.12.4
restkit==4.2.2
rfidiot==1.0
roman==2.0.0
scapy===unknown.version
scgi==1.13
SecretStorage==2.3.1
service-identity==16.0.0
Shapely==1.5.17
simplegeneric==0.8.1
simplejson==3.11.1
singledispatch==3.4.0.3
six==1.10.0
slowaes==0.1a1
smmap2==2.0.3
smoke-zephyr==1.0.2
socketpool==0.5.3
SQLAlchemy==1.1.11
subprocess32==3.2.7
tblib==0.2.0
tcpwatch==1.3.1
Tempita==0.5.2
termcolor==1.1.0
tornado==4.5.1
traitlets==4.3.1
Twisted==16.6.0
typing==3.5.2.2
tzlocal==1.4
unicodecsv==0.14.1
urllib3==1.19.1
urwid==1.3.1
uTidylib==0.3
vinetto==0.7b0
volatility==2.6
wafw00f==0.9.3
wapiti==2.3.0
watchdog==0.8.3
wcwidth==0.1.7
webencodings==0.5
webunit==1.3.10
Werkzeug==0.12.2.dev0
wfuzz==0.0.0
Whoosh==2.7.0
wxPython==3.0.2.0
wxPython-common==3.0.2.0
XlsxWriter==0.9.6
xmlbuilder==1.0
yara-python==3.6.1
zenmap==7.50
zim==0.65
zope.interface==4.3.2

Please help me .

**Comment by andresriancho** [comment]
Looks like you got a network error here:

> ReadTimeoutError: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out.

Run the command again
