### ISSUE TITLE
Unable to launch w3af_console or w3af_gui

### ISSUE THREAD

**Issue by hirizarry643** [andresriancho/w3af#15902]
Getting the same return error when trying to launch either w3af_gui or w3af_console from local host and docker image. This just started happening recently, what's changed?

~/w3af$ ./w3af_console
Traceback (most recent call last):
  File "./w3af_console", line 12, in <module>
    from w3af.core.controllers.dependency_check.dependency_check import dependency_check
  File "/home/toor/w3af/w3af/core/controllers/dependency_check/dependency_check.py", line 31, in <module>
    import pip
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 13, in <module>
    from pip.exceptions import InstallationError, CommandError, PipError
  File "/usr/lib/python2.7/dist-packages/pip/exceptions.py", line 6, in <module>
    from pip._vendor.six import iteritems
  File "/usr/lib/python2.7/dist-packages/pip/_vendor/__init__.py", line 64, in <module>
    vendored("cachecontrol")
  File "/usr/lib/python2.7/dist-packages/pip/_vendor/__init__.py", line 36, in vendored
    __import__(modulename, globals(), locals(), level=0)
  File "/usr/share/python-wheels/CacheControl-0.11.5-py2.py3-none-any.whl/cachecontrol/__init__.py", line 9, in <module>
  File "/usr/share/python-wheels/CacheControl-0.11.5-py2.py3-none-any.whl/cachecontrol/wrapper.py", line 1, in <module>
  File "/usr/share/python-wheels/CacheControl-0.11.5-py2.py3-none-any.whl/cachecontrol/adapter.py", line 3, in <module>
  File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/__init__.py", line 53, in <module>
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/contrib/pyopenssl.py", line 54, in <module>
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

**Comment by Plup-io** [comment]
I have the same error.

**Comment by andresriancho** [comment]
Solved with the latest merge from develop to master I made today. In order to fix this issue you need to go to your w3af directory and run `git pull`, then try to run the `w3af_console` again.
