### ISSUE TITLE
Spiderman plugin not working

### ISSUE THREAD

**Issue by idrinks** [andresriancho/w3af#15971]
Received the following error when using spiderman plugin. 

Exception in thread ThreadProxyRequestHandler:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/share/w3af/w3af/plugins/crawl/spider_man.py", line 197, in handle_request_in_thread
    http_response = self._send_http_request(http_request, grep=grep)
  File "/usr/share/w3af/w3af/core/controllers/daemons/proxy/handler.py", line 144, in _create_error_response
    content = render('error.html', context)
  File "/usr/share/w3af/w3af/core/controllers/daemons/proxy/templates/utils.py", line 19, in render
    return template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/share/w3af/w3af/core/controllers/daemons/proxy/templates/error.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/usr/share/w3af/w3af/core/controllers/daemons/proxy/templates/base.html", line 10, in top-level template code
    {% block content %}
  File "/usr/share/w3af/w3af/core/controllers/daemons/proxy/templates/error.html", line 15, in block "content"
    <div><pre>{{ http_request }}</pre></div>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf2 in position 411: ordinal not in range(128)

**Comment by andresriancho** [comment]
Thanks for reporting this.

Priority set, milestone assigned.
