### ISSUE TITLE
Cannot run w3af after install in Fedora 26

### ISSUE THREAD

**Issue by izauddin** [andresriancho/w3af#16122]
Hi,

I tried to run w3af_gui after cloning it from git. But it said I have to installed python-pip and python-devel.
Both this package has been install in my OS. How to make w3af working ?

My Linux distribution release is => Fedora release 26 (Twenty Six)
My Python version is => Python 2.7.13

[pipfreeze.txt](https://github.com/andresriancho/w3af/files/1426172/pipfreeze.txt)
[w3af_dependency_install.sh.txt](https://github.com/andresriancho/w3af/files/1426176/w3af_dependency_install.sh.txt)

Rgds
Din

**Comment by izauddin** [comment]
Solved this 

I change  CORE_SYSTEM_PACKAGES = ['python-pip', 'python-devel', 'python2-setuptools' to
 CORE_SYSTEM_PACKAGES = ['python2-pip', 'python2-devel', 'python2-setuptools'

Then I change PIPDependency('OpenSSL', 'pyOpenSSL', '16.2.0'), from PIPDependency('OpenSSL', 'pyOpenSSL', '0.15.1'),

Able to run the gui

**Comment by dksh** [comment]
@izauddin wrong way to requirements.py
right way is w3af/w3af/core/controllers/dependency_check/requirements.py
However I can't run w3af_gui, got:
./w3af_gui 
Traceback (most recent call last):
  File "./w3af_gui", line 110, in <module>
    _main()
  File "./w3af_gui", line 106, in _main
    sys.exit(main())
  File "./w3af_gui", line 100, in main
    from w3af.core.ui.gui.main import main as gui_main
  File "/root/Documents/soft/w3af/w3af/core/ui/gui/main.py", line 54, in <module>
    from w3af.core.ui.gui import scanrun, helpers, profiles, compare
  File "/root/Documents/soft/w3af/w3af/core/ui/gui/scanrun.py", line 27, in <module>
    import webkit
  File "/usr/lib64/python2.7/site-packages/webkit/__init__.py", line 21, in <module>
    import webkit
ImportError: libwebkitgtk-1.0.so.0: cannot open shared object file: No such file or directory

But I can run w3af_console
