### ISSUE TITLE
w3af finishes without joining all queues

### ISSUE THREAD

**Issue by andresriancho** [andresriancho/w3af#16194]
```
dav.audit(http://target/dvwa/vulnerabilities/brute/?username=&password=&Login=Login)
dav.audit(http://target/dvwa/vulnerabilities/brute/?username=&password=&Login=Login) took 0.00 seconds to run
ssi.audit(http://target/dvwa/vulnerabilities/brute/?username=&password=&Login=Login)
Created 18 mutants for "Method: GET | http://target/dvwa/vulnerabilities/brute/ | URL encoded form: (username, password, Login)" (query string: 18)
ssi.audit(http://target/dvwa/vulnerabilities/brute/?username=&password=&Login=Login) took 0.03 seconds to run
GET http://target/?mode=phpinfo returned HTTP code "200" (id=5583,from_cache=0,grep=1,rtt=1.26)
csrf.audit(http://target/dvwa/vulnerabilities/brute/?username=&password=&Login=Login)
GET http://target/dvwa/vulnerabilities/fi/?page=1' or pg_sleep(12) and '1'='1 returned HTTP code "200" (id=5584,from_cache=0,grep=1,rtt=1.24)
csrf.audit(http://target/dvwa/vulnerabilities/brute/?username=&password=&Login=Login) took 0.00 seconds to run
(Test id: 139870244662544) 1.24332404137 > 11.8329272469
(Test id: 139870244662544) Failed to control HTTP response delay for URL http://target/dvwa/vulnerabilities/fi/ - parameter "page" for 12 seconds using <ExactDelay (fmt:1' or pg_sleep(%s) and '1'='1, delta:0, mult:1)>, response wait time was: 1.24332404137 seconds and response ID: 5584.
xss.audit(http://target/dvwa/vulnerabilities/brute/?username=&password=&Login=Login)
Created 3 mutants for "Method: GET | http://target/dvwa/vulnerabilities/brute/ | URL encoded form: (username, password, Login)" (query string: 3)
GET http://target/dvwa/vulnerabilities/brute/?username=&Login=Login&password=FrAmE30. returned HTTP code "200" (id=5585,from_cache=0,grep=1,rtt=1.21)
GET http://target/?mode=phpinfo returned HTTP code "200" (id=5586,from_cache=0,grep=1,rtt=1.11)
GET http://target/dvwa/vulnerabilities/fi/?page=include.php returned HTTP code "200" (id=5587,from_cache=0,grep=1,rtt=1.11)
GET http://target/dvwa/vulnerabilities/brute/?username=1;waitfor delay '0:0:12'--&Login=Login&password=FrAmE30. returned HTTP code "200" (id=5588,from_cache=0,grep=1,rtt=0.90)
(Test id: 139872727958736) 0.90106511116 > 11.919405659
(Test id: 139872727958736) Failed to control HTTP response delay for URL http://target/dvwa/vulnerabilities/brute/ - parameter "username" for 12 seconds using <ExactDelay (fmt:1;waitfor delay '0:0:%s'--, delta:0, mult:1)>, response wait time was: 0.90106511116 seconds and response ID: 5588.

Liked it? Contribute with some lines of code!

Failed to HTTP "GET" "http://target/dvwa/vulnerabilities/brute/?username=&Login=Login&password=FrAmE30.". Reason: "", going to retry.
Traceback for this error: Traceback (most recent call last):
  File "/home/caveman/tools/w3af/w3af/core/data/url/extended_urllib.py", line 816, in send
    res = self._opener.open(req)
  File "/home/caveman/tools/w3af/w3af/core/data/url/director.py", line 33, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/home/caveman/tools/w3af/w3af/core/data/url/handlers/keepalive/handler.py", line 330, in http_open
    return self.do_open(req)
  File "/home/caveman/tools/w3af/w3af/core/data/url/handlers/keepalive/handler.py", line 142, in do_open
    resp, start = self._get_response(conn, req)
  File "/home/caveman/tools/w3af/w3af/core/data/url/handlers/keepalive/handler.py", line 218, in _get_response
    resp = conn.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1123, in getresponse
    raise ResponseNotReady()
ResponseNotReady

ExtendedUrllib error rate is at 1%
Re-sending request "<HTTPRequest "http://target/dvwa/vulnerabilities/brute/?username=&password=FrAmE30.&Login=Login" (cookies:True, cache:False)>" after initial exception: ""
Failed to HTTP "GET" "http://target/?mode=phpinfo". Reason: "", going to retry.
Traceback for this error: Traceback (most recent call last):
  File "/home/caveman/tools/w3af/w3af/core/data/url/extended_urllib.py", line 816, in send
    res = self._opener.open(req)
  File "/home/caveman/tools/w3af/w3af/core/data/url/director.py", line 33, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/home/caveman/tools/w3af/w3af/core/data/url/handlers/keepalive/handler.py", line 330, in http_open
    return self.do_open(req)
  File "/home/caveman/tools/w3af/w3af/core/data/url/handlers/keepalive/handler.py", line 142, in do_open
    resp, start = self._get_response(conn, req)
  File "/home/caveman/tools/w3af/w3af/core/data/url/handlers/keepalive/handler.py", line 218, in _get_response
    resp = conn.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1123, in getresponse
    raise ResponseNotReady()
ResponseNotReady

ExtendedUrllib error rate is at 2%
Re-sending request "<HTTPRequest "http://target/?mode=phpinfo" (cookies:True, cache:False)>" after initial exception: ""
Failed to HTTP "GET" "http://target/dvwa/vulnerabilities/fi/?page=include.php". Reason: "", going to retry.
Traceback for this error: Traceback (most recent call last):
  File "/home/caveman/tools/w3af/w3af/core/data/url/extended_urllib.py", line 816, in send
    res = self._opener.open(req)
  File "/home/caveman/tools/w3af/w3af/core/data/url/director.py", line 33, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/home/caveman/tools/w3af/w3af/core/data/url/handlers/keepalive/handler.py", line 330, in http_open
    return self.do_open(req)
  File "/home/caveman/tools/w3af/w3af/core/data/url/handlers/keepalive/handler.py", line 142, in do_open
    resp, start = self._get_response(conn, req)
  File "/home/caveman/tools/w3af/w3af/core/data/url/handlers/keepalive/handler.py", line 218, in _get_response
    resp = conn.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1123, in getresponse
    raise ResponseNotReady()
ResponseNotReady

ExtendedUrllib error rate is at 3%
Re-sending request "<HTTPRequest "http://target/dvwa/vulnerabilities/fi/?page=91 OR 91=91 OR 91=91 " (cookies:True, cache:False)>" after initial exception: ""
Exception while inserting request/response to the database: "Directory does not exist: "" while trying to write DB history to "/home/caveman/.w3af/tmp/31500/main.db_traces/5589.trace"". The request/response that generated the error is: 5589 http://target/dvwa/?mode=phpinfo 200
os_commanding.audit(http://target/dvwa/?mode=phpinfo) took 133.62 seconds to run
Exception while inserting request/response to the database: "Directory does not exist: "" while trying to write DB history to "/home/caveman/.w3af/tmp/31500/main.db_traces/5590.trace"". The request/response that generated the error is: 5590 http://target/dvwa/vulnerabilities/brute/?username=f3epd<f3epdf3epd-->f3epdf3epd*/f3epdf3epd*/:("'f3epdf3epd:f3epdf3epd
f3epdf3epd"f3epdf3epd'f3epdf3epd`f3epdf3epd%20=f3epd&password=FrAmE30.&Login=Login 200
xss.audit(http://target/dvwa/vulnerabilities/brute/?username=&password=&Login=Login) took 0.59 seconds to run
Exception while inserting request/response to the database: "Directory does not exist: "" while trying to write DB history to "/home/caveman/.w3af/tmp/31500/main.db_traces/5591.trace"". The request/response that generated the error is: 5591 http://target/?mode=31%20OR%2031=31%20OR%2031=31%20 200
blind_sqli.audit(http://target/?mode=phpinfo) took 32.15 seconds to run
Exception while inserting request/response to the database: "Directory does not exist: "" while trying to write DB history to "/home/caveman/.w3af/tmp/31500/main.db_traces/5592.trace"". The request/response that generated the error is: 5592 http://target/dvwa/vulnerabilities/brute/?username=19%20OR%2019=19%20OR%2019=19%20&password=FrAmE30.&Login=Login 200
blind_sqli.audit(http://target/dvwa/vulnerabilities/brute/?username=&password=&Login=Login) took 6.85 seconds to run
Exception while inserting request/response to the database: "Directory does not exist: "" while trying to write DB history to "/home/caveman/.w3af/tmp/31500/main.db_traces/5593.trace"". The request/response that generated the error is: 5593 http://target/dvwa/vulnerabilities/brute/?username=&password=FrAmE30.&Login=Login 200
redos.audit(http://target/dvwa/vulnerabilities/brute/?username=&password=&Login=Login) took 2.29 seconds to run
Exception while inserting request/response to the database: "Directory does not exist: "" while trying to write DB history to "/home/caveman/.w3af/tmp/31500/main.db_traces/5594.trace"". The request/response that generated the error is: 5594 http://target/dvwa/vulnerabilities/fi/?page=include.php 200
os_commanding.audit(http://target/dvwa/vulnerabilities/fi/?page=include.php) took 61.19 seconds to run
Exception while inserting request/response to the database: "Directory does not exist: "" while trying to write DB history to "/home/caveman/.w3af/tmp/31500/main.db_traces/5595.trace"". The request/response that generated the error is: 5595 http://target/dvwa/vulnerabilities/brute/?username=&password=FrAmE30.&Login=Login 200
os_commanding.audit(http://target/dvwa/vulnerabilities/brute/?username=&password=&Login=Login) took 15.08 seconds to run
Exception while inserting request/response to the database: "Directory does not exist: "" while trying to write DB history to "/home/caveman/.w3af/tmp/31500/main.db_traces/5596.trace"". The request/response that generated the error is: 5596 http://target/?mode=phpinfo 200
os_commanding.audit(http://target/?mode=phpinfo) took 34.47 seconds to run
[caveman:~/tools/w3af] [w3af] feature/acora* 3m53s ± 
```

**Comment by andresriancho** [comment]
Fixed in https://github.com/andresriancho/w3af/tree/feature/acora
