### ISSUE TITLE
ValueError: I/O operation on closed file

### ISSUE THREAD

**Issue by chhatrachhorm** [andresriancho/w3af#16389]
I installed w3af on kali by modifying the version of python-pybloomfiltermmap to 0.3.15.
**./w3af_console --help** works as expected, but when i run **./w3af_console** alone i got
[-]calg library: http://c-algorithms.sourceforge.net
w3af>>> Traceback (most recent call last):
  File "./w3af_console", line 167, in <module>
	_main()
  File "./w3af_console", line 163, in _main
	sys.exit(main())
  File "./w3af_console", line 158, in main
	return console.sh()
  File "/root/workspace/w3af/w3af/core/ui/console/console_ui.py", line 152, in sh
	term.setRawInputMode(True)
  File "/root/workspace/w3af/w3af/core/ui/console/io/unixctrl.py", line 66, in setRawInputMode
	if not os.isatty(sys.stdin.fileno()):
ValueError: I/O operation on closed file.

**Comment by chhatrachhorm** [comment]
sorry, it is not an issue at all.
this can be fixed by installing **c-algorithms**
