### ISSUE TITLE
error while importing w3af.plugins.crawl.open_api

### ISSUE THREAD

**Issue by sempersecurus** [andresriancho/w3af#17027]
When starting w3af_console, I receive the following error:
"Error while reading plugin options: "There was an error while importing w3af.plugins.crawl.open_api: "'module' object has no attribute 'ReadTimeout'"."

w3af_gui gives more details as follows:
++++++++++++++++++++++++++++++++++
sudo ./w3af_gui 
Starting w3af, running on:
  Python version: 2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]
  Platform: Ubuntu 14.04 trusty
  GTK version: 2.24.23
  PyGTK version: 2.24.0
  w3af version:
    w3af - Web Application Attack and Audit Framework
    Version: 2018.5.24
    Revision: 356b14b975 - 24 May 2018 14:40
    Branch: master
    Local changes: No
    Author: Andres Riancho and the w3af team.
Traceback (most recent call last):
  File "./w3af_gui", line 110, in <module>
    _main()
  File "./w3af_gui", line 106, in _main
    sys.exit(main())
  File "./w3af_gui", line 101, in main
    gui_main(profile, doupdate)
  File "/home/stalk/tools/w3af/w3af/core/ui/gui/main.py", line 936, in main
    MainApp(profile, do_upd)
  File "/home/stalk/tools/w3af/w3af/core/ui/gui/main.py", line 413, in __init__
    self.pcbody = pluginconfig.PluginConfigBody(self, self.w3af)
  File "/home/stalk/tools/w3af/w3af/core/ui/gui/pluginconfig.py", line 624, in __init__
    self.pan = self._buildpan()
  File "/home/stalk/tools/w3af/w3af/core/ui/gui/pluginconfig.py", line 643, in _buildpan
    self.config_panel)
  File "/home/stalk/tools/w3af/w3af/core/ui/gui/pluginconfig.py", line 245, in __init__
    if self._getEditablePlugin(plugin, plugintype):
  File "/home/stalk/tools/w3af/w3af/core/ui/gui/pluginconfig.py", line 301, in _getEditablePlugin
    plugin = self.w3af.plugins.get_plugin_inst(ptype, pname)
  File "/home/stalk/tools/w3af/w3af/core/controllers/core_helpers/plugins.py", line 282, in get_plugin_inst
    plugin_inst = factory('w3af.plugins.%s.%s' % (plugin_type, plugin_name))
  File "/home/stalk/tools/w3af/w3af/core/controllers/misc/factory.py", line 81, in factory
    raise BaseFrameworkException(msg % (module_name, e))
BaseFrameworkException: There was an error while importing w3af.plugins.crawl.open_api: "'module' object has no attribute 'ReadTimeout'".
+++++++++++++++++++++++++++++++++++++++

**Comment by andresriancho** [comment]
This is really strange. No code in w3af references `ReadTimeout`, so it has to be something in the dependencies.

Could you please send me the output of `pip freeze` command?

**Comment by sempersecurus** [comment]
stalk@stalk:~$ pip freeze
acora==2.1
apt-xapian-index==0.45
asn1crypto==0.24.0
backports.ssl-match-hostname==3.4.0.2
biplist==1.0.3
blinker==1.3
bravado==9.2.2
bravado-core==4.13.4
certifi==2015.4.28
cffi==1.11.5
chardet==3.0.4
CherryPy==3.8.0
clamd==1.0.1
cluster==1.1.1b3
colorama==0.2.5
ConfigArgParse==0.9.3
configobj==4.7.2
cryptography==2.2.2
darts.util.lru==0.5
diff-match-patch==20121119
ds-store==1.1.2
enum34==1.0.4
esmre==0.3.1
Flask==0.10.1
functools32==3.2.3.post2
future==0.16.0
futures==3.2.0
gitdb==0.6.4
gitdb2==2.0.3
GitPython==2.1.3
guess-language==0.2
halberd==0.2.4
hpack==1.0.1
html2text==2015.6.21
html5lib==0.999
idna==2.6
ipaddress==1.0.7
itsdangerous==0.24
Jinja2==2.10
jsonref==0.1
jsonschema==2.6.0
Landscape-Client==14.12
lxml==3.4.4
lz4==1.1.0
M2Crypto==0.21.1
mac-alias==2.0.7
Mako==1.0.3
Markdown==2.6.1
MarkupSafe==0.23
mitmproxy==0.13
msgpack==0.5.6
msgpack-python==0.4.4
ndg-httpsclient==0.3.3
netaddr==0.7.18
netlib==0.13.1
nltk==3.0.1
PAM==0.4.2
passlib==1.6.2
pdfminer==20140328
Pebble==4.3.8
phply==0.9.1
Pillow==2.8.2
ply==3.4
psutil==2.2.1
pyasn1==0.4.2
pybloomfiltermmap==0.3.14
pyClamd==0.4.0
pycparser==2.14
pycrypto==2.6.1
PyGithub==1.21.0
pygobject==3.12.0
pyOpenSSL==17.4.0
pyparsing==2.0.3
pyperclip==1.5.11
pyserial==2.6
python-apt===0.9.3.5ubuntu2
python-dateutil==2.7.3
python-debian===0.1.21-nmu2ubuntu2
python-ntlm==1.0.1
pytz==2018.4
pyxdg==0.25
PyYAML==3.12
requests==2.2.1
rfc3987==1.3.7
ruamel.ordereddict==0.4.8
scapy-real==2.2.0.dev0
simplejson==3.15.0
six==1.5.2
smmap==0.9.0
smmap2==2.0.3
ssh-import-id==3.21
stopit==1.1.0
strict-rfc3339==0.7
swagger-spec-validator==2.1.0
tblib==0.2.0
termcolor==1.1.0
tldextract==1.7.2
tornado==4.2
Twisted-Core==13.2.0
urllib3==1.7.1
urwid==1.3.0
vulndb==0.1.0
webcolors==1.8.1
Werkzeug==0.10.4
xdot==0.6
zenmap===7.25SVN
zope.interface==4.0.5

**Comment by andresriancho** [comment]
I have a different version of bravado core, maybe you could try:

```
pip install bravado-core==4.13.1
```

Then run the GUI again?

If that doesn't work, please edit your [w3af/w3af/core/controllers/misc/factory.py](https://github.com/andresriancho/w3af/blob/master/w3af/core/controllers/misc/factory.py#L79-L81) , it looks like:

```python
    except Exception, e:
        msg = 'There was an error while importing %s: "%s".'
        raise BaseFrameworkException(msg % (module_name, e))
```

Change to:

```python
    except Exception, e:
        raise
        msg = 'There was an error while importing %s: "%s".'
        raise BaseFrameworkException(msg % (module_name, e))
```

Run the GUI again, and please send the new error.

**Comment by sempersecurus** [comment]
Thank you Andres.  I installed bravado-core 4.13.1, but it still failed.  Here is the GUI output after modifying factory.py
++++++++++++++++++++++++++++++++++++++++++++
Starting w3af, running on:
  Python version: 2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]
  Platform: Ubuntu 14.04 trusty
  GTK version: 2.24.23
  PyGTK version: 2.24.0
  w3af version:
    w3af - Web Application Attack and Audit Framework
    Version: 2018.5.24
    Revision: 356b14b975 - 24 May 2018 14:40
    Branch: master
    Local changes: Yes
    Author: Andres Riancho and the w3af team.
Traceback (most recent call last):
  File "./w3af_gui", line 110, in <module>
    _main()
  File "./w3af_gui", line 106, in _main
    sys.exit(main())
  File "./w3af_gui", line 101, in main
    gui_main(profile, doupdate)
  File "/home/stalk/tools/w3af/w3af/core/ui/gui/main.py", line 936, in main
    MainApp(profile, do_upd)
  File "/home/stalk/tools/w3af/w3af/core/ui/gui/main.py", line 413, in __init__
    self.pcbody = pluginconfig.PluginConfigBody(self, self.w3af)
  File "/home/stalk/tools/w3af/w3af/core/ui/gui/pluginconfig.py", line 624, in __init__
    self.pan = self._buildpan()
  File "/home/stalk/tools/w3af/w3af/core/ui/gui/pluginconfig.py", line 643, in _buildpan
    self.config_panel)
  File "/home/stalk/tools/w3af/w3af/core/ui/gui/pluginconfig.py", line 245, in __init__
    if self._getEditablePlugin(plugin, plugintype):
  File "/home/stalk/tools/w3af/w3af/core/ui/gui/pluginconfig.py", line 301, in _getEditablePlugin
    plugin = self.w3af.plugins.get_plugin_inst(ptype, pname)
  File "/home/stalk/tools/w3af/w3af/core/controllers/core_helpers/plugins.py", line 282, in get_plugin_inst
    plugin_inst = factory('w3af.plugins.%s.%s' % (plugin_type, plugin_name))
  File "/home/stalk/tools/w3af/w3af/core/controllers/misc/factory.py", line 62, in factory
    __import__(module_name)
  File "/home/stalk/tools/w3af/w3af/plugins/crawl/open_api.py", line 30, in <module>
    from w3af.core.data.parsers.doc.open_api import OpenAPI
  File "/home/stalk/tools/w3af/w3af/core/data/parsers/doc/open_api/__init__.py", line 1, in <module>
    from .main import OpenAPI
  File "/home/stalk/tools/w3af/w3af/core/data/parsers/doc/open_api/main.py", line 34, in <module>
    from w3af.core.data.parsers.doc.open_api.requests import RequestFactory
  File "/home/stalk/tools/w3af/w3af/core/data/parsers/doc/open_api/requests.py", line 23, in <module>
    from bravado.client import construct_request
  File "/usr/local/lib/python2.7/dist-packages/bravado/client.py", line 59, in <module>
    from bravado.requests_client import RequestsClient
  File "/usr/local/lib/python2.7/dist-packages/bravado/requests_client.py", line 214, in <module>
    class RequestsFutureAdapter(FutureAdapter):
  File "/usr/local/lib/python2.7/dist-packages/bravado/requests_client.py", line 219, in RequestsFutureAdapter
    timeout_errors = [requests.exceptions.ReadTimeout]
AttributeError: 'module' object has no attribute 'ReadTimeout'
++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by andresriancho** [comment]
I believe the workaround for your problem is:

```
pip install --upgrade requests
```

The root cause was reported to `bravado-core` https://github.com/Yelp/bravado-core/issues/271
