### ISSUE TITLE
Exception in thread WorkerPoolStateObserve

### ISSUE THREAD

**Issue by moss1993** [andresriancho/w3af#17110]
```
Exception in thread WorkerPoolStateObserver:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/test/w3af-master/w3af/core/controllers/core_helpers/strategy_observers/thread_state_observer.py", line 143, in thread_worker
    self.inspect_data_to_log(pool, inspect_data)
  File "/test/w3af-master/w3af/core/controllers/core_helpers/strategy_observers/thread_state_observer.py", line 266, in inspect_data_to_log
    args_str = ', '.join(smart_str_ignore(repr(arg)) for arg in worker_state['args'])
  File "/test/w3af-master/w3af/core/controllers/core_helpers/strategy_observers/thread_state_observer.py", line 266, in <genexpr>
    args_str = ', '.join(smart_str_ignore(repr(arg)) for arg in worker_state['args'])
UnicodeEncodeError: 'ascii' codec can't encode characters in position 51-54: ordinal not in range(128)
```

**Comment by andresriancho** [comment]
Just merged develop into master.

This issue was fixed a couple of weeks ago in develop branch and should now also be fixed in master.

Just `git pull` to get the latest version

Thanks
