### ISSUE TITLE
Failed to Retrive url 

### ISSUE THREAD

**Issue by omban007** [andresriancho/w3af#17368]
I have tried simple program running in diffrent urls but is does not work it shows different issues 
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    scan.get_urls()
  File "/usr/local/lib/python2.7/dist-packages/w3af_api_client/scan.py", line 137, in get_urls
    raise APIException('Failed to retrieve urls')

Another issue is:

    conn = Connection('http://127.0.0.1:5000/')
  File "/usr/local/lib/python2.7/dist-packages/w3af_api_client/connection.py", line 42, in __init__
    self.can_access_api()
  File "/usr/local/lib/python2.7/dist-packages/w3af_api_client/connection.py", line 52, in can_access_api
    raise APIException(msg % e)
w3af_api_client.utils.exceptions.APIException: An exception was raised when connecting to REST API: "HTTPConnectionPool(host='127.0.0.1', port=5000): Read timed out. (read timeout=5)"

Please somebody help me to solve the issue. Thanks.

**Comment by 0xInfection** [comment]
It is post probably due to your very slow internet connection, or probably you sites are not responding properly.

**Comment by omban007** [comment]
Thank you 0xinfection
