### ISSUE TITLE
w3af_api error

### ISSUE THREAD

**Issue by 0FuzzingQ** [andresriancho/w3af#17449]
error 
Exception in thread CrawlInfraController:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/bin/web/w3af/w3af/w3af/core/controllers/core_helpers/consumers/crawl_infrastructure.py", line 92, in run
    work_unit = self.in_queue.get(timeout=0.1)
  File "/usr/local/lib/python2.7/Queue.py", line 178, in get
    item = self._get()
  File "/usr/bin/web/w3af/w3af/w3af/core/data/misc/ordered_cached_queue.py", line 181, in _get
    item = self.disk.pop(unique_id)
  File "/usr/bin/web/w3af/w3af/w3af/core/data/db/disk_dict.py", line 139, in pop
    value = self.get(key)
  File "/usr/bin/web/w3af/w3af/w3af/core/data/db/disk_dict.py", line 131, in get
    return self[key]
  File "/usr/bin/web/w3af/w3af/w3af/core/data/db/disk_dict.py", line 122, in __getitem__
    return cPickle.loads(r[0][0])
EOFError

server end:
>>> res = requests.get('http://127.0.0.1:5000/scans/0/kb')
>>> res.text
'{\n  "code": 500,\n  "exception_type": "EOFError",\n  "filename": "knowledge_base.py",\n  "function_name": "get_all_entries_of_class_iter",\n  "line_number": 677,\n  "message": "",\n  "please": "https://github.com/andresriancho/w3af/issues/new"\n}'

**Comment by andresriancho** [comment]
Thanks for reporting this, I was able to understand where this happens, but not sure why. In order for this to happen an INSERT to a SQLite DB should be incomplete, and when the data is read and deserialized (in `cPickle.loads(r[0][0])`) the EOF is found.

Are you able to reproduce this every time you scan a specific site? Could you send me the steps to reproduce and a debug log (generated by `text_file` with `verbose` on)?

**Comment by 0FuzzingQ** [comment]
> Thanks for reporting this, I was able to understand where this happens, but not sure why. In order for this to happen an INSERT to a SQLite DB should be incomplete, and when the data is read and deserialized (in `cPickle.loads(r[0][0])`) the EOF is found.
> 
> Are you able to reproduce this every time you scan a specific site? Could you send me the steps to reproduce and a debug log (generated by `text_file` with `verbose` on)?

i have solved this problem by change my python version from 2.7.2 to 2.7.12 and it runs successfully but i don not know why 
sorry my english is not so good
