### ISSUE TITLE
ImportError: No module named webkit

### ISSUE THREAD

**Issue by yazarneon** [andresriancho/w3af#17505]
root@kali:~/Desktop/w3af# ./w3af_gui
Traceback (most recent call last):
  File "./w3af_gui", line 110, in <module>
    _main()
  File "./w3af_gui", line 106, in _main
    sys.exit(main())
  File "./w3af_gui", line 100, in main
    from w3af.core.ui.gui.main import main as gui_main
  File "/root/Desktop/w3af/w3af/core/ui/gui/main.py", line 54, in <module>
    from w3af.core.ui.gui import scanrun, helpers, profiles, compare
  File "/root/Desktop/w3af/w3af/core/ui/gui/scanrun.py", line 27, in <module>
    import webkit
ImportError: No module named webkit

**Comment by beardedcat** [comment]
I've also encountered this error. Were you able to work out a fix?
