### ISSUE TITLE
[Auto-Generated] Bug Report - TypeError: can only join an iterable

### ISSUE THREAD

**Issue by 1d3df9903ad** [andresriancho/w3af#17700]
No user description was provided for this bug report given that it was related to handled exceptions in scan with id 1c2db1a7b6
## Version Information
```
  Python version: 2.7.16rc1 (default, Feb 18 2019, 11:05:09) [GCC 8.2.0]
  Platform: Kali kali-rolling kali-rolling
  GTK version: 2.24.32
  PyGTK version: 2.24.0
  w3af version:
    w3af - Web Application Attack and Audit Framework
    Version: 2019.1.2
    Revision: 0e6dc291a4 - 02 Mar 2019 23:29
    Branch: master
    Local changes: No
    Author: Andres Riancho and the w3af team.
```
## Traceback
```pytb
A "TypeError" exception was found while running crawl.web_spider on "Method: GET | https://domain/wp-content/plugins/countdown-timer-ultimate/languages/countdown-timer-ultimate-en_US.po". The exception was: "can only join an iterable" at None:None():None. The full traceback is:

Traceback (most recent call last):
  File "/root/tools/w3af/w3af/core/controllers/threads/threadpool.py", line 278, in __call__
    result = (True, func(*args, **kwds))
  File "/root/tools/w3af/w3af/core/controllers/threads/pool276.py", line 67, in mapstar
    return map(*args)
  File "/root/tools/w3af/w3af/core/controllers/threads/threadpool.py", line 55, in __call__
    return self.func_orig(*args)
  File "/root/tools/w3af/w3af/plugins/crawl/web_spider.py", line 374, in _verify_reference
    if not is_404(resp):
  File "/root/tools/w3af/w3af/core/controllers/core_helpers/fingerprint_404.py", line 412, in is_404
    return fp_404_db.is_404(http_response)
  File "/root/tools/w3af/w3af/core/controllers/core_helpers/not_found/decorators.py", line 123, in __call__
    return self._function(*args, **kwargs)
  File "/root/tools/w3af/w3af/core/controllers/core_helpers/not_found/decorators.py", line 58, in __call__
    result = self._function(*args, **kwargs)
  File "/root/tools/w3af/w3af/core/controllers/core_helpers/fingerprint_404.py", line 99, in is_404
    if self._is_404_complex(http_response):
  File "/root/tools/w3af/w3af/core/controllers/core_helpers/fingerprint_404.py", line 186, in _is_404_complex
    known_404 = self._get_404_response(http_response, query, debugging_id)
  File "/root/tools/w3af/w3af/core/controllers/core_helpers/fingerprint_404.py", line 393, in _get_404_response
    debugging_id)
  File "/root/tools/w3af/w3af/core/controllers/core_helpers/not_found/generate_404.py", line 261, in send_request_generate_404
    url_404 = get_url_for_404_request(http_response, seed=seed)
  File "/root/tools/w3af/w3af/core/controllers/core_helpers/not_found/generate_404.py", line 280, in get_url_for_404_request
    relative_url = generate_404_filename(filename, seed=seed)
  File "/root/tools/w3af/w3af/core/controllers/core_helpers/not_found/generate_404.py", line 240, in generate_404_filename
    return generate_404_by_shuffle(orig_filename, extension, seed=seed)
  File "/root/tools/w3af/w3af/core/controllers/core_helpers/not_found/generate_404.py", line 135, in generate_404_by_shuffle
    mod_filename = ''.join(mod_filename)
TypeError: can only join an iterable

```
## Enabled Plugins
```python
{'attack': {},
 'audit': {u'blind_sqli': <OptionList: eq_limit>,
           u'dav': <OptionList: >,
           u'eval': <OptionList: use_time_delay|use_echo>,
           u'file_upload': <OptionList: extensions>,
           u'lfi': <OptionList: >,
           u'os_commanding': <OptionList: >,
           u'rfi': <OptionList: listen_address|listen_port|use_w3af_site>,
           u'sqli': <OptionList: >},
 'auth': {},
 'bruteforce': {},
 'crawl': {u'web_spider': <OptionList: only_forward|follow_regex|ignore_regex>},
 'evasion': {},
 'grep': {},
 'infrastructure': {'allowed_methods': {}, 'server_header': {}},
 'mangle': {},
 'output': {u'console': <OptionList: verbose|use_colors>}}

```

**Comment by perfgao** [comment]
Like many list methods, ```random.shuffle()``` , acts in-place , and therefore returns None. so ```mod_filename``` is therefore None, hence the error.

you can look this: https://github.com/andresriancho/w3af/pull/17964
