### ISSUE TITLE
Does the w3af have python3 version?

### ISSUE THREAD

**Issue by jianghoo** [andresriancho/w3af#17866]
Does the w3af have python3 version?

**Comment by andresriancho** [comment]
No, but we'll have to migrate at some point!

**Comment by MartinFalatic** [comment]
That time is quickly approaching (especially since Python 2 won't have security updates itself after the end of this year).  Has there been progress in this regard?

**Comment by andresriancho** [comment]
No progress in this area.

**Comment by XVilka** [comment]
Python 2 is dead in a month, and many distributions started to remove python2 packages already. It makes sense to start the migration.

https://pythonclock.org/

**Comment by anthraxx** [comment]
Hm yeah, bigger major distros will not package python2 in upcoming versions, sad to see this tool struggling soon. It may obviously be lots of work and testing time, but hope this doesn't vanish

**Comment by juju4** [comment]
trying switch to python3 in my ansible role (https://travis-ci.org/juju4/ansible-w3af/jobs/654157164#L3736) and many issues found
- pdfminer: to update to latest 20191125 (except xenial which seems to only allow 20191016)
- pybloomfiltermmap: issue as not maintained, latest 0.3.15 from 2016
- scapy-real: update to 2.3/latest/Mar 2019, marked deprecated
- halberd: same latest 0.2.4 from 2010
- esmre: latest 0.3.1 from Oct 2008
- ruamel.ordereddict: latest 0.4.14 from Jul 2019

and after, get
https://travis-ci.org/juju4/ansible-w3af/jobs/654221776#L4076
```
# w3af_console -v
Traceback (most recent call last):
  File "/usr/local/share/w3af/w3af_console", line 12, in <module>
    from w3af.core.controllers.dependency_check.dependency_check import dependency_check
  File "/usr/local/share/w3af/w3af/core/controllers/dependency_check/dependency_check.py", line 26, in <module>
    from w3af.core.data.db.startup_cfg import StartUpConfig
  File "/usr/local/share/w3af/w3af/core/data/db/startup_cfg.py", line 22, in <module>
    import ConfigParser
ModuleNotFoundError: No module named 'ConfigParser'
```
classic python3 migration
https://stackoverflow.com/questions/14087598/python-3-importerror-no-module-named-configparser

any plan?

thanks

**Comment by linxon** [comment]
bump

**Comment by Kali95739** [comment]
Is this tool still active or is it dead

**Comment by Kali95739** [comment]
It's dead use industry standards such as acunetix burpsuite or detectify.

**Comment by ITSundae** [comment]
It is depressing that w3af quietly died like this. At the moment, it requires a good bit of messing around to get working now. I hope to see it return again, but it does not seem likely as even the author has left it behind.

**Comment by codders** [comment]
I'm happy to report that there is some work on-going on a python3 version: https://github.com/w4af/w4af
It's still in pretty early stages, but feedback and user experience reports are greatly appreciated.
