### ISSUE TITLE
File "./w3af api", line 12, in <module>from w3af.core.ui. api.main import main

### ISSUE THREAD

**Issue by wangenlei-git** [andresriancho/w3af#18051]

**Comment by wangenlei-git** [comment]
- 1. 「root@ecs-c839-0003 w3afl# ./w3af api
- 2. Traceback (most recent call last):
- 3. File "./w3af api", line 12, in 
- 4.   from w3af.core.ui.api.main import main
- 5. File "/root/w3af/w3af/core/ui/api/ init .py", line 1, in 
- 6.  from .utils.mp flask import ThreadedFlask
- 7. File "/root/w3af/w3af/core/ui/api/utils/mp flask.py", line 7, in 
- 8.  from werkzeuq.servinq import select ip version
- 9. ImportError:cannot import name select_ip_version
