### ISSUE TITLE
Consider Updating Bravado_core to 5.15.0 to fix Open API Bugs

### ISSUE THREAD

**Issue by nstarke** [andresriancho/w3af#18218]
Hello,
I was experiencing some parameter parsing issues with the `crawl.openapi` plugin, where w3af would recognize some routes but no parameters for any routes, and then other routes were not found at all entirely. So on a whim I tried to upgrade the `bravado_core` package to `5.15.0`. Lo and behold, the parsing problems went away and I was able to get a clean run out of a OpenAPI json doc.  Just something to consider.  Thanks for making this project possible.

**Comment by andresriancho** [comment]
Thanks for reporting this.

Upgraded to `5.15.0` and run the unittests, all but one `PASS`:

```
======================================================================
ERROR: test_model_param_nested_loop_in_json (w3af.core.data.parsers.doc.open_api.tests.test_specification.TestSpecification)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/eth/tools/w3af/w3af/core/data/parsers/doc/open_api/tests/test_specification.py", line 468, in test_model_param_nested_loop_in_json
    data = [d for d in handler.get_api_information()]
  File "/home/eth/tools/w3af/w3af/core/data/parsers/doc/open_api/specification.py", line 91, in get_api_information
    for _operation in operations:
  File "/home/eth/tools/w3af/w3af/core/data/parsers/doc/open_api/specification.py", line 115, in _set_operation_params
    op = parameter_handler.set_operation_params(optional=optional)
  File "/home/eth/tools/w3af/w3af/core/data/parsers/doc/open_api/parameters.py", line 78, in set_operation_params
    self._set_param_value(parameter)
  File "/home/eth/tools/w3af/w3af/core/data/parsers/doc/open_api/parameters.py", line 259, in _set_param_value
    value = self._get_param_value(param_spec)
  File "/home/eth/tools/w3af/w3af/core/data/parsers/doc/open_api/parameters.py", line 280, in _get_param_value
    value = self._get_param_value_for_model(param_spec)
  File "/home/eth/tools/w3af/w3af/core/data/parsers/doc/open_api/parameters.py", line 457, in _get_param_value_for_model
    parameter_definition = self._get_object_definition(param_spec)
  File "/home/eth/tools/w3af/w3af/core/data/parsers/doc/open_api/parameters.py", line 476, in _get_object_definition
    return self._get_object_definition_impl(param_spec)
  File "/home/eth/tools/w3af/w3af/core/data/parsers/doc/open_api/parameters.py", line 525, in _get_object_definition_impl
    param_spec = self._merge_all_parts(all_parts)
  File "/home/eth/tools/w3af/w3af/core/data/parsers/doc/open_api/parameters.py", line 502, in _merge_all_parts
    object_definition = self._get_object_definition_impl(part)
  File "/home/eth/tools/w3af/w3af/core/data/parsers/doc/open_api/parameters.py", line 525, in _get_object_definition_impl
    param_spec = self._merge_all_parts(all_parts)
  File "/home/eth/tools/w3af/w3af/core/data/parsers/doc/open_api/parameters.py", line 502, in _merge_all_parts
    object_definition = self._get_object_definition_impl(part)
  File "/home/eth/tools/w3af/w3af/core/data/parsers/doc/open_api/parameters.py", line 525, in _get_object_definition_impl
    param_spec = self._merge_all_parts(all_parts)
  File "/home/eth/tools/w3af/w3af/core/data/parsers/doc/open_api/parameters.py", line 502, in _merge_all_parts
    object_definition = self._get_object_definition_impl(part)
```

**Comment by andresriancho** [comment]
Investigating...

**Comment by andresriancho** [comment]
Nested loop test added in https://github.com/andresriancho/w3af/commit/57b4bfac2e102cfcc2f8cfcfa7830d0022355fd1

**Comment by andresriancho** [comment]
Fixed in `develop` branch
