### ISSUE TITLE
not opening in mac os Catalina 

### ISSUE THREAD

**Issue by amir992710** [andresriancho/w3af#18226]
Hi
I have solved almost all the errors and problems I got from the w3af_gui 
the packages and pip things,
after not getting an error, I ran the./w3af_gui, it tries to open (by a python on a jet icon) but it doesn't open it at all.

Thank you for helping me in advance

**Comment by andresriancho** [comment]
hmmmmm, could you give me more info? What do you see on the screen?

**Comment by amir992710** [comment]
root > ./w3af_gui 
zsh: abort      ./w3af_gui

=============the pop up error ==========
Python quit unexpectedly
Click Reopen to open the application again. Click Report to see more detailed information and send a report to Apple

**Comment by amir992710** [comment]
well after realizing that zsh runs by default on mac terminals in Catalina Version.
I changed the default to bash.
then i ran it and other programs which i got this. 

./w3af_gui 
Abort trap: 6


-.- 
so annoying

**Comment by amir992710** [comment]
Hello again @andresriancho 
I have solved that problem, it was libcrypto issues, now i get this! :

Traceback (most recent call last):
  File "w3af_gui", line 110, in <module>
    _main()
  File "w3af_gui", line 106, in _main
    sys.exit(main())
  File "w3af_gui", line 100, in main
    from w3af.core.ui.gui.main import main as gui_main
  File "/Users/root.seveni/tools/must-see/w3af/w3af/core/ui/gui/main.py", line 54, in <module>
    from w3af.core.ui.gui import scanrun, helpers, profiles, compare
  File "/Users/root.seveni/tools/must-see/w3af/w3af/core/ui/gui/scanrun.py", line 27, in <module>
    import webkit
ImportError: No module named webkit

i tried to install webkit modules from pip and pip3 , didnt find anything, and also ran w3af_gui with python 2 and 3 , same!
