### ISSUE TITLE
Database disk image is malformed

### ISSUE THREAD

**Issue by valodo** [andresriancho/w3af#18457]
Hello,
I have started to use w3af in order to scan a test website. I have encountered  some problems during the installation and for this reason I decided to use docker. However, when I try to scan the website, w3af returns me several errors. Following, I report the executed instructions and the errors:
http-settings
set headers_file /root/w3af-shared/header.txt
set user_agent Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
set proxy_port 8082
back

plugins
output console, html_file
output config console
set verbose True
back
output config html_file
set output_file /root/w3af-shared/report.html
set verbose True
back

audit all
crawl web_spider
crawl config web_spider
set only_forward True
back

grep all
back

target
set target https://192.168.58.60:8080/test/dashboard, https://192.168.58.60:8080/test/director/host/add?type=object
back

start
____________________________

strategy.start() found exception "Failed to initialize the 404 detection, original exception was: "no such table: disk_dict_deque_WAnCexCbtxbTxpIfALGWkIuAQchcBx"."
no such table: knowledge_base_UwdOSwZXiMWEuLTGOZoAeKyYWpIfkM
no such table: disk_dict_ssi_BgDPAVRwoiJMBiEkDRHSzXcDClGkMS
no such table: disk_list_kb_fuzzable_requests_yiSSVsDygDcjFSqeSVIeydFfKjtdrL
The plugin "allowed_methods" raised an exception in the end() method: no such table: knowledge_base_UwdOSwZXiMWEuLTGOZoAeKyYWpIfkM
The plugin "web_spider" raised an exception in the end() method: no such table: disk_list_web_spider_uLWWNiurAApcwTJluoSjHZBegXbfUI
strategy.start() found exception while terminating workers "no such table: disk_list_kb_urls_QaeMyfsAsZSJThfKhxJnqnApUPLikE"
The following error was detected and could not be resolved:
Failed to initialize the 404 detection, original exception was: "no such table: disk_dict_deque_WAnCexCbtxbTxpIfALGWkIuAQchcBx".

Scan finished in 4 seconds.
Stopping the core...
no such table: knowledge_base_UwdOSwZXiMWEuLTGOZoAeKyYWpIfkM
w3af>>> exit
w3af>>> The user stopped the core, finishing threads...
0 seconds. were needed to stop the core.
Traceback (most recent call last):
  File "/home/w3af/w3af/w3af_console", line 167, in <module>
    _main()
  File "/home/w3af/w3af/w3af_console", line 163, in _main
    sys.exit(main())
  File "/home/w3af/w3af/w3af_console", line 158, in main
    return console.sh()
  File "/home/w3af/w3af/w3af/core/ui/console/console_ui.py", line 167, in sh
    self._w3af.quit()
  File "/home/w3af/w3af/w3af/core/controllers/w3afCore.py", line 404, in quit
    self.uri_opener.end()
  File "/home/w3af/w3af/w3af/core/data/url/extended_urllib.py", line 449, in end
    self.settings.clear_cache()
  File "/home/w3af/w3af/w3af/core/data/url/opener_settings.py", line 408, in clear_cache
    return self._cache_handler.clear()
  File "/home/w3af/w3af/w3af/core/data/url/handlers/cache.py", line 52, in clear
    return CacheClass.clear()
  File "/home/w3af/w3af/w3af/core/data/url/handlers/cache_backend/db.py", line 119, in clear
    return HistoryItem().clear()
  File "/home/w3af/w3af/w3af/core/data/db/history.py", line 414, in clear
    self._db.clear_table(self.get_table_name()).result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 404, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 356, in __get_result
    raise self._exception
w3af.core.controllers.exceptions.DBException: database disk image is malformed

**Comment by andresriancho** [comment]
Are you getting this on every scan? Which w3af version are you using?

**Comment by valodo** [comment]
This problem does not happen at each scan. It seams to occur when I set the verbose flag to True and when I enable the web_spider with False as value for only_forward.
The version of w3af docker is 1.7.2, but this morning I was able to install the console version on my pc thanks to the reply in the previous issue [(https://github.com/andresriancho/w3af/issues/18451).](https://github.com/andresriancho/w3af/issues/18451). Therefore, I will try to test my web application with the latest version (2019.1.2) of w3af and if I find the same errors, I reply here putting all the steps.
