### ISSUE TITLE
W3af bash script cron issue

### ISSUE THREAD

**Issue by sivassk7** [andresriancho/w3af#18644]
Hi I'm getting this error while scheduling w3af in crontab can you help on this 

Error while reading plugin options: "Failed to create an instance of "retirejs". The original exception was: "list index out of range". Traceback for this error:
Traceback (most recent call last):
  File "/data/w3af/w3af/core/controllers/misc/factory.py", line 97, in factory
    inst = a_class(*args)
  File "/data/w3af/w3af/plugins/grep/retirejs.py", line 68, in __init__
    self._retirejs_path = self._get_retirejs_path()
  File "/data/w3af/w3af/plugins/grep/retirejs.py", line 499, in _get_retirejs_path
    return paths_to_retire[0]
IndexError: list index out of range

**Comment by sivassk7** [comment]
#!/bin/bash
w3af_console -s /scan.w3af 
If i run the script manually it's working fine and getting the report everything but while scheduling it in cron getting that error
profiles use full_audit
plugins output html_file
plugins output config html_file
set output_file /data/w3af/report/2020-07-13_http/test11.html
back
target set target https://itsec.com
start
exit
