### ISSUE TITLE
Can't start scan with w3af_api

### ISSUE THREAD

**Issue by nerdb2** [andresriancho/w3af#18650]
Hey there,

I am trying to start a scan using w3af_api, but I am getting the below error:

```
* Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [18/Jul/2020 01:14:50] "GET /version HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1410, in handle_exception
    return handler(e)
  File "/home/akshat/Documents/Projects/Github/w3af/w3af/core/ui/api/resources/error_handlers.py", line 79, in error_500_handler
    'message': 'REST API error'})
  File "/usr/local/lib/python2.7/dist-packages/flask/json.py", line 235, in jsonify
    and not request.is_xhr:
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'is_xhr'
```

Below is the code I am using to execute the scan:
```
response = requests.post('http://127.0.0.1:5000/scans/',
                         data=json.dumps(data),
                         headers={'content-type': 'application/json'})

```

**Comment by charlesreid1** [comment]
The `is_xhr` method has been deprecated and removed from Flask, so this is a problem with the w3af library being too out-of-date. See discussion [here](https://stackoverflow.com/questions/43871003/identify-if-flask-request-is-from-javascript-or-not) and [here](https://stackoverflow.com/questions/43871003/identify-if-flask-request-is-from-javascript-or-not) for why that method was removed.

If you want to fix this, I recommend starting a fork of this repo, as it does not appear to be actively maintained. :(
