### ISSUE TITLE
Install w3af on Kali error

### ISSUE THREAD

**Issue by IqbalKhaan** [andresriancho/w3af#18827]
When I run ./w3af_console, it throws out an error
Traceback (most recent call last):
  File "/home/iqbalkhan/w3af/./w3af_console", line 12, in <module>
    from w3af.core.controllers.dependency_check.dependency_check import dependency_check
  File "/home/iqbalkhan/w3af/w3af/core/controllers/dependency_check/dependency_check.py", line 26, in <module>
    from w3af.core.data.db.startup_cfg import StartUpConfig
  File "/home/iqbalkhan/w3af/w3af/core/data/db/startup_cfg.py", line 22, in <module>
    import ConfigParser
ModuleNotFoundError: No module named 'ConfigParser'

**Comment by sammy1881** [comment]
It needs python2.7. Try running the following 

`sudo apt install python-pip python2.7-dev`
`sudo ln -s /usr/bin/python2 /usr/bin/python`

**Comment by IqbalKhaan** [comment]
> It needs python2.7. Try running the following
> 
> `sudo apt install python-pip python2.7-dev` `sudo ln -s /usr/bin/python2 /usr/bin/python`

When I run 
sudo apt install python-pip python2.7-dev
it gives me an error 

E: Package 'python-pip' has no installation candidate

**Comment by amankumarchagti** [comment]
https://stackoverflow.com/questions/64187581/e-package-python-pip-has-no-installation-candidate
 hope this helps!

**Comment by reddy193** [comment]
> When I run ./w3af_console, it throws out an error Traceback (most recent call last): File "/home/iqbalkhan/w3af/./w3af_console", line 12, in from w3af.core.controllers.dependency_check.dependency_check import dependency_check File "/home/iqbalkhan/w3af/w3af/core/controllers/dependency_check/dependency_check.py", line 26, in from w3af.core.data.db.startup_cfg import StartUpConfig File "/home/iqbalkhan/w3af/w3af/core/data/db/startup_cfg.py", line 22, in import ConfigParser ModuleNotFoundError: No module named 'ConfigParser'

iam facing the same issue  here ,if you found any solution would you help me with it guys.

**Comment by codders** [comment]
Hi @IqbalKhaan , @sammy1881 , @reddy193 ,

w3af is no longer being maintained and only supports python2 (which is end-of-life). You might want to check out the updated project at https://github.com/w4af/w4af
