### ISSUE TITLE
Installation Issue (Kali)

### ISSUE THREAD

**Issue by crypt0-kn1ght** [andresriancho/w3af#18858]
This came up when I tried to execute the command './w3af_console' 

Traceback (most recent call last):
  File "/home/crypt/w3af/./w3af_console", line 12, in <module>
    from w3af.core.controllers.dependency_check.dependency_check import dependency_check
  File "/home/crypt/w3af/w3af/core/controllers/dependency_check/dependency_check.py", line 26, in <module>
    from w3af.core.data.db.startup_cfg import StartUpConfig
  File "/home/crypt/w3af/w3af/core/data/db/startup_cfg.py", line 22, in <module>
    import ConfigParser
ModuleNotFoundError: No module named 'ConfigParser'

**Comment by cherdt** [comment]
You are probably trying to run `w3af_console` using Python 3. Try using Python 2 instead.

**Comment by murraycollingwood** [comment]
FYI. I had the same problem.  
I'm not a python user, but by default I appears to have python v3 installed for some other tool.
Don't know how to install python 2, so I will delete w3af and try another tool.
