### ISSUE TITLE
Config parser error

### ISSUE THREAD

**Issue by Gittester4** [andresriancho/w3af#18872]
I am getting following error can any one help me resolve this error?.

./w3af_console
Traceback (most recent call last):
  File "/home/user/w3af/./w3af_console", line 12, in <module>
    from w3af.core.controllers.dependency_check.dependency_check import dependency_check
  File "/home/user/w3af/w3af/core/controllers/dependency_check/dependency_check.py", line 26, in <module>
    from w3af.core.data.db.startup_cfg import StartUpConfig
  File "/home/user/w3af/w3af/core/data/db/startup_cfg.py", line 22, in <module>
    import ConfigParser

**Comment by codders** [comment]
Hi @Gittester4,

w3af only supports python2, and is incompatible with the current ConfigParser shipped with modern python. Please take a look at https://github.com/w4af/w4af - we have made the effort there to port the project to python3, and the ConfigParser issue is resolved.
