### ISSUE TITLE
w3af installation issue

### ISSUE THREAD

**Issue by Saurabh1973** [andresriancho/w3af#18881]
Hi,

I am Saurabh Pal. I have tried to install w3af in my kali linux. But after installation facing the following issue. Please advice me how to resolve the same.

┌──(saurabh㉿kali)-[~]
└─$ cd w3af       
                                                                                
┌──(saurabh㉿kali)-[~/w3af]
└─$ ./w3af_console    
Traceback (most recent call last):
  File "/home/saurabh/w3af/./w3af_console", line 12, in <module>
    from w3af.core.controllers.dependency_check.dependency_check import dependency_check
  File "/home/saurabh/w3af/w3af/core/controllers/dependency_check/dependency_check.py", line 26, in <module>
    from w3af.core.data.db.startup_cfg import StartUpConfig
  File "/home/saurabh/w3af/w3af/core/data/db/startup_cfg.py", line 22, in <module>
    import ConfigParser
ModuleNotFoundError: No module named 'ConfigParser'
                                                                                
┌──(saurabh㉿kali)-[~/w3af]
└─$

**Comment by thenameispriyam** [comment]
Any solution for the above issue?

**Comment by Saurabh1973** [comment]
Hi,

Here at the time of w3af_console access found the attached issue. Here
which changes are required?

Regards,

Saurabh
+91-9803278524.

**Comment by codders** [comment]
Hi @Saurabh1973 ,

w3af is no longer maintained, and the project only supports python2. The dependencies it requires are not present in Kali linux.

Take a look at https://github.com/w4af/w4af - there the project has been ported to python3 and should work with kali
