### ISSUE TITLE
UnicodeDecodeError @ parsers/swf.py : 'utf8' codec can't decode byte

### ISSUE THREAD

**Issue by 1d3df9903ad** [andresriancho/w3af#3098]
## History
I've applied a potential fix at 0f271ef , closing this (hoping) that it will be fixed by it. Will re-open if required.

## Version Information
```
  Python version: 2.7.3 (default, Feb 27 2014, 20:00:17) [GCC 4.6.3]
  GTK version: 2.24.10
  PyGTK version: 2.24.0
  w3af version:
    w3af - Web Application Attack and Audit Framework
    Version: 1.6.0.2
    Revision: 9361c6e202 - 04 Jun 2014 19:58
    Branch: master
    Local changes: No
    Author: Andres Riancho and the w3af team.
```
## Traceback
```pytb
An exception was found while running grep.strange_parameters on "http://domain/path/foo/core/flash/login.swf | Method: GET". The exception was: "'utf8' codec can't decode byte 0x96 in position 28: invalid start byte" at urlparse.py:urlunsplit():238.The full traceback is:
  File "/home/user/path/foo/w3af/core/controllers/core_helpers/consumers/grep.py", line 76, in run
    plugin.grep_wrapper(request, response)
  File "/home/user/path/foo/w3af/core/controllers/plugins/grep_plugin.py", line 51, in grep_wrapper
    self.grep(fuzzable_request, response)
  File "/home/user/path/foo/w3af/plugins/grep/strange_parameters.py", line 56, in grep
    dp = parser_cache.dpc.get_document_parser_for(response)
  File "/home/user/path/foo/w3af/core/data/parsers/parser_cache.py", line 88, in get_document_parser_for
    res = DocumentParser.DocumentParser(http_response)
  File "/home/user/path/foo/w3af/core/data/parsers/document_parser.py", line 54, in __init__
    self._parser = parser(http_resp)
  File "/home/user/path/foo/w3af/core/data/parsers/swf.py", line 41, in __init__
    self._parse(http_response)
  File "/home/user/path/foo/w3af/core/data/parsers/swf.py", line 105, in _parse
    self._re_extract(swf_body)
  File "/home/user/path/foo/w3af/core/data/parsers/swf.py", line 111, in _re_extract
    re_extract = ReExtract(swf_body, self._base_url, self._encoding)
  File "/home/user/path/foo/w3af/core/data/parsers/utils/re_extract.py", line 51, in __init__
    self._parse(doc_string, relative)
  File "/home/user/path/foo/w3af/core/data/parsers/utils/re_extract.py", line 57, in _parse
    self._extract_full_urls(doc_string)
  File "/home/user/path/foo/w3af/core/data/parsers/utils/re_extract.py", line 91, in _extract_full_urls
    self._re_urls.add(url)
  File "/home/user/path/foo/w3af/core/data/parsers/url.py", line 796, in __hash__
    return hash(self.url_string)
  File "/home/user/path/foo/w3af/core/data/parsers/url.py", line 274, in url_string
    calc = urlparse.urlunparse(data)
  File "/usr/lib/python2.7/urlparse.py", line 223, in urlunparse
    return urlunsplit((scheme, netloc, url, query, fragment))
  File "/usr/lib/python2.7/urlparse.py", line 238, in urlunsplit
    url = url + '?' + query

```

**Comment by andresriancho** [comment]
```
In [4]: u'abc' + '\x96'
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-4-763b6f48b034> in <module>()
----> 1 u'abc' + '\x96'

UnicodeDecodeError: 'ascii' codec can't decode byte 0x96 in position 0: ordinal not in range(128)
```

**Comment by andresriancho** [comment]
```
In [5]: u'abc' + '\x96'.decode('utf8')
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-5-dacc2f2803db> in <module>()
----> 1 u'abc' + '\x96'.decode('utf8')

/usr/lib/python2.7/encodings/utf_8.pyc in decode(input, errors)
     14 
     15 def decode(input, errors='strict'):
---> 16     return codecs.utf_8_decode(input, errors, True)
     17 
     18 class IncrementalEncoder(codecs.IncrementalEncoder):

UnicodeDecodeError: 'utf8' codec can't decode byte 0x96 in position 0: invalid start byte
```
