### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe1 in position 26: invalid continuation byte

### ISSUE THREAD

**Issue by 1d3df9903ad** [andresriancho/w3af#3661]
## Version Information
```
  Python version: 2.7.3 (default, Feb 27 2014, 19:58:35) [GCC 4.6.3]
  GTK version: 2.24.10
  PyGTK version: 2.24.0
  w3af version:
    w3af - Web Application Attack and Audit Framework
    Version: 1.6.0.4
    Revision: 293670749e - 23 Jun 2014 15:50
    Branch: master
    Local changes: No
    Author: Andres Riancho and the w3af team.
```
## Traceback
```pytb
Traceback (most recent call last):
  File "/home/user/Applications/w3af/w3af/core/ui/gui/scanrun.py", line 142, in _showDesc
    self.kbbrowser.pagesControl.activate(num_ids)
  File "/home/user/Applications/w3af/w3af/core/ui/gui/entries.py", line 797, in activate
    self._arrow()
  File "/home/user/Applications/w3af/w3af/core/ui/gui/entries.py", line 823, in _arrow
    self.callback(int(self.page) - 1)
  File "/home/user/Applications/w3af/w3af/core/ui/gui/scanrun.py", line 281, in _pageChange
    self.rrV.response.show_object(historyItem.response)
  File "/home/user/Applications/w3af/w3af/core/ui/gui/reqResViewer.py", line 379, in show_object
    self.synchronize()
  File "/home/user/Applications/w3af/w3af/core/ui/gui/reqResViewer.py", line 331, in synchronize
    view.show_object(self._obj)
  File "/home/user/Applications/w3af/w3af/core/ui/gui/rrviews/raw.py", line 45, in show_object
    self.set_text(obj.dump())
  File "/home/user/Applications/w3af/w3af/core/data/url/HTTPResponse.py", line 657, in dump
    return "%s%s%s" % (self.dump_response_head(), CRLF, body)
  File "/home/user/Applications/w3af/w3af/core/data/url/HTTPResponse.py", line 643, in dump_response_head
    dump_head = "%s%s" % (self.get_status_line(), self.dump_headers())
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe1 in position 26: invalid continuation byte

```

**Comment by andresriancho** [comment]
Duplicates UnicodeDecodeError with details found at dump_response_head() #5416
