### ISSUE TITLE
AssertionError: No calls to SQLiteDBMS can be made after stop().

### ISSUE THREAD

**Issue by 1d3df9903ad** [andresriancho/w3af#4223]
## Version Information
```
  Python version: 2.7.3 (default, Mar 14 2014, 11:57:14) [GCC 4.7.2]
  GTK version: 2.24.10
  PyGTK version: 2.24.0
  w3af version:
    w3af - Web Application Attack and Audit Framework
    Version: 1.6.0.3
    Distribution: Kali Linux
    Author: Andres Riancho and the w3af team.
```
## Traceback
```pytb
Traceback (most recent call last):
  File "/usr/share/w3af/w3af/core/ui/gui/output/message_consumer.py", line 68, in _process_queue
    for _ in self.handle_message(msg):
  File "/usr/share/w3af/w3af/core/ui/gui/tabs/log/messages.py", line 100, in handle_message
    self.all_messages.append((mtype, text))
  File "/usr/share/w3af/w3af/core/data/db/disk_list.py", line 143, in append
    self.db.execute(query, t)
  File "/usr/share/w3af/w3af/core/data/db/dbms.py", line 50, in inner_verify_started
    assert self.sql_executor.is_alive(), msg
AssertionError: No calls to SQLiteDBMS can be made after stop().

```

**Comment by andresriancho** [comment]
Bug is really old, never received these messages again
