### ISSUE TITLE
311 running threads

### ISSUE THREAD

**Issue by 1d3df9903ad** [andresriancho/w3af#5329]
## Version Information
```
  Python version: 2.7.3 (default, Mar 14 2014, 11:57:14) [GCC 4.7.2]
  GTK version: 2.24.10
  PyGTK version: 2.24.0
  w3af version:
    w3af - Web Application Attack and Audit Framework
    Version: 1.6.0.5
    Revision: fd37a1a528 - 08 Sep 2014 17:23
    Branch: master
    Local changes: No
    Author: Andres Riancho and the w3af team.
```
## Traceback
```pytb
Traceback (most recent call last):
  File "/root/w3af/w3af/core/ui/gui/main.py", line 608, in start_scan_wrap
    real_scan_start()
  File "/root/w3af/w3af/core/ui/gui/main.py", line 599, in real_scan_start
    self.w3af.start()
  File "/root/w3af/w3af/core/controllers/w3afCore.py", line 195, in start
    handle_threading_error(self.status.scans_completed)
  File "/root/w3af/w3af/core/controllers/w3afCore.py", line 497, in handle_threading_error
    raise Exception(msg % (active_threads, scans_completed, pprint_threads))
Exception: An error occurred while trying to start a new thread.
 The current process has a total of 331 active threads and has completed 0 scans. The complete list of threads follows:

['<DaemonProcess(AuditorWorker, started daemon -1082733712)>',
 '<DaemonProcess(AuditorWorker, started daemon -1091126416)>',
 '<DaemonProcess(AuditorWorker, started daemon -1099519120)>',
 '<DaemonProcess(AuditorWorker, started daemon -1107911824)>',
 '<DaemonProcess(AuditorWorker, started daemon -1116304528)>',
 '<DaemonProcess(WorkerThread, started daemon -1379509392)>',
 '<DaemonProcess(WorkerThread, started daemon -1387902096)>',
 '<DaemonProcess(WorkerThread, started daemon -1396294800)>',
 '<DaemonProcess(WorkerThread, started daemon -1404687504)>',
 '<DaemonProcess(WorkerThread, started daemon -1413080208)>',
 '<DaemonProcess(WorkerThread, started daemon -1421472912)>',
 '<DaemonProcess(WorkerThread, started daemon -1429865616)>',
 '<DaemonProcess(WorkerThread, started daemon -1438258320)>',
 '<DaemonProcess(WorkerThread, started daemon -1455043728)>',
 '<DaemonProcess(WorkerThread, started daemon -1463436432)>',
 '<DaemonProcess(WorkerThread, started daemon -1471829136)>',
 '<DaemonProcess(WorkerThread, started daemon -1480221840)>',
 '<DaemonProcess(WorkerThread, started daemon -1488614544)>',
 '<DaemonProcess(WorkerThread, started daemon -1497007248)>',
 '<DaemonProcess(WorkerThread, started daemon -1505399952)>',
 '<DaemonProcess(WorkerThread, started daemon -1513792656)>',
 '<DaemonProcess(WorkerThread, started daemon -1522185360)>',
 '<DaemonProcess(WorkerThread, started daemon -1530578064)>',
 '<DaemonProcess(WorkerThread, started daemon -1547048080)>',
 '<DaemonProcess(WorkerThread, started daemon -1555440784)>',
 '<DaemonProcess(WorkerThread, started daemon -1563833488)>',
 '<DaemonProcess(WorkerThread, started daemon -1599829136)>',
 '<DaemonProcess(WorkerThread, started daemon -1644168336)>',
 '<DaemonProcess(WorkerThread, started daemon -1652561040)>',
 '<DaemonProcess(WorkerThread, started daemon -1660953744)>',
 '<DaemonProcess(WorkerThread, started daemon -1669346448)>',
 '<DaemonProcess(WorkerThread, started daemon -1677739152)>',
 '<DaemonProcess(WorkerThread, started daemon -1686131856)>',
 '<DaemonProcess(WorkerThread, started daemon -1694524560)>',
 '<DaemonProcess(WorkerThread, started daemon -1702917264)>',
 '<DaemonProcess(WorkerThread, started daemon -1711309968)>',
 '<DaemonProcess(WorkerThread, started daemon -1720038544)>',
 '<DaemonProcess(WorkerThread, started daemon -1728431248)>',
 '<DaemonProcess(WorkerThread, started daemon -1736823952)>',
 '<DaemonProcess(WorkerThread, started daemon -1745216656)>',
 '<DaemonProcess(WorkerThread, started daemon -1753609360)>',
 '<DaemonProcess(WorkerThread, started daemon -1762002064)>',
 '<DaemonProcess(WorkerThread, started daemon -1770394768)>',
 '<DaemonProcess(WorkerThread, started daemon -1778787472)>',
 '<DaemonProcess(WorkerThread, started daemon -1795572880)>',
 '<DaemonProcess(WorkerThread, started daemon -1812358288)>',
 '<DaemonProcess(WorkerThread, started daemon -1829143696)>',
 '<DaemonProcess(WorkerThread, started daemon -1837536400)>',
 '<DaemonProcess(WorkerThread, started daemon -1845929104)>',
 '<DaemonProcess(WorkerThread, started daemon -1854321808)>',
 '<DaemonProcess(WorkerThread, started daemon -1862714512)>',
 '<DaemonProcess(WorkerThread, started daemon -1871107216)>',
 '<DaemonProcess(WorkerThread, started daemon -1879499920)>',
 '<DaemonProcess(WorkerThread, started daemon -1887892624)>',
 '<DaemonProcess(WorkerThread, started daemon -1896285328)>',
 '<DaemonProcess(WorkerThread, started daemon -1904678032)>',
 '<DaemonProcess(WorkerThread, started daemon -1913070736)>',
 '<DaemonProcess(WorkerThread, started daemon -1921463440)>',
 '<DaemonProcess(WorkerThread, started daemon -1929856144)>',
 '<DaemonProcess(WorkerThread, started daemon -1938248848)>',
 '<DaemonProcess(WorkerThread, started daemon -1946641552)>',
 '<DaemonProcess(WorkerThread, started daemon -1955034256)>',
 '<DaemonProcess(WorkerThread, started daemon -1963426960)>',
 '<DaemonProcess(WorkerThread, started daemon -1971819664)>',
 '<DaemonProcess(WorkerThread, started daemon -1988605072)>',
 '<DaemonProcess(WorkerThread, started daemon -2005390480)>',
 '<DaemonProcess(WorkerThread, started daemon -2022175888)>',
 '<DaemonProcess(WorkerThread, started daemon -2030568592)>',
 '<DaemonProcess(WorkerThread, started daemon -2038961296)>',
 '<DaemonProcess(WorkerThread, started daemon -2047354000)>',
 '<DaemonProcess(WorkerThread, started daemon -2055746704)>',
 '<DaemonProcess(WorkerThread, started daemon -2064139408)>',
 '<DaemonProcess(WorkerThread, started daemon -2072532112)>',
 '<DaemonProcess(WorkerThread, started daemon -2080924816)>',
 '<DaemonProcess(WorkerThread, started daemon -2089317520)>',
 '<DaemonProcess(WorkerThread, started daemon -2097710224)>',
 '<DaemonProcess(WorkerThread, started daemon -2106102928)>',
 '<DaemonProcess(WorkerThread, started daemon -2114495632)>',
 '<DaemonProcess(WorkerThread, started daemon -2122888336)>',
 '<DaemonProcess(WorkerThread, started daemon -2131281040)>',
 '<DaemonProcess(WorkerThread, started daemon -2139673744)>',
 '<DaemonProcess(WorkerThread, started daemon 1005493104)>',
 '<DaemonProcess(WorkerThread, started daemon 100940656)>',
 '<DaemonProcess(WorkerThread, started daemon 1013885808)>',
 '<DaemonProcess(WorkerThread, started daemon 1022278512)>',
 '<DaemonProcess(WorkerThread, started daemon 1030671216)>',
 '<DaemonProcess(WorkerThread, started daemon 1039063920)>',
 '<DaemonProcess(WorkerThread, started daemon 1047456624)>',
 '<DaemonProcess(WorkerThread, started daemon 1055849328)>',
 '<DaemonProcess(WorkerThread, started daemon 1064242032)>',
 '<DaemonProcess(WorkerThread, started daemon 1072634736)>',
 '<DaemonProcess(WorkerThread, started daemon 1081027440)>',
 '<DaemonProcess(WorkerThread, started daemon 1089420144)>',
 '<DaemonProcess(WorkerThread, started daemon 109333360)>',
 '<DaemonProcess(WorkerThread, started daemon 1097812848)>',
 '<DaemonProcess(WorkerThread, started daemon 1106205552)>',
 '<DaemonProcess(WorkerThread, started daemon 1114598256)>',
 '<DaemonProcess(WorkerThread, started daemon 1131383664)>',
 '<DaemonProcess(WorkerThread, started daemon 1148169072)>',
 '<DaemonProcess(WorkerThread, started daemon 1164954480)>',
 '<DaemonProcess(WorkerThread, started daemon 1173347184)>',
 '<DaemonProcess(WorkerThread, started daemon 117726064)>',
 '<DaemonProcess(WorkerThread, started daemon 1181739888)>',
 '<DaemonProcess(WorkerThread, started daemon 1190132592)>',
 '<DaemonProcess(WorkerThread, started daemon 1198525296)>',
 '<DaemonProcess(WorkerThread, started daemon 1206918000)>',
 '<DaemonProcess(WorkerThread, started daemon 1215310704)>',
 '<DaemonProcess(WorkerThread, started daemon 1223703408)>',
 '<DaemonProcess(WorkerThread, started daemon 1232096112)>',
 '<DaemonProcess(WorkerThread, started daemon 1240488816)>',
 '<DaemonProcess(WorkerThread, started daemon 1248881520)>',
 '<DaemonProcess(WorkerThread, started daemon 1257274224)>',
 '<DaemonProcess(WorkerThread, started daemon 126118768)>',
 '<DaemonProcess(WorkerThread, started daemon 1265666928)>',
 '<DaemonProcess(WorkerThread, started daemon 1274059632)>',
 '<DaemonProcess(WorkerThread, started daemon 1282452336)>',
 '<DaemonProcess(WorkerThread, started daemon 1290845040)>',
 '<DaemonProcess(WorkerThread, started daemon 1299237744)>',
 '<DaemonProcess(WorkerThread, started daemon 1307630448)>',
 '<DaemonProcess(WorkerThread, started daemon 1324415856)>',
 '<DaemonProcess(WorkerThread, started daemon 1341201264)>',
 '<DaemonProcess(WorkerThread, started daemon 134511472)>',
 '<DaemonProcess(WorkerThread, started daemon 1366379376)>',
 '<DaemonProcess(WorkerThread, started daemon 1374772080)>',
 '<DaemonProcess(WorkerThread, started daemon 1383164784)>',
 '<DaemonProcess(WorkerThread, started daemon 1391557488)>',
 '<DaemonProcess(WorkerThread, started daemon 1399950192)>',
 '<DaemonProcess(WorkerThread, started daemon 1408342896)>',
 '<DaemonProcess(WorkerThread, started daemon 1416735600)>',
 '<DaemonProcess(WorkerThread, started daemon 1425128304)>',
 '<DaemonProcess(WorkerThread, started daemon 1433521008)>',
 '<DaemonProcess(WorkerThread, started daemon 1441913712)>',
 '<DaemonProcess(WorkerThread, started daemon 1450306416)>',
 '<DaemonProcess(WorkerThread, started daemon 1458699120)>',
 '<DaemonProcess(WorkerThread, started daemon 1467091824)>',
 '<DaemonProcess(WorkerThread, started daemon 1475484528)>',
 '<DaemonProcess(WorkerThread, started daemon 1483877232)>',
 '<DaemonProcess(WorkerThread, started daemon 1492269936)>',
 '<DaemonProcess(WorkerThread, started daemon 1500662640)>',
 '<DaemonProcess(WorkerThread, started daemon 1517448048)>',
 '<DaemonProcess(WorkerThread, started daemon 153054064)>',
 '<DaemonProcess(WorkerThread, started daemon 1534233456)>',
 '<DaemonProcess(WorkerThread, started daemon 1551018864)>',
 '<DaemonProcess(WorkerThread, started daemon 1559411568)>',
 '<DaemonProcess(WorkerThread, started daemon 1567804272)>',
 '<DaemonProcess(WorkerThread, started daemon 1576196976)>',
 '<DaemonProcess(WorkerThread, started daemon 1584589680)>',
 '<DaemonProcess(WorkerThread, started daemon 1592982384)>',
 '<DaemonProcess(WorkerThread, started daemon 1601375088)>',
 '<DaemonProcess(WorkerThread, started daemon 1609767792)>',
 '<DaemonProcess(WorkerThread, started daemon 161446768)>',
 '<DaemonProcess(WorkerThread, started daemon 1618160496)>',
 '<DaemonProcess(WorkerThread, started daemon 1626553200)>',
 '<DaemonProcess(WorkerThread, started daemon 1634945904)>',
 '<DaemonProcess(WorkerThread, started daemon 1643338608)>',
 '<DaemonProcess(WorkerThread, started daemon 1651731312)>',
 '<DaemonProcess(WorkerThread, started daemon 1660124016)>',
 '<DaemonProcess(WorkerThread, started daemon 1668516720)>',
 '<DaemonProcess(WorkerThread, started daemon 1676909424)>',
 '<DaemonProcess(WorkerThread, started daemon 1685302128)>',
 '<DaemonProcess(WorkerThread, started daemon 169839472)>',
 '<DaemonProcess(WorkerThread, started daemon 1702087536)>',
 '<DaemonProcess(WorkerThread, started daemon 1718872944)>',
 '<DaemonProcess(WorkerThread, started daemon 1735658352)>',
 '<DaemonProcess(WorkerThread, started daemon 1744051056)>',
 '<DaemonProcess(WorkerThread, started daemon 1752443760)>',
 '<DaemonProcess(WorkerThread, started daemon 1760836464)>',
 '<DaemonProcess(WorkerThread, started daemon 1769229168)>',
 '<DaemonProcess(WorkerThread, started daemon 1777621872)>',
 '<DaemonProcess(WorkerThread, started daemon 1786014576)>',
 '<DaemonProcess(WorkerThread, started daemon 1794407280)>',
 '<DaemonProcess(WorkerThread, started daemon 1802799984)>',
 '<DaemonProcess(WorkerThread, started daemon 1811192688)>',
 '<DaemonProcess(WorkerThread, started daemon 1819585392)>',
 '<DaemonProcess(WorkerThread, started daemon 1827978096)>',
 '<DaemonProcess(WorkerThread, started daemon 1836370800)>',
 '<DaemonProcess(WorkerThread, started daemon 1844763504)>',
 '<DaemonProcess(WorkerThread, started daemon 1853156208)>',
 '<DaemonProcess(WorkerThread, started daemon 1861548912)>',
 '<DaemonProcess(WorkerThread, started daemon 1869941616)>',
 '<DaemonProcess(WorkerThread, started daemon 1878334320)>',
 '<DaemonProcess(WorkerThread, started daemon 1886727024)>',
 '<DaemonProcess(WorkerThread, started daemon 1903512432)>',
 '<DaemonProcess(WorkerThread, started daemon 1920297840)>',
 '<DaemonProcess(WorkerThread, started daemon 1937083248)>',
 '<DaemonProcess(WorkerThread, started daemon 1945475952)>',
 '<DaemonProcess(WorkerThread, started daemon 1953868656)>',
 '<DaemonProcess(WorkerThread, started daemon 1962261360)>',
 '<DaemonProcess(WorkerThread, started daemon 1970654064)>',
 '<DaemonProcess(WorkerThread, started daemon 1979046768)>',
 '<DaemonProcess(WorkerThread, started daemon 1987439472)>',
 '<DaemonProcess(WorkerThread, started daemon 1995832176)>',
 '<DaemonProcess(WorkerThread, started daemon 2004224880)>',
 '<DaemonProcess(WorkerThread, started daemon 2012617584)>',
 '<DaemonProcess(WorkerThread, started daemon 2021010288)>',
 '<DaemonProcess(WorkerThread, started daemon 2029402992)>',
 '<DaemonProcess(WorkerThread, started daemon 2037795696)>',
 '<DaemonProcess(WorkerThread, started daemon 2046188400)>',
 '<DaemonProcess(WorkerThread, started daemon 2054581104)>',
 '<DaemonProcess(WorkerThread, started daemon 2062973808)>',
 '<DaemonProcess(WorkerThread, started daemon 2071366512)>',
 '<DaemonProcess(WorkerThread, started daemon 2079759216)>',
 '<DaemonProcess(WorkerThread, started daemon 2096544624)>',
 '<DaemonProcess(WorkerThread, started daemon 2113330032)>',
 '<DaemonProcess(WorkerThread, started daemon 2130115440)>',
 '<DaemonProcess(WorkerThread, started daemon 2138508144)>',
 '<DaemonProcess(WorkerThread, started daemon 2146900848)>',
 '<DaemonProcess(WorkerThread, started daemon 266935152)>',
 '<DaemonProcess(WorkerThread, started daemon 275327856)>',
 '<DaemonProcess(WorkerThread, started daemon 283720560)>',
 '<DaemonProcess(WorkerThread, started daemon 292113264)>',
 '<DaemonProcess(WorkerThread, started daemon 300505968)>',
 '<DaemonProcess(WorkerThread, started daemon 308898672)>',
 '<DaemonProcess(WorkerThread, started daemon 317291376)>',
 '<DaemonProcess(WorkerThread, started daemon 325684080)>',
 '<DaemonProcess(WorkerThread, started daemon 334076784)>',
 '<DaemonProcess(WorkerThread, started daemon 350862192)>',
 '<DaemonProcess(WorkerThread, started daemon 367647600)>',
 '<DaemonProcess(WorkerThread, started daemon 384433008)>',
 '<DaemonProcess(WorkerThread, started daemon 392825712)>',
 '<DaemonProcess(WorkerThread, started daemon 401218416)>',
 '<DaemonProcess(WorkerThread, started daemon 409611120)>',
 '<DaemonProcess(WorkerThread, started daemon 418003824)>',
 '<DaemonProcess(WorkerThread, started daemon 426396528)>',
 '<DaemonProcess(WorkerThread, started daemon 434789232)>',
 '<DaemonProcess(WorkerThread, started daemon 443181936)>',
 '<DaemonProcess(WorkerThread, started daemon 451574640)>',
 '<DaemonProcess(WorkerThread, started daemon 459967344)>',
 '<DaemonProcess(WorkerThread, started daemon 468360048)>',
 '<DaemonProcess(WorkerThread, started daemon 476752752)>',
 '<DaemonProcess(WorkerThread, started daemon 485145456)>',
 '<DaemonProcess(WorkerThread, started daemon 493538160)>',
 '<DaemonProcess(WorkerThread, started daemon 501930864)>',
 '<DaemonProcess(WorkerThread, started daemon 510323568)>',
 '<DaemonProcess(WorkerThread, started daemon 518716272)>',
 '<DaemonProcess(WorkerThread, started daemon 527108976)>',
 '<DaemonProcess(WorkerThread, started daemon 543894384)>',
 '<DaemonProcess(WorkerThread, started daemon 560679792)>',
 '<DaemonProcess(WorkerThread, started daemon 577465200)>',
 '<DaemonProcess(WorkerThread, started daemon 585857904)>',
 '<DaemonProcess(WorkerThread, started daemon 594250608)>',
 '<DaemonProcess(WorkerThread, started daemon 602643312)>',
 '<DaemonProcess(WorkerThread, started daemon 611036016)>',
 '<DaemonProcess(WorkerThread, started daemon 619428720)>',
 '<DaemonProcess(WorkerThread, started daemon 627821424)>',
 '<DaemonProcess(WorkerThread, started daemon 636214128)>',
 '<DaemonProcess(WorkerThread, started daemon 644606832)>',
 '<DaemonProcess(WorkerThread, started daemon 652999536)>',
 '<DaemonProcess(WorkerThread, started daemon 661392240)>',
 '<DaemonProcess(WorkerThread, started daemon 669784944)>',
 '<DaemonProcess(WorkerThread, started daemon 678177648)>',
 '<DaemonProcess(WorkerThread, started daemon 686570352)>',
 '<DaemonProcess(WorkerThread, started daemon 694963056)>',
 '<DaemonProcess(WorkerThread, started daemon 703355760)>',
 '<DaemonProcess(WorkerThread, started daemon 711748464)>',
 '<DaemonProcess(WorkerThread, started daemon 720141168)>',
 '<DaemonProcess(WorkerThread, started daemon 728533872)>',
 '<DaemonProcess(WorkerThread, started daemon 745319280)>',
 '<DaemonProcess(WorkerThread, started daemon 75762544)>',
 '<DaemonProcess(WorkerThread, started daemon 762104688)>',
 '<DaemonProcess(WorkerThread, started daemon 778890096)>',
 '<DaemonProcess(WorkerThread, started daemon 787282800)>',
 '<DaemonProcess(WorkerThread, started daemon 795675504)>',
 '<DaemonProcess(WorkerThread, started daemon 804068208)>',
 '<DaemonProcess(WorkerThread, started daemon 812460912)>',
 '<DaemonProcess(WorkerThread, started daemon 820853616)>',
 '<DaemonProcess(WorkerThread, started daemon 829246320)>',
 '<DaemonProcess(WorkerThread, started daemon 837639024)>',
 '<DaemonProcess(WorkerThread, started daemon 846031728)>',
 '<DaemonProcess(WorkerThread, started daemon 854424432)>',
 '<DaemonProcess(WorkerThread, started daemon 862817136)>',
 '<DaemonProcess(WorkerThread, started daemon 871209840)>',
 '<DaemonProcess(WorkerThread, started daemon 879602544)>',
 '<DaemonProcess(WorkerThread, started daemon 887995248)>',
 '<DaemonProcess(WorkerThread, started daemon 896387952)>',
 '<DaemonProcess(WorkerThread, started daemon 904780656)>',
 '<DaemonProcess(WorkerThread, started daemon 913173360)>',
 '<DaemonProcess(WorkerThread, started daemon 92547952)>',
 '<DaemonProcess(WorkerThread, started daemon 929958768)>',
 '<DaemonProcess(WorkerThread, started daemon 946744176)>',
 '<DaemonProcess(WorkerThread, started daemon 963529584)>',
 '<DaemonProcess(WorkerThread, started daemon 971922288)>',
 '<DaemonProcess(WorkerThread, started daemon 980314992)>',
 '<DaemonProcess(WorkerThread, started daemon 988707696)>',
 '<DaemonProcess(WorkerThread, started daemon 997100400)>',
 '<DummyProcess(MainGTKScanner, started daemon 1357986672)>',
 '<SQLiteExecutor(SQLiteExecutor, started daemon -1248330896)>',
 '<Thread(Thread-10, started daemon -1820750992)>',
 '<Thread(Thread-115, started daemon 770497392)>',
 '<Thread(Thread-116, started daemon 753711984)>',
 '<Thread(Thread-117, started daemon 736926576)>',
 '<Thread(Thread-127, started daemon 569072496)>',
 '<Thread(Thread-128, started daemon 552287088)>',
 '<Thread(Thread-130, started daemon 535501680)>',
 '<Thread(Thread-136, started daemon 376040304)>',
 '<Thread(Thread-137, started daemon 359254896)>',
 '<Thread(Thread-139, started daemon 342469488)>',
 '<Thread(Thread-145, started daemon 84155248)>',
 '<Thread(Thread-146, started daemon 67369840)>',
 '<Thread(Thread-147, started daemon 58977136)>',
 '<Thread(Thread-148, started daemon 50584432)>',
 '<Thread(Thread-149, started daemon 42191728)>',
 '<Thread(Thread-150, started daemon 33799024)>',
 '<Thread(Thread-16, started daemon -1980212368)>',
 '<Thread(Thread-17, started daemon -1996997776)>',
 '<Thread(Thread-19, started daemon -2013783184)>',
 '<Thread(Thread-25, started daemon 2121722736)>',
 '<Thread(Thread-26, started daemon 2104937328)>',
 '<Thread(Thread-28, started daemon 2088151920)>',
 '<Thread(Thread-34, started daemon 1928690544)>',
 '<Thread(Thread-35, started daemon 1911905136)>',
 '<Thread(Thread-36, started daemon 1895119728)>',
 '<Thread(Thread-49, started daemon 1727265648)>',
 '<Thread(Thread-50, started daemon 1710480240)>',
 '<Thread(Thread-52, started daemon 1693694832)>',
 '<Thread(Thread-64, started daemon 1542626160)>',
 '<Thread(Thread-65, started daemon 1525840752)>',
 '<Thread(Thread-66, started daemon 1509055344)>',
 '<Thread(Thread-7, started daemon -1787180176)>',
 '<Thread(Thread-73, started daemon 1349593968)>',
 '<Thread(Thread-74, started daemon 1332808560)>',
 '<Thread(Thread-75, started daemon 1316023152)>',
 '<Thread(Thread-8, started daemon -1803965584)>',
 '<Thread(Thread-85, started daemon 1156561776)>',
 '<Thread(Thread-86, started daemon 1139776368)>',
 '<Thread(Thread-87, started daemon 1122990960)>',
 '<Thread(Thread-94, started daemon 955136880)>',
 '<Thread(Thread-95, started daemon 938351472)>',
 '<Thread(Thread-97, started daemon 921566064)>',
 '<_MainThread(MainThread, started -1219230016)>',
 '<output_manager(OutputManager, started daemon -1355715728)>']

```

**Comment by andresriancho** [comment]
Duplicates #6446
