### ISSUE TITLE
"timed out" shouldn't be an ScanMustStopByUnknownReasonExc

### ISSUE THREAD

**Issue by 1d3df9903ad** [andresriancho/w3af#5341]
## Version Information
```
  Python version: 2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]
  GTK version: 2.24.23
  PyGTK version: 2.24.0
  w3af version:
    w3af - Web Application Attack and Audit Framework
    Version: 1.6.0.5
    Revision: 880379b54b - 26 Sep 2014 18:32
    Branch: master
    Local changes: No
    Author: Andres Riancho and the w3af team.
```
## Traceback
```pytb
Traceback (most recent call last):
  File "/home/user/w3af/w3af/core/ui/gui/main.py", line 608, in start_scan_wrap
    real_scan_start()
  File "/home/user/w3af/w3af/core/ui/gui/main.py", line 599, in real_scan_start
    self.w3af.start()
  File "/home/user/w3af/w3af/core/controllers/w3afCore.py", line 187, in start
    self.strategy.start()
  File "/home/user/w3af/w3af/core/controllers/core_helpers/strategy.py", line 98, in start
    self._fuzzable_request_router()
  File "/home/user/w3af/w3af/core/controllers/core_helpers/strategy.py", line 194, in _fuzzable_request_router
    consumer_forced_end)
  File "/home/user/w3af/w3af/core/controllers/core_helpers/strategy.py", line 236, in _route_one_fuzzable_request_batch
    self._handle_consumer_exception(result_item)
  File "/home/user/w3af/w3af/core/controllers/core_helpers/strategy.py", line 291, in _handle_consumer_exception
    self._w3af_core.exception_handler.handle_exception_data(exception_data)
  File "/home/user/w3af/w3af/core/controllers/core_helpers/exception_handler.py", line 72, in handle_exception_data
    exception_data.enabled_plugins)
  File "/home/user/w3af/w3af/core/controllers/core_helpers/consumers/crawl_infrastructure.py", line 402, in _discover_worker
    result = plugin.discover_wrapper(fuzzable_request)
  File "/home/user/w3af/w3af/core/controllers/plugins/crawl_plugin.py", line 49, in crawl_wrapper
    return self.crawl(fuzzable_request_copy)
  File "/home/user/w3af/w3af/plugins/crawl/web_spider.py", line 115, in crawl
    self._extract_links_and_verify(resp, fuzzable_req)
  File "/home/user/w3af/w3af/plugins/crawl/web_spider.py", line 314, in _extract_links_and_verify
    self._urls_to_verify_generator(resp, fuzzable_req))
  File "/home/user/w3af/w3af/core/controllers/threads/threadpool.py", line 83, in map_multi_args
    return self.map_async(one_to_many(func), iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
ScanMustStopByUnknownReasonExc: w3af found too many consecutive errors while performing HTTP requests. In most cases this means that the remote web server is not reachable anymore, the network is down, or a WAF is blocking our tests. The last error message was "timed out".
HTTP timeout error after 10.0 seconds.
timed out
timed out
timed out
timed out
HTTP timeout error after 10.0 seconds.
HTTP timeout error after 10.0 seconds.
timed out
timed out
timed out

```

**Comment by andresriancho** [comment]
Dup ScanMustStopByUnknownReasonExc: The last error message was "timed out". #5191
