### ISSUE TITLE
UnicodeDecodeError with details found at dump_response_head()

### ISSUE THREAD

**Issue by 1d3df9903ad** [andresriancho/w3af#5416]
## Debugging helper
Added this code to add more information to the unicode bugs: https://github.com/andresriancho/w3af/commit/d22f7adbf930f58e4a9df842720335e8af354d3f , and found:

Exception: UnicodeDecodeError found at dump_response_head().
 * Original exception was: "'utf8' codec can't decode byte 0xe9 in position 14: invalid continuation byte".   
 * The response charset is: "utf-8", the content-type: ""
 * The status_line is "'HTTP/1.1 302 D\xe9plac\xe9 Temporairement\r\n'"
 * And the dumped_headers are: "u'content-length: 0\r\nset-cookie: SPRING_SECURITY_REMEMBER_ME_COOKIE=""; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/\r\nserver: Apache-Coyote/1.1\r\nconnection: keep-alive\r\nlocation: http://domain/login?error=true\r\ndate: Wed, 01 Oct 2014 15:57:48 GMT\r\n'".

Looks like the status line is to blame?

## Version Information
```
  Python version: 2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]
  GTK version: 2.24.10
  PyGTK version: 2.24.0
  w3af version:
    w3af - Web Application Attack and Audit Framework
    Version: 1.6.0.5
    Revision: 880379b54b - 26 Sep 2014 18:32
    Branch: master
    Local changes: No
    Author: Andres Riancho and the w3af team.
```
## Traceback
```pytb
Traceback (most recent call last):
  File "/lib/live/mount/persistence/sdb3/tools/w3af/w3af/core/ui/gui/httpLogTab.py", line 461, in _view_in_req_res_viewer
    self.show_req_res_by_id(iid)
  File "/lib/live/mount/persistence/sdb3/tools/w3af/w3af/core/ui/gui/httpLogTab.py", line 489, in show_req_res_by_id
    self._reqResViewer.response.show_object(history_item.response)
  File "/lib/live/mount/persistence/sdb3/tools/w3af/w3af/core/ui/gui/reqResViewer.py", line 385, in show_object
    self.synchronize()
  File "/lib/live/mount/persistence/sdb3/tools/w3af/w3af/core/ui/gui/reqResViewer.py", line 337, in synchronize
    view.show_object(self._obj)
  File "/lib/live/mount/persistence/sdb3/tools/w3af/w3af/core/ui/gui/rrviews/raw.py", line 47, in show_object
    self.set_text(obj.dump())
  File "/lib/live/mount/persistence/sdb3/tools/w3af/w3af/core/data/url/HTTPResponse.py", line 695, in dump
    return "%s%s%s" % (self.dump_response_head(), CRLF, body)
  File "/lib/live/mount/persistence/sdb3/tools/w3af/w3af/core/data/url/HTTPResponse.py", line 679, in dump_response_head
    raise Exception(msg % args)
Exception: UnicodeDecodeError found at dump_response_head(). Original exception was: "'utf8' codec can't decode byte 0xe9 in position 14: invalid continuation byte". The response charset is: "utf-8", the content-type: "", the status_line is "'HTTP/1.1 302 D\xe9plac\xe9 Temporairement\r\n'" and the dumped_headers are: "u'content-length: 0\r\nset-cookie: SPRING_SECURITY_REMEMBER_ME_COOKIE=""; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/\r\nserver: Apache-Coyote/1.1\r\nconnection: keep-alive\r\nlocation: http://domain/login?error=true\r\ndate: Wed, 01 Oct 2014 15:57:48 GMT\r\n'".

```

**Comment by andresriancho** [comment]
https://circleci.com/gh/andresriancho/w3af/1514
