### ISSUE TITLE
GUI: The HTTP request has an invalid header

### ISSUE THREAD

**Issue by 1d3df9903ad** [andresriancho/w3af#5439]
## Version Information
```
  Python version: 2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]
  GTK version: 2.24.23
  PyGTK version: 2.24.0
  w3af version:
    w3af - Web Application Attack and Audit Framework
    Version: 1.6.0.5
    Revision: 880379b54b - 26 Set 2014 18:32
    Branch: master
    Local changes: No
    Author: Andres Riancho and the w3af team.
```
## Traceback
```pytb
Traceback (most recent call last):
  File "/home/user/pcitools/w3af/w3af/core/ui/gui/rrviews/headers.py", line 154, in _headerValueEdited
    self._changed()
  File "/home/user/pcitools/w3af/w3af/core/ui/gui/rrviews/headers.py", line 165, in _changed
    self.parentView.set_object(self.get_object())
  File "/home/user/pcitools/w3af/w3af/core/ui/gui/rrviews/headers.py", line 198, in get_object
    return http_request_parser(head, self._raw.get_text())
  File "/home/user/pcitools/w3af/w3af/core/data/parsers/http_request_parser.py", line 133, in http_request_parser
    raise BaseFrameworkException(msg % header)
BaseFrameworkException: The HTTP request has an invalid header: ".dafitidev.com.br	TRUE	/	FALSE	1443820960	new_checkout	1".

```

**Comment by andresriancho** [comment]
Failed to reproduce
