### ISSUE TITLE
Content-length: 0 will raise unhandled exception

### ISSUE THREAD

**Issue by 1d3df9903ad** [andresriancho/w3af#644]
# User description
What steps will reproduce the problem?
1. android, firefox, proxy through w3af
2. access http://www.memecenter.com/
3. intercept, and then "Send Request" button

What is the expected output? What do you see instead?
I expect no errors.

What operating system are you using?
wheezy

Please provide any additional information below:

# Version Information
```
  Python version: 2.7.3 (default, Jan  2 2013, 13:56:14) [GCC 4.7.2]
  GTK version: 2.24.10
  PyGTK version: 2.24.0
  w3af version:
    w3af - Web Application Attack and Audit Framework
    Version: 1.6
    Revision: 29706f6afd - 06  9月 2013 12:41
    Author: Andres Riancho and the w3af team.
```
# Traceback
```
Traceback (most recent call last):
  File "/home/user/w3af/core/ui/gui/tools/proxywin.py", line 385, in _next
    self._send(None)
  File "/home/user/w3af/core/ui/gui/tools/proxywin.py", line 366, in _send
    self.fuzzable, headers, data)
  File "/home/user/w3af/core/ui/gui/helpers.py", line 205, in __call__
    return func(*args, **kwargs)
  File "/home/user/w3af/core/controllers/daemons/localproxy.py", line 281, in send_raw_request
    raise res
TypeError: object of type 'NoneType' has no len()

```

**Comment by andresriancho** [comment]
Failed to repro with Content-length: 0 will raise unhandled exception
