### ISSUE TITLE
332 threads are running during scan

### ISSUE THREAD

**Issue by 1d3df9903ad** [andresriancho/w3af#6446]
# User description
What steps will reproduce the problem?
1. Targeting http://www.xat.com
2. activating all plugins except evasion
3. Starting the scan.

What is the expected output? What do you see instead?
Expected to see a full crawl and audit, scan finished in four seconds, with no information retrieved.

What operating system are you using?
Linux Ubuntu 14.04

## Version Information
Confirmed bug is present at e4d4d84232 (latest master as of 3 Feb 2015) by #7922

## Traceback
```pytb
Traceback (most recent call last):
  File "/home/user/w3af/w3af/core/ui/gui/main.py", line 608, in start_scan_wrap
    real_scan_start()
  File "/home/user/w3af/w3af/core/ui/gui/main.py", line 599, in real_scan_start
    self.w3af.start()
  File "/home/user/w3af/w3af/core/controllers/w3afCore.py", line 195, in start
    handle_threading_error(self.status.scans_completed)
  File "/home/user/w3af/w3af/core/controllers/w3afCore.py", line 497, in handle_threading_error
    raise Exception(msg % (active_threads, scans_completed, pprint_threads))
Exception: An error occurred while trying to start a new thread.
 The current process has a total of 332 active threads and has completed 0 scans. The complete list of threads follows:

['<DaemonProcess(AuditorWorker, started daemon -1082098880)>',
 '<DaemonProcess(AuditorWorker, started daemon -1090491584)>',
 '<DaemonProcess(AuditorWorker, started daemon -1098884288)>',
 '<DaemonProcess(AuditorWorker, started daemon -1107276992)>',
 '<DaemonProcess(AuditorWorker, started daemon -1115669696)>',
 '<DaemonProcess(AuditorWorker, started daemon -1124062400)>',
 '<DaemonProcess(WorkerThread, started daemon -1157633216)>',
 '<DaemonProcess(WorkerThread, started daemon -1166025920)>',
 '<DaemonProcess(WorkerThread, started daemon -1199596736)>',
 '<DaemonProcess(WorkerThread, started daemon -1207989440)>',
 '<DaemonProcess(WorkerThread, started daemon -1373492416)>',
 '<DaemonProcess(WorkerThread, started daemon -1381885120)>',
 '<DaemonProcess(WorkerThread, started daemon -1390277824)>',
 '<DaemonProcess(WorkerThread, started daemon -1398670528)>',
 '<DaemonProcess(WorkerThread, started daemon -1407063232)>',
 '<DaemonProcess(WorkerThread, started daemon -1415455936)>',
 '<DaemonProcess(WorkerThread, started daemon -1423848640)>',
 '<DaemonProcess(WorkerThread, started daemon -1432241344)>',
 '<DaemonProcess(WorkerThread, started daemon -1440634048)>',
 '<DaemonProcess(WorkerThread, started daemon -1449026752)>',
 '<DaemonProcess(WorkerThread, started daemon -1457419456)>',
 '<DaemonProcess(WorkerThread, started daemon -1465812160)>',
 '<DaemonProcess(WorkerThread, started daemon -1474204864)>',
 '<DaemonProcess(WorkerThread, started daemon -1482597568)>',
 '<DaemonProcess(WorkerThread, started daemon -1490990272)>',
 '<DaemonProcess(WorkerThread, started daemon -1499382976)>',
 '<DaemonProcess(WorkerThread, started daemon -1507775680)>',
 '<DaemonProcess(WorkerThread, started daemon -1516168384)>',
 '<DaemonProcess(WorkerThread, started daemon -1524561088)>',
 '<DaemonProcess(WorkerThread, started daemon -1532953792)>',
 '<DaemonProcess(WorkerThread, started daemon -1541346496)>',
 '<DaemonProcess(WorkerThread, started daemon -1549739200)>',
 '<DaemonProcess(WorkerThread, started daemon -1558131904)>',
 '<DaemonProcess(WorkerThread, started daemon -1670288576)>',
 '<DaemonProcess(WorkerThread, started daemon -1762063552)>',
 '<DaemonProcess(WorkerThread, started daemon -1770456256)>',
 '<DaemonProcess(WorkerThread, started daemon -1778848960)>',
 '<DaemonProcess(WorkerThread, started daemon -1787241664)>',
 '<DaemonProcess(WorkerThread, started daemon -1795634368)>',
 '<DaemonProcess(WorkerThread, started daemon -1804027072)>',
 '<DaemonProcess(WorkerThread, started daemon -1820812480)>',
 '<DaemonProcess(WorkerThread, started daemon -1837597888)>',
 '<DaemonProcess(WorkerThread, started daemon -1854383296)>',
 '<DaemonProcess(WorkerThread, started daemon -1862776000)>',
 '<DaemonProcess(WorkerThread, started daemon -1871168704)>',
 '<DaemonProcess(WorkerThread, started daemon -1879561408)>',
 '<DaemonProcess(WorkerThread, started daemon -1887954112)>',
 '<DaemonProcess(WorkerThread, started daemon -1896346816)>',
 '<DaemonProcess(WorkerThread, started daemon -1904739520)>',
 '<DaemonProcess(WorkerThread, started daemon -1913132224)>',
 '<DaemonProcess(WorkerThread, started daemon -1921524928)>',
 '<DaemonProcess(WorkerThread, started daemon -1929917632)>',
 '<DaemonProcess(WorkerThread, started daemon -1938310336)>',
 '<DaemonProcess(WorkerThread, started daemon -1946703040)>',
 '<DaemonProcess(WorkerThread, started daemon -1976075456)>',
 '<DaemonProcess(WorkerThread, started daemon -1984468160)>',
 '<DaemonProcess(WorkerThread, started daemon -1992860864)>',
 '<DaemonProcess(WorkerThread, started daemon -2001253568)>',
 '<DaemonProcess(WorkerThread, started daemon -2009646272)>',
 '<DaemonProcess(WorkerThread, started daemon -2018038976)>',
 '<DaemonProcess(WorkerThread, started daemon -2026431680)>',
 '<DaemonProcess(WorkerThread, started daemon -2034824384)>',
 '<DaemonProcess(WorkerThread, started daemon -2051609792)>',
 '<DaemonProcess(WorkerThread, started daemon -2068395200)>',
 '<DaemonProcess(WorkerThread, started daemon -2085180608)>',
 '<DaemonProcess(WorkerThread, started daemon -2093573312)>',
 '<DaemonProcess(WorkerThread, started daemon -2101966016)>',
 '<DaemonProcess(WorkerThread, started daemon -2110358720)>',
 '<DaemonProcess(WorkerThread, started daemon -2118751424)>',
 '<DaemonProcess(WorkerThread, started daemon -2127144128)>',
 '<DaemonProcess(WorkerThread, started daemon -2135536832)>',
 '<DaemonProcess(WorkerThread, started daemon -2143929536)>',
 '<DaemonProcess(WorkerThread, started daemon 1003998016)>',
 '<DaemonProcess(WorkerThread, started daemon 100940608)>',
 '<DaemonProcess(WorkerThread, started daemon 1012390720)>',
 '<DaemonProcess(WorkerThread, started daemon 1029176128)>',
 '<DaemonProcess(WorkerThread, started daemon 1045961536)>',
 '<DaemonProcess(WorkerThread, started daemon 1054354240)>',
 '<DaemonProcess(WorkerThread, started daemon 1062746944)>',
 '<DaemonProcess(WorkerThread, started daemon 1071139648)>',
 '<DaemonProcess(WorkerThread, started daemon 1079532352)>',
 '<DaemonProcess(WorkerThread, started daemon 1087925056)>',
 '<DaemonProcess(WorkerThread, started daemon 109333312)>',
 '<DaemonProcess(WorkerThread, started daemon 1096317760)>',
 '<DaemonProcess(WorkerThread, started daemon 1104710464)>',
 '<DaemonProcess(WorkerThread, started daemon 1113103168)>',
 '<DaemonProcess(WorkerThread, started daemon 1121495872)>',
 '<DaemonProcess(WorkerThread, started daemon 1129888576)>',
 '<DaemonProcess(WorkerThread, started daemon 1138281280)>',
 '<DaemonProcess(WorkerThread, started daemon 1146673984)>',
 '<DaemonProcess(WorkerThread, started daemon 1155066688)>',
 '<DaemonProcess(WorkerThread, started daemon 1163459392)>',
 '<DaemonProcess(WorkerThread, started daemon 1171852096)>',
 '<DaemonProcess(WorkerThread, started daemon 117726016)>',
 '<DaemonProcess(WorkerThread, started daemon 1180244800)>',
 '<DaemonProcess(WorkerThread, started daemon 1188637504)>',
 '<DaemonProcess(WorkerThread, started daemon 1197030208)>',
 '<DaemonProcess(WorkerThread, started daemon 1205422912)>',
 '<DaemonProcess(WorkerThread, started daemon 1213815616)>',
 '<DaemonProcess(WorkerThread, started daemon 1222208320)>',
 '<DaemonProcess(WorkerThread, started daemon 1238993728)>',
 '<DaemonProcess(WorkerThread, started daemon 1255779136)>',
 '<DaemonProcess(WorkerThread, started daemon 126118720)>',
 '<DaemonProcess(WorkerThread, started daemon 1272564544)>',
 '<DaemonProcess(WorkerThread, started daemon 1280957248)>',
 '<DaemonProcess(WorkerThread, started daemon 1289349952)>',
 '<DaemonProcess(WorkerThread, started daemon 1297742656)>',
 '<DaemonProcess(WorkerThread, started daemon 1306135360)>',
 '<DaemonProcess(WorkerThread, started daemon 1314528064)>',
 '<DaemonProcess(WorkerThread, started daemon 1322920768)>',
 '<DaemonProcess(WorkerThread, started daemon 1331313472)>',
 '<DaemonProcess(WorkerThread, started daemon 1339706176)>',
 '<DaemonProcess(WorkerThread, started daemon 134511424)>',
 '<DaemonProcess(WorkerThread, started daemon 1348098880)>',
 '<DaemonProcess(WorkerThread, started daemon 1364884288)>',
 '<DaemonProcess(WorkerThread, started daemon 1381669696)>',
 '<DaemonProcess(WorkerThread, started daemon 1398455104)>',
 '<DaemonProcess(WorkerThread, started daemon 1406847808)>',
 '<DaemonProcess(WorkerThread, started daemon 1415240512)>',
 '<DaemonProcess(WorkerThread, started daemon 1423633216)>',
 '<DaemonProcess(WorkerThread, started daemon 1432025920)>',
 '<DaemonProcess(WorkerThread, started daemon 1440418624)>',
 '<DaemonProcess(WorkerThread, started daemon 1448811328)>',
 '<DaemonProcess(WorkerThread, started daemon 1457204032)>',
 '<DaemonProcess(WorkerThread, started daemon 1465596736)>',
 '<DaemonProcess(WorkerThread, started daemon 146996032)>',
 '<DaemonProcess(WorkerThread, started daemon 1473989440)>',
 '<DaemonProcess(WorkerThread, started daemon 1482382144)>',
 '<DaemonProcess(WorkerThread, started daemon 1490774848)>',
 '<DaemonProcess(WorkerThread, started daemon 1499167552)>',
 '<DaemonProcess(WorkerThread, started daemon 1507560256)>',
 '<DaemonProcess(WorkerThread, started daemon 1515952960)>',
 '<DaemonProcess(WorkerThread, started daemon 1524345664)>',
 '<DaemonProcess(WorkerThread, started daemon 1532738368)>',
 '<DaemonProcess(WorkerThread, started daemon 1541131072)>',
 '<DaemonProcess(WorkerThread, started daemon 1549523776)>',
 '<DaemonProcess(WorkerThread, started daemon 155388736)>',
 '<DaemonProcess(WorkerThread, started daemon 1557916480)>',
 '<DaemonProcess(WorkerThread, started daemon 1566309184)>',
 '<DaemonProcess(WorkerThread, started daemon 1574701888)>',
 '<DaemonProcess(WorkerThread, started daemon 1583094592)>',
 '<DaemonProcess(WorkerThread, started daemon 1591487296)>',
 '<DaemonProcess(WorkerThread, started daemon 1599880000)>',
 '<DaemonProcess(WorkerThread, started daemon 1608272704)>',
 '<DaemonProcess(WorkerThread, started daemon 1616665408)>',
 '<DaemonProcess(WorkerThread, started daemon 1625058112)>',
 '<DaemonProcess(WorkerThread, started daemon 1633450816)>',
 '<DaemonProcess(WorkerThread, started daemon 163781440)>',
 '<DaemonProcess(WorkerThread, started daemon 1641843520)>',
 '<DaemonProcess(WorkerThread, started daemon 1658628928)>',
 '<DaemonProcess(WorkerThread, started daemon 1675414336)>',
 '<DaemonProcess(WorkerThread, started daemon 1692199744)>',
 '<DaemonProcess(WorkerThread, started daemon 1700592448)>',
 '<DaemonProcess(WorkerThread, started daemon 17013568)>',
 '<DaemonProcess(WorkerThread, started daemon 1708985152)>',
 '<DaemonProcess(WorkerThread, started daemon 1717377856)>',
 '<DaemonProcess(WorkerThread, started daemon 1725770560)>',
 '<DaemonProcess(WorkerThread, started daemon 1734163264)>',
 '<DaemonProcess(WorkerThread, started daemon 1742555968)>',
 '<DaemonProcess(WorkerThread, started daemon 1750948672)>',
 '<DaemonProcess(WorkerThread, started daemon 1759341376)>',
 '<DaemonProcess(WorkerThread, started daemon 1767734080)>',
 '<DaemonProcess(WorkerThread, started daemon 1776126784)>',
 '<DaemonProcess(WorkerThread, started daemon 1784519488)>',
 '<DaemonProcess(WorkerThread, started daemon 1792912192)>',
 '<DaemonProcess(WorkerThread, started daemon 1809697600)>',
 '<DaemonProcess(WorkerThread, started daemon 1826483008)>',
 '<DaemonProcess(WorkerThread, started daemon 1834875712)>',
 '<DaemonProcess(WorkerThread, started daemon 1851661120)>',
 '<DaemonProcess(WorkerThread, started daemon 1860053824)>',
 '<DaemonProcess(WorkerThread, started daemon 1868446528)>',
 '<DaemonProcess(WorkerThread, started daemon 1876839232)>',
 '<DaemonProcess(WorkerThread, started daemon 1885231936)>',
 '<DaemonProcess(WorkerThread, started daemon 1893624640)>',
 '<DaemonProcess(WorkerThread, started daemon 1902017344)>',
 '<DaemonProcess(WorkerThread, started daemon 1910410048)>',
 '<DaemonProcess(WorkerThread, started daemon 1918802752)>',
 '<DaemonProcess(WorkerThread, started daemon 1927195456)>',
 '<DaemonProcess(WorkerThread, started daemon 1935588160)>',
 '<DaemonProcess(WorkerThread, started daemon 1943980864)>',
 '<DaemonProcess(WorkerThread, started daemon 1952373568)>',
 '<DaemonProcess(WorkerThread, started daemon 1960766272)>',
 '<DaemonProcess(WorkerThread, started daemon 1969158976)>',
 '<DaemonProcess(WorkerThread, started daemon 1977551680)>',
 '<DaemonProcess(WorkerThread, started daemon 1985944384)>',
 '<DaemonProcess(WorkerThread, started daemon 1994337088)>',
 '<DaemonProcess(WorkerThread, started daemon 2002729792)>',
 '<DaemonProcess(WorkerThread, started daemon 2011122496)>',
 '<DaemonProcess(WorkerThread, started daemon 2027907904)>',
 '<DaemonProcess(WorkerThread, started daemon 2053086016)>',
 '<DaemonProcess(WorkerThread, started daemon 2061478720)>',
 '<DaemonProcess(WorkerThread, started daemon 2069871424)>',
 '<DaemonProcess(WorkerThread, started daemon 2078264128)>',
 '<DaemonProcess(WorkerThread, started daemon 2086656832)>',
 '<DaemonProcess(WorkerThread, started daemon 2095049536)>',
 '<DaemonProcess(WorkerThread, started daemon 2103442240)>',
 '<DaemonProcess(WorkerThread, started daemon 2117466944)>',
 '<DaemonProcess(WorkerThread, started daemon 2125859648)>',
 '<DaemonProcess(WorkerThread, started daemon 2134252352)>',
 '<DaemonProcess(WorkerThread, started daemon 2142645056)>',
 '<DaemonProcess(WorkerThread, started daemon 247397184)>',
 '<DaemonProcess(WorkerThread, started daemon 25406272)>',
 '<DaemonProcess(WorkerThread, started daemon 264182592)>',
 '<DaemonProcess(WorkerThread, started daemon 289360704)>',
 '<DaemonProcess(WorkerThread, started daemon 297753408)>',
 '<DaemonProcess(WorkerThread, started daemon 306146112)>',
 '<DaemonProcess(WorkerThread, started daemon 314538816)>',
 '<DaemonProcess(WorkerThread, started daemon 322931520)>',
 '<DaemonProcess(WorkerThread, started daemon 331324224)>',
 '<DaemonProcess(WorkerThread, started daemon 33798976)>',
 '<DaemonProcess(WorkerThread, started daemon 339716928)>',
 '<DaemonProcess(WorkerThread, started daemon 348109632)>',
 '<DaemonProcess(WorkerThread, started daemon 356502336)>',
 '<DaemonProcess(WorkerThread, started daemon 364895040)>',
 '<DaemonProcess(WorkerThread, started daemon 373287744)>',
 '<DaemonProcess(WorkerThread, started daemon 381680448)>',
 '<DaemonProcess(WorkerThread, started daemon 399723328)>',
 '<DaemonProcess(WorkerThread, started daemon 408116032)>',
 '<DaemonProcess(WorkerThread, started daemon 416508736)>',
 '<DaemonProcess(WorkerThread, started daemon 42191680)>',
 '<DaemonProcess(WorkerThread, started daemon 424901440)>',
 '<DaemonProcess(WorkerThread, started daemon 433294144)>',
 '<DaemonProcess(WorkerThread, started daemon 441686848)>',
 '<DaemonProcess(WorkerThread, started daemon 450079552)>',
 '<DaemonProcess(WorkerThread, started daemon 458472256)>',
 '<DaemonProcess(WorkerThread, started daemon 466864960)>',
 '<DaemonProcess(WorkerThread, started daemon 500435776)>',
 '<DaemonProcess(WorkerThread, started daemon 50584384)>',
 '<DaemonProcess(WorkerThread, started daemon 508828480)>',
 '<DaemonProcess(WorkerThread, started daemon 517221184)>',
 '<DaemonProcess(WorkerThread, started daemon 525613888)>',
 '<DaemonProcess(WorkerThread, started daemon 534006592)>',
 '<DaemonProcess(WorkerThread, started daemon 542399296)>',
 '<DaemonProcess(WorkerThread, started daemon 550792000)>',
 '<DaemonProcess(WorkerThread, started daemon 559184704)>',
 '<DaemonProcess(WorkerThread, started daemon 567577408)>',
 '<DaemonProcess(WorkerThread, started daemon 575970112)>',
 '<DaemonProcess(WorkerThread, started daemon 584362816)>',
 '<DaemonProcess(WorkerThread, started daemon 58977088)>',
 '<DaemonProcess(WorkerThread, started daemon 592755520)>',
 '<DaemonProcess(WorkerThread, started daemon 601148224)>',
 '<DaemonProcess(WorkerThread, started daemon 609540928)>',
 '<DaemonProcess(WorkerThread, started daemon 643111744)>',
 '<DaemonProcess(WorkerThread, started daemon 651504448)>',
 '<DaemonProcess(WorkerThread, started daemon 659897152)>',
 '<DaemonProcess(WorkerThread, started daemon 668289856)>',
 '<DaemonProcess(WorkerThread, started daemon 67369792)>',
 '<DaemonProcess(WorkerThread, started daemon 676682560)>',
 '<DaemonProcess(WorkerThread, started daemon 685075264)>',
 '<DaemonProcess(WorkerThread, started daemon 693467968)>',
 '<DaemonProcess(WorkerThread, started daemon 701860672)>',
 '<DaemonProcess(WorkerThread, started daemon 710253376)>',
 '<DaemonProcess(WorkerThread, started daemon 718646080)>',
 '<DaemonProcess(WorkerThread, started daemon 727038784)>',
 '<DaemonProcess(WorkerThread, started daemon 735431488)>',
 '<DaemonProcess(WorkerThread, started daemon 743824192)>',
 '<DaemonProcess(WorkerThread, started daemon 752216896)>',
 '<DaemonProcess(WorkerThread, started daemon 75762496)>',
 '<DaemonProcess(WorkerThread, started daemon 760609600)>',
 '<DaemonProcess(WorkerThread, started daemon 769002304)>',
 '<DaemonProcess(WorkerThread, started daemon 777395008)>',
 '<DaemonProcess(WorkerThread, started daemon 785787712)>',
 '<DaemonProcess(WorkerThread, started daemon 794180416)>',
 '<DaemonProcess(WorkerThread, started daemon 802573120)>',
 '<DaemonProcess(WorkerThread, started daemon 810965824)>',
 '<DaemonProcess(WorkerThread, started daemon 819358528)>',
 '<DaemonProcess(WorkerThread, started daemon 84155200)>',
 '<DaemonProcess(WorkerThread, started daemon 852929344)>',
 '<DaemonProcess(WorkerThread, started daemon 861322048)>',
 '<DaemonProcess(WorkerThread, started daemon 8620864)>',
 '<DaemonProcess(WorkerThread, started daemon 869714752)>',
 '<DaemonProcess(WorkerThread, started daemon 878107456)>',
 '<DaemonProcess(WorkerThread, started daemon 886500160)>',
 '<DaemonProcess(WorkerThread, started daemon 894892864)>',
 '<DaemonProcess(WorkerThread, started daemon 903285568)>',
 '<DaemonProcess(WorkerThread, started daemon 911678272)>',
 '<DaemonProcess(WorkerThread, started daemon 920070976)>',
 '<DaemonProcess(WorkerThread, started daemon 92547904)>',
 '<DaemonProcess(WorkerThread, started daemon 928463680)>',
 '<DaemonProcess(WorkerThread, started daemon 936856384)>',
 '<DaemonProcess(WorkerThread, started daemon 945249088)>',
 '<DaemonProcess(WorkerThread, started daemon 953641792)>',
 '<DaemonProcess(WorkerThread, started daemon 962034496)>',
 '<DaemonProcess(WorkerThread, started daemon 970427200)>',
 '<DaemonProcess(WorkerThread, started daemon 978819904)>',
 '<DaemonProcess(WorkerThread, started daemon 987212608)>',
 '<DummyProcess(MainGTKScanner, started daemon 391330624)>',
 '<SQLiteExecutor(SQLiteExecutor, started daemon -1272452288)>',
 '<Thread(Thread-10, started daemon -1812419776)>',
 '<Thread(Thread-109, started daemon 844536640)>',
 '<Thread(Thread-11, started daemon -1829205184)>',
 '<Thread(Thread-110, started daemon 836143936)>',
 '<Thread(Thread-111, started daemon 827751232)>',
 '<Thread(Thread-12, started daemon -1845990592)>',
 '<Thread(Thread-124, started daemon 634719040)>',
 '<Thread(Thread-125, started daemon 626326336)>',
 '<Thread(Thread-126, started daemon 617933632)>',
 '<Thread(Thread-133, started daemon 492043072)>',
 '<Thread(Thread-134, started daemon 483650368)>',
 '<Thread(Thread-135, started daemon 475257664)>',
 '<Thread(Thread-148, started daemon 280968000)>',
 '<Thread(Thread-149, started daemon 272575296)>',
 '<Thread(Thread-150, started daemon 255789888)>',
 '<Thread(Thread-157, started daemon -1191204032)>',
 '<Thread(Thread-158, started daemon -1182811328)>',
 '<Thread(Thread-159, started daemon -1174418624)>',
 '<Thread(Thread-160, started daemon -1149240512)>',
 '<Thread(Thread-161, started daemon -1140847808)>',
 '<Thread(Thread-162, started daemon -1132455104)>',
 '<Thread(Thread-28, started daemon -2043217088)>',
 '<Thread(Thread-29, started daemon -2060002496)>',
 '<Thread(Thread-30, started daemon -2076787904)>',
 '<Thread(Thread-37, started daemon 2044693312)>',
 '<Thread(Thread-38, started daemon 2036300608)>',
 '<Thread(Thread-39, started daemon 2019515200)>',
 '<Thread(Thread-46, started daemon 1843268416)>',
 '<Thread(Thread-47, started daemon 1818090304)>',
 '<Thread(Thread-48, started daemon 1801304896)>',
 '<Thread(Thread-55, started daemon 1683807040)>',
 '<Thread(Thread-56, started daemon 1667021632)>',
 '<Thread(Thread-57, started daemon 1650236224)>',
 '<Thread(Thread-71, started daemon 1390062400)>',
 '<Thread(Thread-73, started daemon 1373276992)>',
 '<Thread(Thread-75, started daemon 1356491584)>',
 '<Thread(Thread-79, started daemon 1264171840)>',
 '<Thread(Thread-80, started daemon 1247386432)>',
 '<Thread(Thread-81, started daemon 1230601024)>',
 '<Thread(Thread-94, started daemon 1037568832)>',
 '<Thread(Thread-95, started daemon 1020783424)>',
 '<Thread(Thread-96, started daemon 995605312)>',
 '<_MainThread(MainThread, started -1220458176)>',
 '<output_manager(OutputManager, started daemon -1362556096)>']

```

**Comment by andresriancho** [comment]
I'm not really sure how all those WorkerThread instances were created, but it might be because of some circular references to the worker pool. w3af's code has a worker pool instance which might switch between scans, but plugins can still hold a reference to the original one, a solution could be to refactor the plugins to only hold a proxy to the w3afcore:


```diff
diff --git a/w3af/core/controllers/plugins/plugin.py b/w3af/core/controllers/plugins/plugin.py
index a0e3475..26d5316 100644
--- a/w3af/core/controllers/plugins/plugin.py
+++ b/w3af/core/controllers/plugins/plugin.py
@@ -22,6 +22,7 @@ Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 import sys
 import threading
 import Queue
+import weakref
 
 from itertools import repeat
 from tblib.decorators import Error
@@ -55,21 +56,16 @@ class Plugin(Configurable):
         """
         Create some generic attributes that are going to be used by most plugins
         """
-        self._uri_opener = None
-        self.worker_pool = None
-        
         self.output_queue = Queue.Queue()
         self._plugin_lock = threading.RLock()
+        self._w3af_core = None
 
-    def set_worker_pool(self, worker_pool):
-        """
-        Sets the worker pool (at the moment of writing this is a thread pool)
-        that will be used by the plugin to send requests using different
-        threads.
-        """
-        self.worker_pool = worker_pool
+    @property
+    def worker_pool(self):
+        return self._w3af_core.worker_pool
 
-    def set_url_opener(self, url_opener):
+    @property
+    def _uri_opener(self):
         """
         This method should not be overwritten by any plugin (but you are free
         to do it, for example a good idea is to rewrite this method to change
@@ -83,7 +79,15 @@ class Plugin(Configurable):
 
         :return: No value is returned.
         """
-        self._uri_opener = UrlOpenerProxy(url_opener, self)
+        return UrlOpenerProxy(self._w3af_core.uri_opener, self)
+
+    def set_w3af_core(self, w3af_core):
+        """
+        Sets the w3af_core which we'll use to:
+            * Send requests
+            * Perform work in a thread pool
+        """
+        self._w3af_core = weakref.proxy(w3af_core)
 
     def set_options(self, options_list):
         """
```

**Comment by andresriancho** [comment]
```python
self.plugins.zero_enabled_plugins()
```
in the w3afcore makes sure that the plugins from one run are not in memory after the scan is done.

**Comment by andresriancho** [comment]
Threads are tricky:

```
import threading
import time

def foo():
    t = threading.Thread(target=time.sleep, args=(5,), name='SleepThread')
    t.start()

foo()

print([t for t in threading.enumerate()])

time.sleep(7)

print([t for t in threading.enumerate()])
```

vs.

```
import threading
import time

from multiprocessing.dummy import Pool


def foo():
    p = Pool(5)
    #p.terminate()

foo()

print([t for t in threading.enumerate()])

time.sleep(5)

print([t for t in threading.enumerate()])
```

**Comment by andresriancho** [comment]
It's mandatory to terminate() a Pool, if you don't it's going to leave all those threads idling around.

**Comment by andresriancho** [comment]
I made some progress on this issue, now I need to see the results (after merging to master)
