### ISSUE TITLE
UnicodeDecodeError in html output plugin

### ISSUE THREAD

**Issue by andresriancho** [andresriancho/w3af#6645]
Can reproduce with the same info from https://github.com/andresriancho/w3af/issues/6639
```
Exception in thread ConsoleScanThread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/peps/pch/w3af/w3af/core/ui/console/rootMenu.py", line 124, in _real_start
    self._w3af.start()
  File "/home/peps/pch/w3af/w3af/core/controllers/w3afCore.py", line 231, in start
    self.scan_end_hook()
  File "/home/peps/pch/w3af/w3af/core/controllers/w3afCore.py", line 405, in scan_end_hook
    om.out.end_output_plugins()
  File "/home/peps/pch/w3af/w3af/core/controllers/output_manager.py", line 138, in end_output_plugins
    self.__end_output_plugins_impl()
  File "/home/peps/pch/w3af/w3af/core/controllers/output_manager.py", line 149, in __end_output_plugins_impl
    o_plugin.end()
  File "/home/peps/pch/w3af/w3af/plugins/output/html_file.py", line 309, in end
    severity))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 321: ordinal not in range(128)

w3af>>> 
```

**Comment by andresriancho** [comment]
Duplicates html output file - UnicodeDecodeError: 'utf8' codec can't decode byte #4219
