### ISSUE TITLE
target-->set

### ISSUE THREAD

**Issue by pkhadka56** [andresriancho/w3af#7130]
w3af - Web Application Attack and Audit Framework
Version: 1.6.0.5
Distribution: Kali Linux
Author: Andres Riancho and the w3af team.

Python 2.7.3
=======================================
I upgraded the w3af version from 1.2 to 1.6.0.5 then I type following and get errors:

w3af>>> target

Then I type "set" only and get following:

w3af/config:target>>> setTraceback (most recent call last):

Invalid call to set, please see the help:
Set a parameter value.
Syntax: set PARAMETER VALUE
  File "/usr/share/w3af/w3af/core/ui/console/console_ui.py", line 228, in _handleKey
    self._handlers[key]()
  File "/usr/share/w3af/w3af/core/ui/console/console_ui.py", line 321, in _onEnter
    self._execute()
  File "/usr/share/w3af/w3af/core/ui/console/console_ui.py", line 290, in _execute
    menu = self._context.execute(params)
  File "/usr/share/w3af/w3af/core/ui/console/menu.py", line 178, in execute
    return handler(params)
  File "/usr/share/w3af/w3af/core/ui/console/config.py", line 105, in _cmd_set
    if params[0] not in self._options:
IndexError: list index out of range

**Comment by andresriancho** [comment]
Bug confirmed, fixing.

**Comment by andresriancho** [comment]
Fixed, will merge into develop and master in a while.
Will be available in w3af's kali package in more than 1 month (next release)
