### ISSUE TITLE
needs to be updated to support pdfminer 20140328

### ISSUE THREAD

**Issue by archey** [andresriancho/w3af#7262]
It looks like pdfminer updated and removed a func that w3af needs, we have downgraded our version of pdfminer to fix the issue. 

Starting w3af, running on:
Python version: 2.7.9 (default, Dec 11 2014, 04:42:00) [GCC 4.9.2]
GTK version: 2.24.25
PyGTK version: 2.24.0
w3af version:
w3af - Web Application Attack and Audit Framework
Version: 1.6.0.5
Distribution: ArchAssault https://archassault.org
Author: Andres Riancho and the w3af team.
Traceback (most recent call last):
File "/usr/share/w3af/w3af_gui", line 97, in <module>
_main()
File "/usr/share/w3af/w3af_gui", line 93, in _main
sys.exit(main())
File "/usr/share/w3af/w3af_gui", line 88, in main
gui_main(profile, doupdate)
File "/usr/share/w3af/w3af/core/ui/gui/main.py", line 929, in main
MainApp(profile, do_upd)
File "/usr/share/w3af/w3af/core/ui/gui/main.py", line 409, in __init__
self.pcbody = pluginconfig.PluginConfigBody(self, self.w3af)
File "/usr/share/w3af/w3af/core/ui/gui/pluginconfig.py", line 624, in __init__
self.pan = self._buildpan()
File "/usr/share/w3af/w3af/core/ui/gui/pluginconfig.py", line 644, in _buildpan
self.w3af, "standard", self.config_panel)
File "/usr/share/w3af/w3af/core/ui/gui/pluginconfig.py", line 245, in __init__
if self._getEditablePlugin(plugin, plugintype):
File "/usr/share/w3af/w3af/core/ui/gui/pluginconfig.py", line 301, in _getEditablePlugin
plugin = self.w3af.plugins.get_plugin_inst(ptype, pname)
File "/usr/share/w3af/w3af/core/controllers/core_helpers/plugins.py", line 244, in get_plugin_inst
plugin_inst = factory('w3af.plugins.%s.%s' % (plugin_type, plugin_name))
File "/usr/share/w3af/w3af/core/controllers/misc/factory.py", line 46, in factory
raise BaseFrameworkException(msg % (module_name, ie))
BaseFrameworkException: There was an error while importing w3af.plugins.audit.global_redirect: "cannot import name process_pdf".

The newwer pdfminer version in our repo seems to cause issues with w3af as it needs python2-pdfminer or version 20110515-2

https://bugs.archassault.org/task/21?project=2&status[0]= 

We are on the latest version of w3af 1.6.0.5

**Comment by andresriancho** [comment]
Hi there, thanks for reporting this issue. I've already fixed it in the `feature/stopit` branch but still need to stabilize it before merging to develop and then master.

Closing since there is nothing else to do other than making the feature branch stable (nothing to do with this issue really) and merging.

**Comment by archey** [comment]
Thanks as soon as we see the update we will pull it down, I will leave the bug open in our tracker for reference.
