### ISSUE TITLE
Spiderman SSL proxy exception

### ISSUE THREAD

**Issue by kravietz** [andresriancho/w3af#7484]
I have just experienced a crash that was [already reported](https://sourceforge.net/p/w3af/mailman/message/31346067/) back in 2013 but with no further details. I've managed to reproduce it. Here's the config:
```
plugins
crawl spider_man
audit xss
output config console
set verbose true
back
back
target
set target https://cspbuilder.info/
back
start
```
Then, with w3af running, run the following command in another window:
```
curl -vk --proxy 127.0.0.1:44444 https://cspbuilder.info/
```
The proxy immediately crashes with the following backtrack:
```
Created 0 mutants for "Method: GET | https://cspbuilder.info/" ()
Local proxy daemon handling request: localhost.localdomain - "CONNECT ipsec.pl:443 HTTP/1.1" 200 -
SSL 'self.connection' connection state=before/accept initialization
/
The user is navigating through the spider_man proxy.
Traceback for this error: Traceback (most recent call last):
  File "/home/kravietz/w3af/w3af/core/controllers/daemons/proxy.py", line 335, in do_CONNECT
    httpsServer.process_request(conWrap, self.client_address)
  File "/opt/rh/python27/root/usr/lib64/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/opt/rh/python27/root/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/kravietz/w3af/w3af/plugins/crawl/spider_man.py", line 179, in __init__
    w3afProxyHandler.__init__(self, request, client_address, server)
  File "/opt/rh/python27/root/usr/lib64/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/opt/rh/python27/root/usr/lib64/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/home/kravietz/w3af/w3af/core/controllers/daemons/proxy.py", line 75, in handle_one_request
    self.do_ALL()
  File "/home/kravietz/w3af/w3af/plugins/crawl/spider_man.py", line 190, in do_ALL
    path = URL(self.path)
  File "/home/kravietz/w3af/w3af/core/data/parsers/url.py", line 215, in __init__
    raise ValueError('Invalid URL "%s"' % data)
ValueError: Invalid URL "/"

Closing browser-proxy and proxy-site connections.
```

I guess that if this code in `spider_man.py` is just preparing to issue the request to the target server then it should accept the relative `/` URL received from client and pass it on.

**Comment by kravietz** [comment]
Ok, I seem to see how this happens - these are the HTTP requests as seen by the w3af proxy. It looks like the SSL tunnel is established correctly, but then the relative URL that is intended to go to  the tunnel is misdirected:

```
COMMAND CONNECT
Local proxy daemon handling request: localhost.localdomain - "CONNECT ipsec.pl:443 HTTP/1.0" 200 -
SSL 'self.connection' connection state=before/accept initialization
COMMAND GET
The user is navigating through the spider_man proxy.
/
Traceback for this error: Traceback (most recent call last):
  File "/home/kravietz/w3af/w3af/core/controllers/daemons/proxy.py", line 336, in do_CONNECT
    httpsServer.process_request(conWrap, self.client_address)
  File "/opt/rh/python27/root/usr/lib64/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/opt/rh/python27/root/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/kravietz/w3af/w3af/plugins/crawl/spider_man.py", line 179, in __init__
    w3afProxyHandler.__init__(self, request, client_address, server)
  File "/opt/rh/python27/root/usr/lib64/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/opt/rh/python27/root/usr/lib64/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/home/kravietz/w3af/w3af/core/controllers/daemons/proxy.py", line 76, in handle_one_request
    self.do_ALL()
  File "/home/kravietz/w3af/w3af/plugins/crawl/spider_man.py", line 190, in do_ALL
    path = URL(self.path)
  File "/home/kravietz/w3af/w3af/core/data/parsers/url.py", line 215, in __init__
    raise ValueError('Invalid URL "%s"' % data)
ValueError: Invalid URL "/"

Closing browser-proxy and proxy-site connections.
```

**Comment by kravietz** [comment]
@andresriancho Fixed in https://github.com/kravietz/w3af/commit/8fe12c657130e43337507402f70a962ee3017e13

**Comment by andresriancho** [comment]
I just tested this fix and it seems to work, I'm very happy about it since it was affecting users in a very direct way :+1: 

My only concern now is about the code quality, the fix is effective for fixing the issue when using spider_man, but what happens with the rest of the framework?

```
[pablo:/home/pablo/pch/w3af] [w3af] develop ± find . -name '*.py' | xargs grep '(w3afProxyHandler)'
./w3af/core/controllers/daemons/localproxy.py:class w3afLocalProxyHandler(w3afProxyHandler):
./w3af/core/controllers/daemons/proxy.py:        class myProxyHandler(w3afProxyHandler):
./w3af/plugins/crawl/spider_man.py:class ProxyHandler(w3afProxyHandler):
[pablo:/home/pablo/pch/w3af] [w3af] develop ± 
```

There are at least two other locations where `w3afProxyHandler` is sub-classed, and maybe those sub-classes are then sub-classed again (haven't checked). My question is... do we need to move the fix "up" in the inheritance level from `ProxyHandler` to `w3afProxyHandler` so that all the sub-classes get fixed as well?

**Comment by andresriancho** [comment]
PS: I know that I'm rejecting many of your changes because of "technicalities", but I really appreciate your effort and hope you understand my concerns regarding code quality. Thanks!

**Comment by kravietz** [comment]
No problem :) Most of my fixes are quick and ugly, so even if it needs some more work it's definitely desirable to generalize them to the whole project.

**Comment by andresriancho** [comment]
Related with https://github.com/andresriancho/w3af/issues/1269

**Comment by andresriancho** [comment]
Fixed for spiderman (and unittested) now I need to analyze what happens with the other handlers

**Comment by andresriancho** [comment]
Reviewed other implementations, all seem good
