### ISSUE TITLE
output manager - RuntimeError: threads can only be started once

### ISSUE THREAD

**Issue by 1d3df9903ad** [andresriancho/w3af#8214]
## Version Information
```
  Python version: 2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]
  GTK version: 2.24.10
  PyGTK version: 2.24.0
  w3af version:
    w3af - Web Application Attack and Audit Framework
    Version: 1.6.0.3
    Distribution: Kali Linux
    Author: Andres Riancho and the w3af team.
```
## Traceback
```pytb
Traceback (most recent call last):
  File "/usr/share/w3af/w3af/core/ui/gui/main.py", line 524, in quit
    self.w3af.quit()
  File "/usr/share/w3af/w3af/core/controllers/w3afCore.py", line 348, in quit
    self.stop()
  File "/usr/share/w3af/w3af/core/controllers/w3afCore.py", line 305, in stop
    om.out.debug('The user stopped the core, finishing threads...')
  File "/usr/share/w3af/w3af/core/controllers/output_manager.py", line 75, in od_wrapper
    out.start()
  File "/usr/lib/python2.7/multiprocessing/dummy/__init__.py", line 75, in start
    threading.Thread.start(self)
  File "/usr/lib/python2.7/threading.py", line 489, in start
    raise RuntimeError("threads can only be started once")
RuntimeError: threads can only be started once

```

**Comment by andresriancho** [comment]
Dup #8214
