### ISSUE TITLE
Exception in thread PoolTaskHandler

### ISSUE THREAD

**Issue by ST2Labs** [andresriancho/w3af#8410]
w3af - Web Application Attack and Audit Framework
Version: 1.6.45
Revision: 4dce54c3c1 - 18 Feb 2015 19:25
Branch: develop
Local changes: No
Author: Andres Riancho and the w3af team.

./w3af_console
Exception in thread PoolTaskHandler:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
TypeError: _handle_tasks() takes exactly 4 arguments (5 given)

**Comment by andresriancho** [comment]
Duplicates https://github.com/andresriancho/w3af/issues/8368
