### ISSUE TITLE
UnicodeEncodeError @ xml_file

### ISSUE THREAD

**Issue by ST2Labs** [andresriancho/w3af#8859]
# SO 
1 SMP Debian 3.2.57-3
 Python 2.7.3

# VERSION 
w3af - Web Application Attack and Audit Framework
Version: 1.6.48
Revision: 752d51ad39 - 10 Mar 2015 17:45
Branch: develop
Local changes: No
Author: Andres Riancho and the w3af team.

# PROFILE 

profiles
use fast_scan
back

plugins
output xml_file
output config xml_file
set output_file /var/www/wgs/tests/xml/www.icacordoba.com/www.icacordoba.com.xml
back
back

target
set target http://www.icacordoba.com
back

misc-settings
set max_discovery_time 120
set fuzzed_files_extension False
set form_fuzzing_mode b
set fuzz_form_files False
back
http-settings
set timeout 50
set max_file_size 3000000
set max_http_retries 3
back

start
exit

# ERROR
Exception in thread ConsoleScanThread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/share/w3af/w3af/core/ui/console/rootMenu.py", line 124, in _real_start
    self._w3af.start()
  File "/usr/share/w3af/w3af/core/controllers/w3afCore.py", line 235, in start
    self.scan_end_hook()
  File "/usr/share/w3af/w3af/core/controllers/w3afCore.py", line 424, in scan_end_hook
    om.manager.end_output_plugins()
  File "/usr/share/w3af/w3af/core/controllers/output_manager/manager.py", line 137, in end_output_plugins
    self.__end_output_plugins_impl()
  File "/usr/share/w3af/w3af/core/controllers/output_manager/manager.py", line 148, in __end_output_plugins_impl
    o_plugin.end()
  File "/usr/share/w3af/w3af/plugins/output/xml_file.py", line 346, in end
    newl="\n", encoding="UTF-8")
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 1751, in writexml
    node.writexml(writer, indent, addindent, newl)
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 816, in writexml
    node.writexml(writer, indent+addindent, addindent, newl)
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 816, in writexml
    node.writexml(writer, indent+addindent, addindent, newl)
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 812, in writexml
    self.childNodes[0].writexml(writer, '', '', '')
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 1040, in writexml
    _write_data(writer, "%s%s%s" % (indent, self.data, newl))
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 297, in _write_data
    writer.write(data)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 268: ordinal not in range(128)

**Comment by andresriancho** [comment]
@ST2Labs thanks for the detailed bug report, it will really help me fix this issue. Quick question, how long after the scan starts does this issue appear?

**Comment by ST2Labs** [comment]
When finished! Stop core and preparing report XML

**Comment by andresriancho** [comment]
Well, I believe I've fixed it, but after a couple of tests the http://www.icacordoba.com site is not reachable anymore.

Please test yourself, thanks for the bug report!
