### ISSUE TITLE
ScanMustStopByUnknownReasonExc: urlopen error no host given

### ISSUE THREAD

**Issue by 1d3df9903ad** [andresriancho/w3af#8860]
## Description
This already appeared a couple of times before, strange stuff!

## Version Information
```
  Python version: 2.7.3 (default, Mar 14 2014, 11:57:14) [GCC 4.7.2]
  GTK version: 2.24.10
  PyGTK version: 2.24.0
  w3af version:
    w3af - Web Application Attack and Audit Framework
    Version: 1.6.45
    Revision: b7cffaa62a - 26 Фев 2015 13:30
    Branch: master
    Local changes: No
    Author: Andres Riancho and the w3af team.
```
## Traceback
```pytb
Traceback (most recent call last):
  File "/root/w3af/w3af/core/ui/gui/main.py", line 609, in start_scan_wrap
    real_scan_start()
  File "/root/w3af/w3af/core/ui/gui/main.py", line 600, in real_scan_start
    self.w3af.start()
  File "/root/w3af/w3af/core/controllers/w3afCore.py", line 191, in start
    self.strategy.start()
  File "/root/w3af/w3af/core/controllers/core_helpers/strategy.py", line 98, in start
    self._fuzzable_request_router()
  File "/root/w3af/w3af/core/controllers/core_helpers/strategy.py", line 194, in _fuzzable_request_router
    consumer_forced_end)
  File "/root/w3af/w3af/core/controllers/core_helpers/strategy.py", line 236, in _route_one_fuzzable_request_batch
    self._handle_consumer_exception(result_item)
  File "/root/w3af/w3af/core/controllers/core_helpers/strategy.py", line 291, in _handle_consumer_exception
    self._w3af_core.exception_handler.handle_exception_data(exception_data)
  File "/root/w3af/w3af/core/controllers/core_helpers/exception_handler.py", line 72, in handle_exception_data
    exception_data.enabled_plugins)
  File "/root/w3af/w3af/core/controllers/core_helpers/consumers/crawl_infrastructure.py", line 401, in _discover_worker
    result = plugin.discover_wrapper(fuzzable_request)
  File "/root/w3af/w3af/core/controllers/plugins/crawl_plugin.py", line 60, in crawl_wrapper
    return self.crawl(fuzzable_request_copy)
  File "/root/w3af/w3af/plugins/crawl/web_spider.py", line 102, in crawl
    resp = self._uri_opener.send_mutant(fuzzable_req)
  File "/root/w3af/w3af/core/controllers/plugins/plugin.py", line 239, in meth
    return attr(*args, **kwargs)
  File "/root/w3af/w3af/core/data/url/extended_urllib.py", line 310, in send_mutant
    res = functor(*args, **kwargs)
  File "/root/w3af/w3af/core/data/url/extended_urllib.py", line 360, in GET
    return self._send(req, grep=grep)
  File "/root/w3af/w3af/core/data/url/extended_urllib.py", line 535, in _send
    return self._handle_send_urllib_error(req, e, grep, original_url)
  File "/root/w3af/w3af/core/data/url/extended_urllib.py", line 564, in _handle_send_urllib_error
    self._increment_global_error_count(exception)
  File "/root/w3af/w3af/core/data/url/extended_urllib.py", line 672, in _increment_global_error_count
    self._handle_error_on_increment(error, self._last_errors)
  File "/root/w3af/w3af/core/data/url/extended_urllib.py", line 698, in _handle_error_on_increment
    raise self._stop_exception
ScanMustStopByUnknownReasonExc: w3af found too many consecutive errors while performing HTTP requests. In most cases this means that the remote web server is not reachable anymore, the network is down, or a WAF is blocking our tests. The last error message was "<urlopen error no host given>".

```

**Comment by andresriancho** [comment]
Hmm.... how can this be?

```
In [1]: import urllib2

In [2]: urllib2.urlopen('http://')
---------------------------------------------------------------------------
URLError                                  Traceback (most recent call last)
<ipython-input-3-4dcd98b8f0b4> in <module>()
----> 1 urllib2.urlopen('http://')

/usr/lib/python2.7/urllib2.pyc in urlopen(url, data, timeout)
    125     if _opener is None:
    126         _opener = build_opener()
--> 127     return _opener.open(url, data, timeout)
    128 
    129 def install_opener(opener):

/usr/lib/python2.7/urllib2.pyc in open(self, fullurl, data, timeout)
    400         for processor in self.process_request.get(protocol, []):
    401             meth = getattr(processor, meth_name)
--> 402             req = meth(req)
    403 
    404         response = self._open(req, data)

/usr/lib/python2.7/urllib2.pyc in do_request_(self, request)
   1111         host = request.get_host()
   1112         if not host:
-> 1113             raise URLError('no host given')
   1114 
   1115         if request.has_data():  # POST

URLError: <urlopen error no host given>

In [3]: 

```

```
    def test_no_domain(self):
        """
        But we can't specify a URL without a domain!
        """
        self.assertRaises(ValueError, URL, 'http://')
```

**Comment by andresriancho** [comment]
Maybe one of the URL handlers is mistakenly removing the domain?

**Comment by andresriancho** [comment]
https://github.com/andresriancho/w3af/commit/d6ee7a33c71e3333ca2e66c490f6b0ff6a56317c
