### ISSUE TITLE
[Auto-Generated] Bug Report - IOError: [Errno 27] File too large

### ISSUE THREAD

**Issue by 1d3df9903ad** [andresriancho/w3af#9012]
## Version Information
```
  Python version: 2.7.3 (default, Mar 14 2014, 11:57:14) [GCC 4.7.2]
  GTK version: 2.24.10
  PyGTK version: 2.24.0
  w3af version:
    w3af - Web Application Attack and Audit Framework
    Version: 1.6.46
    Distribution: Kali Linux
    Author: Andres Riancho and the w3af team.
```
## Traceback
```pytb
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 525, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 565, in __bootstrap_inner
    (self.name, _format_exc()))
IOError: [Errno 27] File too large

```

**Comment by andresriancho** [comment]
Can't repro
