### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded @ json_iter_setters

### ISSUE THREAD

**Issue by 1d3df9903ad** [andresriancho/w3af#9115]
## Version Information
```
  Python version: 2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]
  GTK version: 2.24.23
  PyGTK version: 2.24.0
  w3af version:
    w3af - Web Application Attack and Audit Framework
    Version: 1.6.48
    Revision: cbd26a6993 - 25 mar 2015 10:49
    Branch: detached HEAD
    Local changes: Yes
    Author: Andres Riancho and the w3af team.
```
## Traceback
```pytb
Traceback (most recent call last):
  File "/w3af/w3af/core/ui/gui/tabs/log/stats.py", line 112, in update
    new_text = self.generate_text(item, set_defaults)
  File "/w3af/w3af/core/ui/gui/tabs/log/stats.py", line 129, in generate_text
    text = '%s: %s' % (item.title, value)
  File "/w3af/w3af/core/data/request/fuzzable_request.py", line 277, in __str__
    parameters = self.get_raw_data().get_param_names()
  File "/w3af/w3af/core/data/dc/generic/data_container.py", line 169, in get_param_names
    return [t.get_name() for t in self.iter_tokens()]
  File "/w3af/w3af/core/data/dc/generic/data_container.py", line 135, in iter_tokens
    for key, val, token_path, setter in self.iter_setters():
  File "/w3af/w3af/core/data/dc/json_container.py", line 130, in iter_setters
    for key, val, setter in json_iter_setters(self._json):
  File "/w3af/w3af/core/data/dc/utils/json_iter_setters.py", line 38, in json_iter_setters
    marbitrary_python_obj = to_mutable(arbitrary_python_obj)
  File "/w3af/w3af/core/data/dc/utils/json_iter_setters.py", line 59, in to_mutable
    value = to_mutable(arbitrary_python_obj.get_value())
  File "/w3af/w3af/core/data/dc/utils/json_iter_setters.py", line 71, in to_mutable
    arbitrary_python_obj[key] = to_mutable(oapo)
  File "/w3af/w3af/core/data/dc/utils/json_iter_setters.py", line 59, in to_mutable
    value = to_mutable(arbitrary_python_obj.get_value())
  File "/w3af/w3af/core/data/dc/utils/json_iter_setters.py", line 59, in to_mutable
    value = to_mutable(arbitrary_python_obj.get_value())
  File "/w3af/w3af/core/data/dc/utils/json_iter_setters.py", line 59, in to_mutable
...
  File "/w3af/w3af/core/data/dc/utils/json_iter_setters.py", line 56, in to_mutable
    return MutableWrapper(arbitrary_python_obj)
RuntimeError: maximum recursion depth exceeded

```

**Comment by andresriancho** [comment]
Failed to reproduce again after fixing #9116
